# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.accommodation_api import router as AccommodationApiRouter
from openapi_server.apis.announcement_api import router as AnnouncementApiRouter
from openapi_server.apis.article_api import router as ArticleApiRouter
from openapi_server.apis.common_api import router as CommonApiRouter
from openapi_server.apis.deprecated_api import router as DeprecatedApiRouter
from openapi_server.apis.distinct_api import router as DistinctApiRouter
from openapi_server.apis.event_api import router as EventApiRouter
from openapi_server.apis.event_short_api import router as EventShortApiRouter
from openapi_server.apis.file_upload_api import router as FileUploadApiRouter
from openapi_server.apis.geo_api import router as GeoApiRouter
from openapi_server.apis.geo_converter_api import router as GeoConverterApiRouter
from openapi_server.apis.json_ld_api import router as JsonLDApiRouter
from openapi_server.apis.location_api import router as LocationApiRouter
from openapi_server.apis.meta_data_api import router as MetaDataApiRouter
from openapi_server.apis.odh_activity_poi_api import router as ODHActivityPoiApiRouter
from openapi_server.apis.odh_tag_api import router as ODHTagApiRouter
from openapi_server.apis.publisher_api import router as PublisherApiRouter
from openapi_server.apis.push_response_api import router as PushResponseApiRouter
from openapi_server.apis.search_api import router as SearchApiRouter
from openapi_server.apis.source_api import router as SourceApiRouter
from openapi_server.apis.tag_api import router as TagApiRouter
from openapi_server.apis.urban_green_api import router as UrbanGreenApiRouter
from openapi_server.apis.venue_api import router as VenueApiRouter
from openapi_server.apis.weather_api import router as WeatherApiRouter
from openapi_server.apis.webcam_info_api import router as WebcamInfoApiRouter

app = FastAPI(
    title="Open Data Hub Tourism Api",
    description="Open Data Hub Tourism Api based on .Net Core with PostgreSQL",
    version="v1",
)

app.include_router(AccommodationApiRouter)
app.include_router(AnnouncementApiRouter)
app.include_router(ArticleApiRouter)
app.include_router(CommonApiRouter)
app.include_router(DeprecatedApiRouter)
app.include_router(DistinctApiRouter)
app.include_router(EventApiRouter)
app.include_router(EventShortApiRouter)
app.include_router(FileUploadApiRouter)
app.include_router(GeoApiRouter)
app.include_router(GeoConverterApiRouter)
app.include_router(JsonLDApiRouter)
app.include_router(LocationApiRouter)
app.include_router(MetaDataApiRouter)
app.include_router(ODHActivityPoiApiRouter)
app.include_router(ODHTagApiRouter)
app.include_router(PublisherApiRouter)
app.include_router(PushResponseApiRouter)
app.include_router(SearchApiRouter)
app.include_router(SourceApiRouter)
app.include_router(TagApiRouter)
app.include_router(UrbanGreenApiRouter)
app.include_router(VenueApiRouter)
app.include_router(WeatherApiRouter)
app.include_router(WebcamInfoApiRouter)
