# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AccoLTSInfo(BaseModel):
    """
    AccoLTSInfo
    """ # noqa: E501
    price_from: Optional[StrictInt] = Field(default=None, alias="PriceFrom")
    price_from_per_unit: Optional[StrictInt] = Field(default=None, alias="PriceFromPerUnit")
    __properties: ClassVar[List[str]] = ["PriceFrom", "PriceFromPerUnit"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccoLTSInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if price_from (nullable) is None
        # and model_fields_set contains the field
        if self.price_from is None and "price_from" in self.model_fields_set:
            _dict['PriceFrom'] = None

        # set to None if price_from_per_unit (nullable) is None
        # and model_fields_set contains the field
        if self.price_from_per_unit is None and "price_from_per_unit" in self.model_fields_set:
            _dict['PriceFromPerUnit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AccoLTSInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "PriceFrom": obj.get("PriceFrom"),
            "PriceFromPerUnit": obj.get("PriceFromPerUnit")
        })
        return _obj


