# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.acco_badges import AccoBadges
from openapi_server.models.acco_boards import AccoBoards
from openapi_server.models.acco_booking_channel import AccoBookingChannel
from openapi_server.models.acco_category import AccoCategory
from openapi_server.models.acco_detail import AccoDetail
from openapi_server.models.acco_feature_linked import AccoFeatureLinked
from openapi_server.models.acco_hgv_info import AccoHGVInfo
from openapi_server.models.acco_lts_info import AccoLTSInfo
from openapi_server.models.acco_overview import AccoOverview
from openapi_server.models.acco_properties import AccoProperties
from openapi_server.models.acco_room_info_linked import AccoRoomInfoLinked
from openapi_server.models.acco_special_features import AccoSpecialFeatures
from openapi_server.models.acco_themes import AccoThemes
from openapi_server.models.acco_type import AccoType
from openapi_server.models.distance_info import DistanceInfo
from openapi_server.models.gps_info import GpsInfo
from openapi_server.models.image_gallery import ImageGallery
from openapi_server.models.independent_data import IndependentData
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.location_info_linked import LocationInfoLinked
from openapi_server.models.metadata import Metadata
from openapi_server.models.mss_response_short import MssResponseShort
from openapi_server.models.odh_tags import ODHTags
from openapi_server.models.operation_schedule import OperationSchedule
from openapi_server.models.rate_plan import RatePlan
from openapi_server.models.related_content import RelatedContent
from openapi_server.models.review import Review
from openapi_server.models.tags import Tags
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AccommodationV2(BaseModel):
    """
    AccommodationV2
    """ # noqa: E501
    review: Optional[Dict[str, Review]] = Field(default=None, alias="Review")
    acco_properties: Optional[AccoProperties] = Field(default=None, alias="AccoProperties")
    operation_schedule: Optional[List[OperationSchedule]] = Field(default=None, alias="OperationSchedule")
    rate_plan: Optional[List[RatePlan]] = Field(default=None, alias="RatePlan")
    trust_you_id: Optional[StrictStr] = Field(default=None, description="Deprecated, use Review.trustyou", alias="TrustYouID")
    trust_you_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Deprecated, use Review.trustyou", alias="TrustYouScore")
    trust_you_results: Optional[StrictInt] = Field(default=None, description="Deprecated, use Review.trustyou", alias="TrustYouResults")
    trust_you_active: Optional[StrictBool] = Field(default=None, description="Deprecated, use Review.trustyou", alias="TrustYouActive")
    trust_you_state: Optional[StrictInt] = Field(default=None, description="Deprecated, use Review.trustyou", alias="TrustYouState")
    has_apartment: Optional[StrictBool] = Field(default=None, description="Deprecated, use AccoProperties.HasApartment", alias="HasApartment")
    has_room: Optional[StrictBool] = Field(default=None, description="Deprecated, use AccoProperties.HasRoom", alias="HasRoom")
    is_camping: Optional[StrictBool] = Field(default=None, description="Deprecated, use AccoProperties.IsCamping", alias="IsCamping")
    is_gastronomy: Optional[StrictBool] = Field(default=None, description="Deprecated, use AccoProperties.IsGastronomy", alias="IsGastronomy")
    is_bookable: Optional[StrictBool] = Field(default=None, description="Deprecated, use AccoProperties.IsBookable", alias="IsBookable")
    is_accommodation: Optional[StrictBool] = Field(default=None, description="Deprecated, use AccoProperties.IsAccommodation", alias="IsAccommodation")
    tv_member: Optional[StrictBool] = Field(default=None, description="Deprecated, use AccoProperties.TVMember", alias="TVMember")
    tags: Optional[List[Tags]] = Field(default=None, alias="Tags")
    tag_ids: Optional[List[StrictStr]] = Field(default=None, alias="TagIds")
    related_content: Optional[List[RelatedContent]] = Field(default=None, alias="RelatedContent")
    additional_properties: Optional[Dict[str, Any]] = Field(default=None, alias="AdditionalProperties")
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    var_self: Optional[StrictStr] = Field(default=None, description="generated field", alias="Self")
    odh_active: Optional[StrictBool] = Field(default=None, description="generated field", alias="OdhActive")
    odh_tags: Optional[List[ODHTags]] = Field(default=None, description="generated field", alias="ODHTags")
    acco_type: Optional[AccoType] = Field(default=None, alias="AccoType")
    acco_category: Optional[AccoCategory] = Field(default=None, alias="AccoCategory")
    acco_boards: Optional[List[AccoBoards]] = Field(default=None, description="generated field", alias="AccoBoards")
    acco_badges: Optional[List[AccoBadges]] = Field(default=None, description="generated field", alias="AccoBadges")
    acco_themes: Optional[List[AccoThemes]] = Field(default=None, description="generated field", alias="AccoThemes")
    acco_special_features: Optional[List[AccoSpecialFeatures]] = Field(default=None, description="generated field", alias="AccoSpecialFeatures")
    features: Optional[List[AccoFeatureLinked]] = Field(default=None, alias="Features")
    acco_room_info: Optional[List[AccoRoomInfoLinked]] = Field(default=None, alias="AccoRoomInfo")
    location_info: Optional[LocationInfoLinked] = Field(default=None, alias="LocationInfo")
    gps_info: Optional[List[GpsInfo]] = Field(default=None, alias="GpsInfo")
    gpstype: Optional[StrictStr] = Field(default=None, description="generated field", alias="Gpstype")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="generated field", alias="Latitude")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="generated field", alias="Longitude")
    altitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="generated field", alias="Altitude")
    altitude_unitof_measure: Optional[StrictStr] = Field(default=None, description="generated field", alias="AltitudeUnitofMeasure")
    gps_points: Optional[Dict[str, GpsInfo]] = Field(default=None, description="generated field", alias="GpsPoints")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    active: Optional[StrictBool] = Field(default=None, description="Data is marked as Active by the data provider", alias="Active")
    hgv_id: Optional[StrictStr] = Field(default=None, description="Accommodation ID on the HGV System, use Mapping instead", alias="HgvId")
    shortname: Optional[StrictStr] = Field(default=None, description="Use AccoDetail.lang.Name", alias="Shortname")
    representation: Optional[StrictInt] = Field(default=None, alias="Representation")
    smg_active: Optional[StrictBool] = Field(default=None, description="Obsolete, use PublishedOn", alias="SmgActive")
    tourism_verein_id: Optional[StrictStr] = Field(default=None, alias="TourismVereinId")
    main_language: Optional[StrictStr] = Field(default=None, alias="MainLanguage")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    distance_info: Optional[DistanceInfo] = Field(default=None, alias="DistanceInfo")
    acco_category_id: Optional[StrictStr] = Field(default=None, alias="AccoCategoryId")
    acco_type_id: Optional[StrictStr] = Field(default=None, alias="AccoTypeId")
    district_id: Optional[StrictStr] = Field(default=None, alias="DistrictId")
    board_ids: Optional[List[StrictStr]] = Field(default=None, alias="BoardIds")
    marketing_group_ids: Optional[List[StrictStr]] = Field(default=None, alias="MarketingGroupIds")
    badge_ids: Optional[List[StrictStr]] = Field(default=None, alias="BadgeIds")
    theme_ids: Optional[List[StrictStr]] = Field(default=None, alias="ThemeIds")
    special_features_ids: Optional[List[StrictStr]] = Field(default=None, alias="SpecialFeaturesIds")
    acco_detail: Optional[Dict[str, AccoDetail]] = Field(default=None, alias="AccoDetail")
    acco_booking_channel: Optional[List[AccoBookingChannel]] = Field(default=None, alias="AccoBookingChannel")
    image_gallery: Optional[List[ImageGallery]] = Field(default=None, alias="ImageGallery")
    gastronomy_id: Optional[StrictStr] = Field(default=None, alias="GastronomyId")
    smg_tags: Optional[List[StrictStr]] = Field(default=None, alias="SmgTags")
    has_language: Optional[List[StrictStr]] = Field(default=None, alias="HasLanguage")
    mss_response_short: Optional[List[MssResponseShort]] = Field(default=None, alias="MssResponseShort")
    independent_data: Optional[IndependentData] = Field(default=None, alias="IndependentData")
    published_on: Optional[List[StrictStr]] = Field(default=None, alias="PublishedOn")
    source: Optional[StrictStr] = Field(default=None, alias="Source")
    mapping: Optional[Dict[str, Dict[str, StrictStr]]] = Field(default=None, alias="Mapping")
    acco_hgv_info: Optional[AccoHGVInfo] = Field(default=None, alias="AccoHGVInfo")
    acco_lts_info: Optional[AccoLTSInfo] = Field(default=None, alias="AccoLTSInfo")
    acco_overview: Optional[AccoOverview] = Field(default=None, alias="AccoOverview")
    __properties: ClassVar[List[str]] = ["Review", "AccoProperties", "OperationSchedule", "RatePlan", "TrustYouID", "TrustYouScore", "TrustYouResults", "TrustYouActive", "TrustYouState", "HasApartment", "HasRoom", "IsCamping", "IsGastronomy", "IsBookable", "IsAccommodation", "TVMember", "Tags", "TagIds", "RelatedContent", "AdditionalProperties", "_Meta", "Self", "OdhActive", "ODHTags", "AccoType", "AccoCategory", "AccoBoards", "AccoBadges", "AccoThemes", "AccoSpecialFeatures", "Features", "AccoRoomInfo", "LocationInfo", "GpsInfo", "Gpstype", "Latitude", "Longitude", "Altitude", "AltitudeUnitofMeasure", "GpsPoints", "LicenseInfo", "Id", "Active", "HgvId", "Shortname", "Representation", "SmgActive", "TourismVereinId", "MainLanguage", "FirstImport", "LastChange", "DistanceInfo", "AccoCategoryId", "AccoTypeId", "DistrictId", "BoardIds", "MarketingGroupIds", "BadgeIds", "ThemeIds", "SpecialFeaturesIds", "AccoDetail", "AccoBookingChannel", "ImageGallery", "GastronomyId", "SmgTags", "HasLanguage", "MssResponseShort", "IndependentData", "PublishedOn", "Source", "Mapping", "AccoHGVInfo", "AccoLTSInfo", "AccoOverview"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccommodationV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "trust_you_id",
                "trust_you_score",
                "trust_you_results",
                "trust_you_active",
                "trust_you_state",
                "has_apartment",
                "has_room",
                "is_camping",
                "is_gastronomy",
                "is_bookable",
                "is_accommodation",
                "tv_member",
                "var_self",
                "odh_active",
                "odh_tags",
                "acco_boards",
                "acco_badges",
                "acco_themes",
                "acco_special_features",
                "gpstype",
                "latitude",
                "longitude",
                "altitude",
                "altitude_unitof_measure",
                "gps_points",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in review (dict)
        _field_dict = {}
        if self.review:
            for _key in self.review:
                if self.review[_key]:
                    _field_dict[_key] = self.review[_key].to_dict()
            _dict['Review'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of acco_properties
        if self.acco_properties:
            _dict['AccoProperties'] = self.acco_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in operation_schedule (list)
        _items = []
        if self.operation_schedule:
            for _item in self.operation_schedule:
                if _item:
                    _items.append(_item.to_dict())
            _dict['OperationSchedule'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rate_plan (list)
        _items = []
        if self.rate_plan:
            for _item in self.rate_plan:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RatePlan'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_content (list)
        _items = []
        if self.related_content:
            for _item in self.related_content:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RelatedContent'] = _items
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in odh_tags (list)
        _items = []
        if self.odh_tags:
            for _item in self.odh_tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ODHTags'] = _items
        # override the default output from pydantic by calling `to_dict()` of acco_type
        if self.acco_type:
            _dict['AccoType'] = self.acco_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acco_category
        if self.acco_category:
            _dict['AccoCategory'] = self.acco_category.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in acco_boards (list)
        _items = []
        if self.acco_boards:
            for _item in self.acco_boards:
                if _item:
                    _items.append(_item.to_dict())
            _dict['AccoBoards'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in acco_badges (list)
        _items = []
        if self.acco_badges:
            for _item in self.acco_badges:
                if _item:
                    _items.append(_item.to_dict())
            _dict['AccoBadges'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in acco_themes (list)
        _items = []
        if self.acco_themes:
            for _item in self.acco_themes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['AccoThemes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in acco_special_features (list)
        _items = []
        if self.acco_special_features:
            for _item in self.acco_special_features:
                if _item:
                    _items.append(_item.to_dict())
            _dict['AccoSpecialFeatures'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in features (list)
        _items = []
        if self.features:
            for _item in self.features:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Features'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in acco_room_info (list)
        _items = []
        if self.acco_room_info:
            for _item in self.acco_room_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['AccoRoomInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of location_info
        if self.location_info:
            _dict['LocationInfo'] = self.location_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in gps_info (list)
        _items = []
        if self.gps_info:
            for _item in self.gps_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['GpsInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in gps_points (dict)
        _field_dict = {}
        if self.gps_points:
            for _key in self.gps_points:
                if self.gps_points[_key]:
                    _field_dict[_key] = self.gps_points[_key].to_dict()
            _dict['GpsPoints'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of distance_info
        if self.distance_info:
            _dict['DistanceInfo'] = self.distance_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in acco_detail (dict)
        _field_dict = {}
        if self.acco_detail:
            for _key in self.acco_detail:
                if self.acco_detail[_key]:
                    _field_dict[_key] = self.acco_detail[_key].to_dict()
            _dict['AccoDetail'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in acco_booking_channel (list)
        _items = []
        if self.acco_booking_channel:
            for _item in self.acco_booking_channel:
                if _item:
                    _items.append(_item.to_dict())
            _dict['AccoBookingChannel'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in image_gallery (list)
        _items = []
        if self.image_gallery:
            for _item in self.image_gallery:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ImageGallery'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in mss_response_short (list)
        _items = []
        if self.mss_response_short:
            for _item in self.mss_response_short:
                if _item:
                    _items.append(_item.to_dict())
            _dict['MssResponseShort'] = _items
        # override the default output from pydantic by calling `to_dict()` of independent_data
        if self.independent_data:
            _dict['IndependentData'] = self.independent_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acco_hgv_info
        if self.acco_hgv_info:
            _dict['AccoHGVInfo'] = self.acco_hgv_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acco_lts_info
        if self.acco_lts_info:
            _dict['AccoLTSInfo'] = self.acco_lts_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acco_overview
        if self.acco_overview:
            _dict['AccoOverview'] = self.acco_overview.to_dict()
        # set to None if review (nullable) is None
        # and model_fields_set contains the field
        if self.review is None and "review" in self.model_fields_set:
            _dict['Review'] = None

        # set to None if operation_schedule (nullable) is None
        # and model_fields_set contains the field
        if self.operation_schedule is None and "operation_schedule" in self.model_fields_set:
            _dict['OperationSchedule'] = None

        # set to None if rate_plan (nullable) is None
        # and model_fields_set contains the field
        if self.rate_plan is None and "rate_plan" in self.model_fields_set:
            _dict['RatePlan'] = None

        # set to None if trust_you_id (nullable) is None
        # and model_fields_set contains the field
        if self.trust_you_id is None and "trust_you_id" in self.model_fields_set:
            _dict['TrustYouID'] = None

        # set to None if trust_you_score (nullable) is None
        # and model_fields_set contains the field
        if self.trust_you_score is None and "trust_you_score" in self.model_fields_set:
            _dict['TrustYouScore'] = None

        # set to None if trust_you_results (nullable) is None
        # and model_fields_set contains the field
        if self.trust_you_results is None and "trust_you_results" in self.model_fields_set:
            _dict['TrustYouResults'] = None

        # set to None if trust_you_active (nullable) is None
        # and model_fields_set contains the field
        if self.trust_you_active is None and "trust_you_active" in self.model_fields_set:
            _dict['TrustYouActive'] = None

        # set to None if trust_you_state (nullable) is None
        # and model_fields_set contains the field
        if self.trust_you_state is None and "trust_you_state" in self.model_fields_set:
            _dict['TrustYouState'] = None

        # set to None if has_room (nullable) is None
        # and model_fields_set contains the field
        if self.has_room is None and "has_room" in self.model_fields_set:
            _dict['HasRoom'] = None

        # set to None if is_camping (nullable) is None
        # and model_fields_set contains the field
        if self.is_camping is None and "is_camping" in self.model_fields_set:
            _dict['IsCamping'] = None

        # set to None if is_gastronomy (nullable) is None
        # and model_fields_set contains the field
        if self.is_gastronomy is None and "is_gastronomy" in self.model_fields_set:
            _dict['IsGastronomy'] = None

        # set to None if is_bookable (nullable) is None
        # and model_fields_set contains the field
        if self.is_bookable is None and "is_bookable" in self.model_fields_set:
            _dict['IsBookable'] = None

        # set to None if is_accommodation (nullable) is None
        # and model_fields_set contains the field
        if self.is_accommodation is None and "is_accommodation" in self.model_fields_set:
            _dict['IsAccommodation'] = None

        # set to None if tv_member (nullable) is None
        # and model_fields_set contains the field
        if self.tv_member is None and "tv_member" in self.model_fields_set:
            _dict['TVMember'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['Tags'] = None

        # set to None if tag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.tag_ids is None and "tag_ids" in self.model_fields_set:
            _dict['TagIds'] = None

        # set to None if related_content (nullable) is None
        # and model_fields_set contains the field
        if self.related_content is None and "related_content" in self.model_fields_set:
            _dict['RelatedContent'] = None

        # set to None if additional_properties (nullable) is None
        # and model_fields_set contains the field
        if self.additional_properties is None and "additional_properties" in self.model_fields_set:
            _dict['AdditionalProperties'] = None

        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if odh_tags (nullable) is None
        # and model_fields_set contains the field
        if self.odh_tags is None and "odh_tags" in self.model_fields_set:
            _dict['ODHTags'] = None

        # set to None if acco_boards (nullable) is None
        # and model_fields_set contains the field
        if self.acco_boards is None and "acco_boards" in self.model_fields_set:
            _dict['AccoBoards'] = None

        # set to None if acco_badges (nullable) is None
        # and model_fields_set contains the field
        if self.acco_badges is None and "acco_badges" in self.model_fields_set:
            _dict['AccoBadges'] = None

        # set to None if acco_themes (nullable) is None
        # and model_fields_set contains the field
        if self.acco_themes is None and "acco_themes" in self.model_fields_set:
            _dict['AccoThemes'] = None

        # set to None if acco_special_features (nullable) is None
        # and model_fields_set contains the field
        if self.acco_special_features is None and "acco_special_features" in self.model_fields_set:
            _dict['AccoSpecialFeatures'] = None

        # set to None if features (nullable) is None
        # and model_fields_set contains the field
        if self.features is None and "features" in self.model_fields_set:
            _dict['Features'] = None

        # set to None if acco_room_info (nullable) is None
        # and model_fields_set contains the field
        if self.acco_room_info is None and "acco_room_info" in self.model_fields_set:
            _dict['AccoRoomInfo'] = None

        # set to None if gps_info (nullable) is None
        # and model_fields_set contains the field
        if self.gps_info is None and "gps_info" in self.model_fields_set:
            _dict['GpsInfo'] = None

        # set to None if gpstype (nullable) is None
        # and model_fields_set contains the field
        if self.gpstype is None and "gpstype" in self.model_fields_set:
            _dict['Gpstype'] = None

        # set to None if altitude (nullable) is None
        # and model_fields_set contains the field
        if self.altitude is None and "altitude" in self.model_fields_set:
            _dict['Altitude'] = None

        # set to None if altitude_unitof_measure (nullable) is None
        # and model_fields_set contains the field
        if self.altitude_unitof_measure is None and "altitude_unitof_measure" in self.model_fields_set:
            _dict['AltitudeUnitofMeasure'] = None

        # set to None if gps_points (nullable) is None
        # and model_fields_set contains the field
        if self.gps_points is None and "gps_points" in self.model_fields_set:
            _dict['GpsPoints'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if hgv_id (nullable) is None
        # and model_fields_set contains the field
        if self.hgv_id is None and "hgv_id" in self.model_fields_set:
            _dict['HgvId'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['Shortname'] = None

        # set to None if representation (nullable) is None
        # and model_fields_set contains the field
        if self.representation is None and "representation" in self.model_fields_set:
            _dict['Representation'] = None

        # set to None if tourism_verein_id (nullable) is None
        # and model_fields_set contains the field
        if self.tourism_verein_id is None and "tourism_verein_id" in self.model_fields_set:
            _dict['TourismVereinId'] = None

        # set to None if main_language (nullable) is None
        # and model_fields_set contains the field
        if self.main_language is None and "main_language" in self.model_fields_set:
            _dict['MainLanguage'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if acco_category_id (nullable) is None
        # and model_fields_set contains the field
        if self.acco_category_id is None and "acco_category_id" in self.model_fields_set:
            _dict['AccoCategoryId'] = None

        # set to None if acco_type_id (nullable) is None
        # and model_fields_set contains the field
        if self.acco_type_id is None and "acco_type_id" in self.model_fields_set:
            _dict['AccoTypeId'] = None

        # set to None if district_id (nullable) is None
        # and model_fields_set contains the field
        if self.district_id is None and "district_id" in self.model_fields_set:
            _dict['DistrictId'] = None

        # set to None if board_ids (nullable) is None
        # and model_fields_set contains the field
        if self.board_ids is None and "board_ids" in self.model_fields_set:
            _dict['BoardIds'] = None

        # set to None if marketing_group_ids (nullable) is None
        # and model_fields_set contains the field
        if self.marketing_group_ids is None and "marketing_group_ids" in self.model_fields_set:
            _dict['MarketingGroupIds'] = None

        # set to None if badge_ids (nullable) is None
        # and model_fields_set contains the field
        if self.badge_ids is None and "badge_ids" in self.model_fields_set:
            _dict['BadgeIds'] = None

        # set to None if theme_ids (nullable) is None
        # and model_fields_set contains the field
        if self.theme_ids is None and "theme_ids" in self.model_fields_set:
            _dict['ThemeIds'] = None

        # set to None if special_features_ids (nullable) is None
        # and model_fields_set contains the field
        if self.special_features_ids is None and "special_features_ids" in self.model_fields_set:
            _dict['SpecialFeaturesIds'] = None

        # set to None if acco_detail (nullable) is None
        # and model_fields_set contains the field
        if self.acco_detail is None and "acco_detail" in self.model_fields_set:
            _dict['AccoDetail'] = None

        # set to None if acco_booking_channel (nullable) is None
        # and model_fields_set contains the field
        if self.acco_booking_channel is None and "acco_booking_channel" in self.model_fields_set:
            _dict['AccoBookingChannel'] = None

        # set to None if image_gallery (nullable) is None
        # and model_fields_set contains the field
        if self.image_gallery is None and "image_gallery" in self.model_fields_set:
            _dict['ImageGallery'] = None

        # set to None if gastronomy_id (nullable) is None
        # and model_fields_set contains the field
        if self.gastronomy_id is None and "gastronomy_id" in self.model_fields_set:
            _dict['GastronomyId'] = None

        # set to None if smg_tags (nullable) is None
        # and model_fields_set contains the field
        if self.smg_tags is None and "smg_tags" in self.model_fields_set:
            _dict['SmgTags'] = None

        # set to None if has_language (nullable) is None
        # and model_fields_set contains the field
        if self.has_language is None and "has_language" in self.model_fields_set:
            _dict['HasLanguage'] = None

        # set to None if mss_response_short (nullable) is None
        # and model_fields_set contains the field
        if self.mss_response_short is None and "mss_response_short" in self.model_fields_set:
            _dict['MssResponseShort'] = None

        # set to None if published_on (nullable) is None
        # and model_fields_set contains the field
        if self.published_on is None and "published_on" in self.model_fields_set:
            _dict['PublishedOn'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['Source'] = None

        # set to None if mapping (nullable) is None
        # and model_fields_set contains the field
        if self.mapping is None and "mapping" in self.model_fields_set:
            _dict['Mapping'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AccommodationV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Review": dict(
                (_k, Review.from_dict(_v))
                for _k, _v in obj.get("Review").items()
            )
            if obj.get("Review") is not None
            else None,
            "AccoProperties": AccoProperties.from_dict(obj.get("AccoProperties")) if obj.get("AccoProperties") is not None else None,
            "OperationSchedule": [OperationSchedule.from_dict(_item) for _item in obj.get("OperationSchedule")] if obj.get("OperationSchedule") is not None else None,
            "RatePlan": [RatePlan.from_dict(_item) for _item in obj.get("RatePlan")] if obj.get("RatePlan") is not None else None,
            "TrustYouID": obj.get("TrustYouID"),
            "TrustYouScore": obj.get("TrustYouScore"),
            "TrustYouResults": obj.get("TrustYouResults"),
            "TrustYouActive": obj.get("TrustYouActive"),
            "TrustYouState": obj.get("TrustYouState"),
            "HasApartment": obj.get("HasApartment"),
            "HasRoom": obj.get("HasRoom"),
            "IsCamping": obj.get("IsCamping"),
            "IsGastronomy": obj.get("IsGastronomy"),
            "IsBookable": obj.get("IsBookable"),
            "IsAccommodation": obj.get("IsAccommodation"),
            "TVMember": obj.get("TVMember"),
            "Tags": [Tags.from_dict(_item) for _item in obj.get("Tags")] if obj.get("Tags") is not None else None,
            "TagIds": obj.get("TagIds"),
            "RelatedContent": [RelatedContent.from_dict(_item) for _item in obj.get("RelatedContent")] if obj.get("RelatedContent") is not None else None,
            "AdditionalProperties": obj.get("AdditionalProperties"),
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "Self": obj.get("Self"),
            "OdhActive": obj.get("OdhActive"),
            "ODHTags": [ODHTags.from_dict(_item) for _item in obj.get("ODHTags")] if obj.get("ODHTags") is not None else None,
            "AccoType": AccoType.from_dict(obj.get("AccoType")) if obj.get("AccoType") is not None else None,
            "AccoCategory": AccoCategory.from_dict(obj.get("AccoCategory")) if obj.get("AccoCategory") is not None else None,
            "AccoBoards": [AccoBoards.from_dict(_item) for _item in obj.get("AccoBoards")] if obj.get("AccoBoards") is not None else None,
            "AccoBadges": [AccoBadges.from_dict(_item) for _item in obj.get("AccoBadges")] if obj.get("AccoBadges") is not None else None,
            "AccoThemes": [AccoThemes.from_dict(_item) for _item in obj.get("AccoThemes")] if obj.get("AccoThemes") is not None else None,
            "AccoSpecialFeatures": [AccoSpecialFeatures.from_dict(_item) for _item in obj.get("AccoSpecialFeatures")] if obj.get("AccoSpecialFeatures") is not None else None,
            "Features": [AccoFeatureLinked.from_dict(_item) for _item in obj.get("Features")] if obj.get("Features") is not None else None,
            "AccoRoomInfo": [AccoRoomInfoLinked.from_dict(_item) for _item in obj.get("AccoRoomInfo")] if obj.get("AccoRoomInfo") is not None else None,
            "LocationInfo": LocationInfoLinked.from_dict(obj.get("LocationInfo")) if obj.get("LocationInfo") is not None else None,
            "GpsInfo": [GpsInfo.from_dict(_item) for _item in obj.get("GpsInfo")] if obj.get("GpsInfo") is not None else None,
            "Gpstype": obj.get("Gpstype"),
            "Latitude": obj.get("Latitude"),
            "Longitude": obj.get("Longitude"),
            "Altitude": obj.get("Altitude"),
            "AltitudeUnitofMeasure": obj.get("AltitudeUnitofMeasure"),
            "GpsPoints": dict(
                (_k, GpsInfo.from_dict(_v))
                for _k, _v in obj.get("GpsPoints").items()
            )
            if obj.get("GpsPoints") is not None
            else None,
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "Id": obj.get("Id"),
            "Active": obj.get("Active"),
            "HgvId": obj.get("HgvId"),
            "Shortname": obj.get("Shortname"),
            "Representation": obj.get("Representation"),
            "SmgActive": obj.get("SmgActive"),
            "TourismVereinId": obj.get("TourismVereinId"),
            "MainLanguage": obj.get("MainLanguage"),
            "FirstImport": obj.get("FirstImport"),
            "LastChange": obj.get("LastChange"),
            "DistanceInfo": DistanceInfo.from_dict(obj.get("DistanceInfo")) if obj.get("DistanceInfo") is not None else None,
            "AccoCategoryId": obj.get("AccoCategoryId"),
            "AccoTypeId": obj.get("AccoTypeId"),
            "DistrictId": obj.get("DistrictId"),
            "BoardIds": obj.get("BoardIds"),
            "MarketingGroupIds": obj.get("MarketingGroupIds"),
            "BadgeIds": obj.get("BadgeIds"),
            "ThemeIds": obj.get("ThemeIds"),
            "SpecialFeaturesIds": obj.get("SpecialFeaturesIds"),
            "AccoDetail": dict(
                (_k, AccoDetail.from_dict(_v))
                for _k, _v in obj.get("AccoDetail").items()
            )
            if obj.get("AccoDetail") is not None
            else None,
            "AccoBookingChannel": [AccoBookingChannel.from_dict(_item) for _item in obj.get("AccoBookingChannel")] if obj.get("AccoBookingChannel") is not None else None,
            "ImageGallery": [ImageGallery.from_dict(_item) for _item in obj.get("ImageGallery")] if obj.get("ImageGallery") is not None else None,
            "GastronomyId": obj.get("GastronomyId"),
            "SmgTags": obj.get("SmgTags"),
            "HasLanguage": obj.get("HasLanguage"),
            "MssResponseShort": [MssResponseShort.from_dict(_item) for _item in obj.get("MssResponseShort")] if obj.get("MssResponseShort") is not None else None,
            "IndependentData": IndependentData.from_dict(obj.get("IndependentData")) if obj.get("IndependentData") is not None else None,
            "PublishedOn": obj.get("PublishedOn"),
            "Source": obj.get("Source"),
            "Mapping": obj.get("Mapping"),
            "AccoHGVInfo": AccoHGVInfo.from_dict(obj.get("AccoHGVInfo")) if obj.get("AccoHGVInfo") is not None else None,
            "AccoLTSInfo": AccoLTSInfo.from_dict(obj.get("AccoLTSInfo")) if obj.get("AccoLTSInfo") is not None else None,
            "AccoOverview": AccoOverview.from_dict(obj.get("AccoOverview")) if obj.get("AccoOverview") is not None else None
        })
        return _obj


