# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.detail import Detail
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.metadata import Metadata
from openapi_server.models.municipality_link import MunicipalityLink
from openapi_server.models.region_link import RegionLink
from openapi_server.models.ski_area_link import SkiAreaLink
from openapi_server.models.tourism_association_link import TourismAssociationLink
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AreaLinked(BaseModel):
    """
    AreaLinked
    """ # noqa: E501
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    var_self: Optional[StrictStr] = Field(default=None, description="generated field", alias="Self")
    odh_active: Optional[StrictBool] = Field(default=None, description="generated field", alias="OdhActive")
    region: Optional[RegionLink] = Field(default=None, alias="Region")
    municipality: Optional[MunicipalityLink] = Field(default=None, alias="Municipality")
    tourismassociation: Optional[TourismAssociationLink] = Field(default=None, alias="Tourismassociation")
    ski_area: Optional[SkiAreaLink] = Field(default=None, alias="SkiArea")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    active: Optional[StrictBool] = Field(default=None, alias="Active")
    smg_active: Optional[StrictBool] = Field(default=None, description="Obsolete, use PublishedOn", alias="SmgActive")
    shortname: Optional[StrictStr] = Field(default=None, alias="Shortname")
    custom_id: Optional[StrictStr] = Field(default=None, alias="CustomId")
    region_id: Optional[StrictStr] = Field(default=None, alias="RegionId")
    tourismverein_id: Optional[StrictStr] = Field(default=None, alias="TourismvereinId")
    municipality_id: Optional[StrictStr] = Field(default=None, alias="MunicipalityId")
    ski_area_id: Optional[StrictStr] = Field(default=None, alias="SkiAreaID")
    gid: Optional[StrictStr] = Field(default=None, alias="GID")
    lts_id: Optional[StrictStr] = Field(default=None, alias="LtsID")
    area_type: Optional[StrictStr] = Field(default=None, alias="AreaType")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    mapping: Optional[Dict[str, Dict[str, StrictStr]]] = Field(default=None, alias="Mapping")
    source: Optional[StrictStr] = Field(default=None, alias="Source")
    detail: Optional[Dict[str, Detail]] = Field(default=None, alias="Detail")
    published_on: Optional[List[StrictStr]] = Field(default=None, alias="PublishedOn")
    __properties: ClassVar[List[str]] = ["_Meta", "Self", "OdhActive", "Region", "Municipality", "Tourismassociation", "SkiArea", "LicenseInfo", "Id", "Active", "SmgActive", "Shortname", "CustomId", "RegionId", "TourismvereinId", "MunicipalityId", "SkiAreaID", "GID", "LtsID", "AreaType", "LastChange", "FirstImport", "Mapping", "Source", "Detail", "PublishedOn"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AreaLinked from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_self",
                "odh_active",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of region
        if self.region:
            _dict['Region'] = self.region.to_dict()
        # override the default output from pydantic by calling `to_dict()` of municipality
        if self.municipality:
            _dict['Municipality'] = self.municipality.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tourismassociation
        if self.tourismassociation:
            _dict['Tourismassociation'] = self.tourismassociation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ski_area
        if self.ski_area:
            _dict['SkiArea'] = self.ski_area.to_dict()
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in detail (dict)
        _field_dict = {}
        if self.detail:
            for _key in self.detail:
                if self.detail[_key]:
                    _field_dict[_key] = self.detail[_key].to_dict()
            _dict['Detail'] = _field_dict
        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['Shortname'] = None

        # set to None if custom_id (nullable) is None
        # and model_fields_set contains the field
        if self.custom_id is None and "custom_id" in self.model_fields_set:
            _dict['CustomId'] = None

        # set to None if region_id (nullable) is None
        # and model_fields_set contains the field
        if self.region_id is None and "region_id" in self.model_fields_set:
            _dict['RegionId'] = None

        # set to None if tourismverein_id (nullable) is None
        # and model_fields_set contains the field
        if self.tourismverein_id is None and "tourismverein_id" in self.model_fields_set:
            _dict['TourismvereinId'] = None

        # set to None if municipality_id (nullable) is None
        # and model_fields_set contains the field
        if self.municipality_id is None and "municipality_id" in self.model_fields_set:
            _dict['MunicipalityId'] = None

        # set to None if ski_area_id (nullable) is None
        # and model_fields_set contains the field
        if self.ski_area_id is None and "ski_area_id" in self.model_fields_set:
            _dict['SkiAreaID'] = None

        # set to None if gid (nullable) is None
        # and model_fields_set contains the field
        if self.gid is None and "gid" in self.model_fields_set:
            _dict['GID'] = None

        # set to None if lts_id (nullable) is None
        # and model_fields_set contains the field
        if self.lts_id is None and "lts_id" in self.model_fields_set:
            _dict['LtsID'] = None

        # set to None if area_type (nullable) is None
        # and model_fields_set contains the field
        if self.area_type is None and "area_type" in self.model_fields_set:
            _dict['AreaType'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if mapping (nullable) is None
        # and model_fields_set contains the field
        if self.mapping is None and "mapping" in self.model_fields_set:
            _dict['Mapping'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['Source'] = None

        # set to None if detail (nullable) is None
        # and model_fields_set contains the field
        if self.detail is None and "detail" in self.model_fields_set:
            _dict['Detail'] = None

        # set to None if published_on (nullable) is None
        # and model_fields_set contains the field
        if self.published_on is None and "published_on" in self.model_fields_set:
            _dict['PublishedOn'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AreaLinked from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "Self": obj.get("Self"),
            "OdhActive": obj.get("OdhActive"),
            "Region": RegionLink.from_dict(obj.get("Region")) if obj.get("Region") is not None else None,
            "Municipality": MunicipalityLink.from_dict(obj.get("Municipality")) if obj.get("Municipality") is not None else None,
            "Tourismassociation": TourismAssociationLink.from_dict(obj.get("Tourismassociation")) if obj.get("Tourismassociation") is not None else None,
            "SkiArea": SkiAreaLink.from_dict(obj.get("SkiArea")) if obj.get("SkiArea") is not None else None,
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "Id": obj.get("Id"),
            "Active": obj.get("Active"),
            "SmgActive": obj.get("SmgActive"),
            "Shortname": obj.get("Shortname"),
            "CustomId": obj.get("CustomId"),
            "RegionId": obj.get("RegionId"),
            "TourismvereinId": obj.get("TourismvereinId"),
            "MunicipalityId": obj.get("MunicipalityId"),
            "SkiAreaID": obj.get("SkiAreaID"),
            "GID": obj.get("GID"),
            "LtsID": obj.get("LtsID"),
            "AreaType": obj.get("AreaType"),
            "LastChange": obj.get("LastChange"),
            "FirstImport": obj.get("FirstImport"),
            "Mapping": obj.get("Mapping"),
            "Source": obj.get("Source"),
            "Detail": dict(
                (_k, Detail.from_dict(_v))
                for _k, _v in obj.get("Detail").items()
            )
            if obj.get("Detail") is not None
            else None,
            "PublishedOn": obj.get("PublishedOn")
        })
        return _obj


