# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.additional_article_infos import AdditionalArticleInfos
from openapi_server.models.article_link_info import ArticleLinkInfo
from openapi_server.models.contact_infos import ContactInfos
from openapi_server.models.detail import Detail
from openapi_server.models.distance_info import DistanceInfo
from openapi_server.models.gps_info import GpsInfo
from openapi_server.models.gps_track import GpsTrack
from openapi_server.models.image_gallery import ImageGallery
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.metadata import Metadata
from openapi_server.models.odh_activity_poi_types_link import ODHActivityPoiTypesLink
from openapi_server.models.odh_tags import ODHTags
from openapi_server.models.operation_schedule import OperationSchedule
from openapi_server.models.related_content import RelatedContent
from openapi_server.models.tags import Tags
from openapi_server.models.video_items import VideoItems
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ArticlesLinked(BaseModel):
    """
    ArticlesLinked
    """ # noqa: E501
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    var_self: Optional[StrictStr] = Field(default=None, description="generated field", alias="Self")
    odh_active: Optional[StrictBool] = Field(default=None, description="generated field", alias="OdhActive")
    article_types: Optional[List[ODHActivityPoiTypesLink]] = Field(default=None, description="generated field", alias="ArticleTypes")
    article_type_list: Optional[List[StrictStr]] = Field(default=None, description="generated field", alias="ArticleTypeList")
    odh_tags: Optional[List[ODHTags]] = Field(default=None, description="generated field", alias="ODHTags")
    tags: Optional[List[Tags]] = Field(default=None, alias="Tags")
    tag_ids: Optional[List[StrictStr]] = Field(default=None, alias="TagIds")
    related_content: Optional[List[RelatedContent]] = Field(default=None, alias="RelatedContent")
    additional_properties: Optional[Dict[str, Any]] = Field(default=None, alias="AdditionalProperties")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    active: Optional[StrictBool] = Field(default=None, alias="Active")
    shortname: Optional[StrictStr] = Field(default=None, alias="Shortname")
    highlight: Optional[StrictBool] = Field(default=None, alias="Highlight")
    type: Optional[StrictStr] = Field(default=None, alias="Type")
    sub_type: Optional[StrictStr] = Field(default=None, alias="SubType")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    smg_active: Optional[StrictBool] = Field(default=None, description="Obsolete, use PublishedOn", alias="SmgActive")
    article_date: Optional[datetime] = Field(default=None, alias="ArticleDate")
    article_date_to: Optional[datetime] = Field(default=None, alias="ArticleDateTo")
    operation_schedule: Optional[List[OperationSchedule]] = Field(default=None, alias="OperationSchedule")
    gps_info: Optional[List[GpsInfo]] = Field(default=None, alias="GpsInfo")
    gps_track: Optional[List[GpsTrack]] = Field(default=None, alias="GpsTrack")
    image_gallery: Optional[List[ImageGallery]] = Field(default=None, alias="ImageGallery")
    detail: Optional[Dict[str, Detail]] = Field(default=None, alias="Detail")
    contact_infos: Optional[Dict[str, ContactInfos]] = Field(default=None, alias="ContactInfos")
    additional_article_infos: Optional[Dict[str, AdditionalArticleInfos]] = Field(default=None, alias="AdditionalArticleInfos")
    article_link_info: Optional[Dict[str, ArticleLinkInfo]] = Field(default=None, alias="ArticleLinkInfo")
    smg_tags: Optional[List[StrictStr]] = Field(default=None, alias="SmgTags")
    has_language: Optional[List[StrictStr]] = Field(default=None, alias="HasLanguage")
    expiration_date: Optional[datetime] = Field(default=None, alias="ExpirationDate")
    gps_points: Optional[Dict[str, GpsInfo]] = Field(default=None, description="generated field", alias="GpsPoints")
    published_on: Optional[List[StrictStr]] = Field(default=None, alias="PublishedOn")
    source: Optional[StrictStr] = Field(default=None, alias="Source")
    mapping: Optional[Dict[str, Dict[str, StrictStr]]] = Field(default=None, alias="Mapping")
    distance_info: Optional[DistanceInfo] = Field(default=None, alias="DistanceInfo")
    video_items: Optional[Dict[str, List[VideoItems]]] = Field(default=None, alias="VideoItems")
    __properties: ClassVar[List[str]] = ["_Meta", "Self", "OdhActive", "ArticleTypes", "ArticleTypeList", "ODHTags", "Tags", "TagIds", "RelatedContent", "AdditionalProperties", "LicenseInfo", "Id", "Active", "Shortname", "Highlight", "Type", "SubType", "FirstImport", "LastChange", "SmgActive", "ArticleDate", "ArticleDateTo", "OperationSchedule", "GpsInfo", "GpsTrack", "ImageGallery", "Detail", "ContactInfos", "AdditionalArticleInfos", "ArticleLinkInfo", "SmgTags", "HasLanguage", "ExpirationDate", "GpsPoints", "PublishedOn", "Source", "Mapping", "DistanceInfo", "VideoItems"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ArticlesLinked from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_self",
                "odh_active",
                "article_types",
                "article_type_list",
                "odh_tags",
                "gps_points",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in article_types (list)
        _items = []
        if self.article_types:
            for _item in self.article_types:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ArticleTypes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in odh_tags (list)
        _items = []
        if self.odh_tags:
            for _item in self.odh_tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ODHTags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_content (list)
        _items = []
        if self.related_content:
            for _item in self.related_content:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RelatedContent'] = _items
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in operation_schedule (list)
        _items = []
        if self.operation_schedule:
            for _item in self.operation_schedule:
                if _item:
                    _items.append(_item.to_dict())
            _dict['OperationSchedule'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in gps_info (list)
        _items = []
        if self.gps_info:
            for _item in self.gps_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['GpsInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in gps_track (list)
        _items = []
        if self.gps_track:
            for _item in self.gps_track:
                if _item:
                    _items.append(_item.to_dict())
            _dict['GpsTrack'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in image_gallery (list)
        _items = []
        if self.image_gallery:
            for _item in self.image_gallery:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ImageGallery'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in detail (dict)
        _field_dict = {}
        if self.detail:
            for _key in self.detail:
                if self.detail[_key]:
                    _field_dict[_key] = self.detail[_key].to_dict()
            _dict['Detail'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in contact_infos (dict)
        _field_dict = {}
        if self.contact_infos:
            for _key in self.contact_infos:
                if self.contact_infos[_key]:
                    _field_dict[_key] = self.contact_infos[_key].to_dict()
            _dict['ContactInfos'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in additional_article_infos (dict)
        _field_dict = {}
        if self.additional_article_infos:
            for _key in self.additional_article_infos:
                if self.additional_article_infos[_key]:
                    _field_dict[_key] = self.additional_article_infos[_key].to_dict()
            _dict['AdditionalArticleInfos'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in article_link_info (dict)
        _field_dict = {}
        if self.article_link_info:
            for _key in self.article_link_info:
                if self.article_link_info[_key]:
                    _field_dict[_key] = self.article_link_info[_key].to_dict()
            _dict['ArticleLinkInfo'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in gps_points (dict)
        _field_dict = {}
        if self.gps_points:
            for _key in self.gps_points:
                if self.gps_points[_key]:
                    _field_dict[_key] = self.gps_points[_key].to_dict()
            _dict['GpsPoints'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of distance_info
        if self.distance_info:
            _dict['DistanceInfo'] = self.distance_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in video_items (dict of array)
        _field_dict_of_array = {}
        if self.video_items:
            for _key in self.video_items:
                if self.video_items[_key] is not None:
                    _field_dict_of_array[_key] = [
                        _item.to_dict() for _item in self.video_items[_key]
                    ]
            _dict['VideoItems'] = _field_dict_of_array
        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if article_types (nullable) is None
        # and model_fields_set contains the field
        if self.article_types is None and "article_types" in self.model_fields_set:
            _dict['ArticleTypes'] = None

        # set to None if article_type_list (nullable) is None
        # and model_fields_set contains the field
        if self.article_type_list is None and "article_type_list" in self.model_fields_set:
            _dict['ArticleTypeList'] = None

        # set to None if odh_tags (nullable) is None
        # and model_fields_set contains the field
        if self.odh_tags is None and "odh_tags" in self.model_fields_set:
            _dict['ODHTags'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['Tags'] = None

        # set to None if tag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.tag_ids is None and "tag_ids" in self.model_fields_set:
            _dict['TagIds'] = None

        # set to None if related_content (nullable) is None
        # and model_fields_set contains the field
        if self.related_content is None and "related_content" in self.model_fields_set:
            _dict['RelatedContent'] = None

        # set to None if additional_properties (nullable) is None
        # and model_fields_set contains the field
        if self.additional_properties is None and "additional_properties" in self.model_fields_set:
            _dict['AdditionalProperties'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['Shortname'] = None

        # set to None if highlight (nullable) is None
        # and model_fields_set contains the field
        if self.highlight is None and "highlight" in self.model_fields_set:
            _dict['Highlight'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        # set to None if sub_type (nullable) is None
        # and model_fields_set contains the field
        if self.sub_type is None and "sub_type" in self.model_fields_set:
            _dict['SubType'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if article_date (nullable) is None
        # and model_fields_set contains the field
        if self.article_date is None and "article_date" in self.model_fields_set:
            _dict['ArticleDate'] = None

        # set to None if article_date_to (nullable) is None
        # and model_fields_set contains the field
        if self.article_date_to is None and "article_date_to" in self.model_fields_set:
            _dict['ArticleDateTo'] = None

        # set to None if operation_schedule (nullable) is None
        # and model_fields_set contains the field
        if self.operation_schedule is None and "operation_schedule" in self.model_fields_set:
            _dict['OperationSchedule'] = None

        # set to None if gps_info (nullable) is None
        # and model_fields_set contains the field
        if self.gps_info is None and "gps_info" in self.model_fields_set:
            _dict['GpsInfo'] = None

        # set to None if gps_track (nullable) is None
        # and model_fields_set contains the field
        if self.gps_track is None and "gps_track" in self.model_fields_set:
            _dict['GpsTrack'] = None

        # set to None if image_gallery (nullable) is None
        # and model_fields_set contains the field
        if self.image_gallery is None and "image_gallery" in self.model_fields_set:
            _dict['ImageGallery'] = None

        # set to None if detail (nullable) is None
        # and model_fields_set contains the field
        if self.detail is None and "detail" in self.model_fields_set:
            _dict['Detail'] = None

        # set to None if contact_infos (nullable) is None
        # and model_fields_set contains the field
        if self.contact_infos is None and "contact_infos" in self.model_fields_set:
            _dict['ContactInfos'] = None

        # set to None if additional_article_infos (nullable) is None
        # and model_fields_set contains the field
        if self.additional_article_infos is None and "additional_article_infos" in self.model_fields_set:
            _dict['AdditionalArticleInfos'] = None

        # set to None if article_link_info (nullable) is None
        # and model_fields_set contains the field
        if self.article_link_info is None and "article_link_info" in self.model_fields_set:
            _dict['ArticleLinkInfo'] = None

        # set to None if smg_tags (nullable) is None
        # and model_fields_set contains the field
        if self.smg_tags is None and "smg_tags" in self.model_fields_set:
            _dict['SmgTags'] = None

        # set to None if has_language (nullable) is None
        # and model_fields_set contains the field
        if self.has_language is None and "has_language" in self.model_fields_set:
            _dict['HasLanguage'] = None

        # set to None if expiration_date (nullable) is None
        # and model_fields_set contains the field
        if self.expiration_date is None and "expiration_date" in self.model_fields_set:
            _dict['ExpirationDate'] = None

        # set to None if gps_points (nullable) is None
        # and model_fields_set contains the field
        if self.gps_points is None and "gps_points" in self.model_fields_set:
            _dict['GpsPoints'] = None

        # set to None if published_on (nullable) is None
        # and model_fields_set contains the field
        if self.published_on is None and "published_on" in self.model_fields_set:
            _dict['PublishedOn'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['Source'] = None

        # set to None if mapping (nullable) is None
        # and model_fields_set contains the field
        if self.mapping is None and "mapping" in self.model_fields_set:
            _dict['Mapping'] = None

        # set to None if video_items (nullable) is None
        # and model_fields_set contains the field
        if self.video_items is None and "video_items" in self.model_fields_set:
            _dict['VideoItems'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ArticlesLinked from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "Self": obj.get("Self"),
            "OdhActive": obj.get("OdhActive"),
            "ArticleTypes": [ODHActivityPoiTypesLink.from_dict(_item) for _item in obj.get("ArticleTypes")] if obj.get("ArticleTypes") is not None else None,
            "ArticleTypeList": obj.get("ArticleTypeList"),
            "ODHTags": [ODHTags.from_dict(_item) for _item in obj.get("ODHTags")] if obj.get("ODHTags") is not None else None,
            "Tags": [Tags.from_dict(_item) for _item in obj.get("Tags")] if obj.get("Tags") is not None else None,
            "TagIds": obj.get("TagIds"),
            "RelatedContent": [RelatedContent.from_dict(_item) for _item in obj.get("RelatedContent")] if obj.get("RelatedContent") is not None else None,
            "AdditionalProperties": obj.get("AdditionalProperties"),
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "Id": obj.get("Id"),
            "Active": obj.get("Active"),
            "Shortname": obj.get("Shortname"),
            "Highlight": obj.get("Highlight"),
            "Type": obj.get("Type"),
            "SubType": obj.get("SubType"),
            "FirstImport": obj.get("FirstImport"),
            "LastChange": obj.get("LastChange"),
            "SmgActive": obj.get("SmgActive"),
            "ArticleDate": obj.get("ArticleDate"),
            "ArticleDateTo": obj.get("ArticleDateTo"),
            "OperationSchedule": [OperationSchedule.from_dict(_item) for _item in obj.get("OperationSchedule")] if obj.get("OperationSchedule") is not None else None,
            "GpsInfo": [GpsInfo.from_dict(_item) for _item in obj.get("GpsInfo")] if obj.get("GpsInfo") is not None else None,
            "GpsTrack": [GpsTrack.from_dict(_item) for _item in obj.get("GpsTrack")] if obj.get("GpsTrack") is not None else None,
            "ImageGallery": [ImageGallery.from_dict(_item) for _item in obj.get("ImageGallery")] if obj.get("ImageGallery") is not None else None,
            "Detail": dict(
                (_k, Detail.from_dict(_v))
                for _k, _v in obj.get("Detail").items()
            )
            if obj.get("Detail") is not None
            else None,
            "ContactInfos": dict(
                (_k, ContactInfos.from_dict(_v))
                for _k, _v in obj.get("ContactInfos").items()
            )
            if obj.get("ContactInfos") is not None
            else None,
            "AdditionalArticleInfos": dict(
                (_k, AdditionalArticleInfos.from_dict(_v))
                for _k, _v in obj.get("AdditionalArticleInfos").items()
            )
            if obj.get("AdditionalArticleInfos") is not None
            else None,
            "ArticleLinkInfo": dict(
                (_k, ArticleLinkInfo.from_dict(_v))
                for _k, _v in obj.get("ArticleLinkInfo").items()
            )
            if obj.get("ArticleLinkInfo") is not None
            else None,
            "SmgTags": obj.get("SmgTags"),
            "HasLanguage": obj.get("HasLanguage"),
            "ExpirationDate": obj.get("ExpirationDate"),
            "GpsPoints": dict(
                (_k, GpsInfo.from_dict(_v))
                for _k, _v in obj.get("GpsPoints").items()
            )
            if obj.get("GpsPoints") is not None
            else None,
            "PublishedOn": obj.get("PublishedOn"),
            "Source": obj.get("Source"),
            "Mapping": obj.get("Mapping"),
            "DistanceInfo": DistanceInfo.from_dict(obj.get("DistanceInfo")) if obj.get("DistanceInfo") is not None else None,
            "VideoItems": dict(
                (_k,
                        [VideoItems.from_dict(_item) for _item in _v]
                        if _v is not None
                        else None
                )
                for _k, _v in obj.get("VideoItems").items()
            )
        })
        return _obj


