# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.bezirks_forecast import BezirksForecast
from openapi_server.models.license_info import LicenseInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BezirksWeather(BaseModel):
    """
    BezirksWeather
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, alias="Id")
    language: Optional[StrictStr] = Field(default=None, alias="Language")
    district_name: Optional[StrictStr] = Field(default=None, alias="DistrictName")
    var_date: Optional[datetime] = Field(default=None, description="Obsolete, use Date", alias="date")
    var_date: Optional[datetime] = Field(default=None, alias="Date")
    tourism_verein_ids: Optional[List[StrictStr]] = Field(default=None, alias="TourismVereinIds")
    bezirks_forecast: Optional[List[BezirksForecast]] = Field(default=None, alias="BezirksForecast")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    __properties: ClassVar[List[str]] = ["Id", "Language", "DistrictName", "date", "Date", "TourismVereinIds", "BezirksForecast", "LicenseInfo"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BezirksWeather from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_date",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bezirks_forecast (list)
        _items = []
        if self.bezirks_forecast:
            for _item in self.bezirks_forecast:
                if _item:
                    _items.append(_item.to_dict())
            _dict['BezirksForecast'] = _items
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['Language'] = None

        # set to None if district_name (nullable) is None
        # and model_fields_set contains the field
        if self.district_name is None and "district_name" in self.model_fields_set:
            _dict['DistrictName'] = None

        # set to None if tourism_verein_ids (nullable) is None
        # and model_fields_set contains the field
        if self.tourism_verein_ids is None and "tourism_verein_ids" in self.model_fields_set:
            _dict['TourismVereinIds'] = None

        # set to None if bezirks_forecast (nullable) is None
        # and model_fields_set contains the field
        if self.bezirks_forecast is None and "bezirks_forecast" in self.model_fields_set:
            _dict['BezirksForecast'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BezirksWeather from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id"),
            "Language": obj.get("Language"),
            "DistrictName": obj.get("DistrictName"),
            "date": obj.get("date"),
            "Date": obj.get("Date"),
            "TourismVereinIds": obj.get("TourismVereinIds"),
            "BezirksForecast": [BezirksForecast.from_dict(_item) for _item in obj.get("BezirksForecast")] if obj.get("BezirksForecast") is not None else None,
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None
        })
        return _obj


