# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ContactInfos(BaseModel):
    """
    ContactInfos
    """ # noqa: E501
    address: Optional[StrictStr] = Field(default=None, description="Street Address", alias="Address")
    region: Optional[StrictStr] = Field(default=None, description="Region (Province / State / Departement / Canton etc...", alias="Region")
    region_code: Optional[StrictStr] = Field(default=None, description="Regioncode", alias="RegionCode")
    area: Optional[StrictStr] = Field(default=None, description="Area (Additional Area Name)", alias="Area")
    city: Optional[StrictStr] = Field(default=None, alias="City")
    zip_code: Optional[StrictStr] = Field(default=None, alias="ZipCode")
    country_code: Optional[StrictStr] = Field(default=None, alias="CountryCode")
    country_name: Optional[StrictStr] = Field(default=None, alias="CountryName")
    surname: Optional[StrictStr] = Field(default=None, alias="Surname")
    givenname: Optional[StrictStr] = Field(default=None, alias="Givenname")
    name_prefix: Optional[StrictStr] = Field(default=None, alias="NamePrefix")
    email: Optional[StrictStr] = Field(default=None, alias="Email")
    phonenumber: Optional[StrictStr] = Field(default=None, alias="Phonenumber")
    faxnumber: Optional[StrictStr] = Field(default=None, alias="Faxnumber")
    url: Optional[StrictStr] = Field(default=None, alias="Url")
    language: Optional[StrictStr] = Field(default=None, alias="Language")
    company_name: Optional[StrictStr] = Field(default=None, alias="CompanyName")
    vat: Optional[StrictStr] = Field(default=None, alias="Vat")
    tax: Optional[StrictStr] = Field(default=None, alias="Tax")
    logo_url: Optional[StrictStr] = Field(default=None, alias="LogoUrl")
    __properties: ClassVar[List[str]] = ["Address", "Region", "RegionCode", "Area", "City", "ZipCode", "CountryCode", "CountryName", "Surname", "Givenname", "NamePrefix", "Email", "Phonenumber", "Faxnumber", "Url", "Language", "CompanyName", "Vat", "Tax", "LogoUrl"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ContactInfos from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['Address'] = None

        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['Region'] = None

        # set to None if region_code (nullable) is None
        # and model_fields_set contains the field
        if self.region_code is None and "region_code" in self.model_fields_set:
            _dict['RegionCode'] = None

        # set to None if area (nullable) is None
        # and model_fields_set contains the field
        if self.area is None and "area" in self.model_fields_set:
            _dict['Area'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['City'] = None

        # set to None if zip_code (nullable) is None
        # and model_fields_set contains the field
        if self.zip_code is None and "zip_code" in self.model_fields_set:
            _dict['ZipCode'] = None

        # set to None if country_code (nullable) is None
        # and model_fields_set contains the field
        if self.country_code is None and "country_code" in self.model_fields_set:
            _dict['CountryCode'] = None

        # set to None if country_name (nullable) is None
        # and model_fields_set contains the field
        if self.country_name is None and "country_name" in self.model_fields_set:
            _dict['CountryName'] = None

        # set to None if surname (nullable) is None
        # and model_fields_set contains the field
        if self.surname is None and "surname" in self.model_fields_set:
            _dict['Surname'] = None

        # set to None if givenname (nullable) is None
        # and model_fields_set contains the field
        if self.givenname is None and "givenname" in self.model_fields_set:
            _dict['Givenname'] = None

        # set to None if name_prefix (nullable) is None
        # and model_fields_set contains the field
        if self.name_prefix is None and "name_prefix" in self.model_fields_set:
            _dict['NamePrefix'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['Email'] = None

        # set to None if phonenumber (nullable) is None
        # and model_fields_set contains the field
        if self.phonenumber is None and "phonenumber" in self.model_fields_set:
            _dict['Phonenumber'] = None

        # set to None if faxnumber (nullable) is None
        # and model_fields_set contains the field
        if self.faxnumber is None and "faxnumber" in self.model_fields_set:
            _dict['Faxnumber'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['Url'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['Language'] = None

        # set to None if company_name (nullable) is None
        # and model_fields_set contains the field
        if self.company_name is None and "company_name" in self.model_fields_set:
            _dict['CompanyName'] = None

        # set to None if vat (nullable) is None
        # and model_fields_set contains the field
        if self.vat is None and "vat" in self.model_fields_set:
            _dict['Vat'] = None

        # set to None if tax (nullable) is None
        # and model_fields_set contains the field
        if self.tax is None and "tax" in self.model_fields_set:
            _dict['Tax'] = None

        # set to None if logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.logo_url is None and "logo_url" in self.model_fields_set:
            _dict['LogoUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ContactInfos from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Address": obj.get("Address"),
            "Region": obj.get("Region"),
            "RegionCode": obj.get("RegionCode"),
            "Area": obj.get("Area"),
            "City": obj.get("City"),
            "ZipCode": obj.get("ZipCode"),
            "CountryCode": obj.get("CountryCode"),
            "CountryName": obj.get("CountryName"),
            "Surname": obj.get("Surname"),
            "Givenname": obj.get("Givenname"),
            "NamePrefix": obj.get("NamePrefix"),
            "Email": obj.get("Email"),
            "Phonenumber": obj.get("Phonenumber"),
            "Faxnumber": obj.get("Faxnumber"),
            "Url": obj.get("Url"),
            "Language": obj.get("Language"),
            "CompanyName": obj.get("CompanyName"),
            "Vat": obj.get("Vat"),
            "Tax": obj.get("Tax"),
            "LogoUrl": obj.get("LogoUrl")
        })
        return _obj


