# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Coordinate(BaseModel):
    """
    Coordinate
    """ # noqa: E501
    x: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="X")
    y: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Y")
    z: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Z")
    m: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="M")
    coordinate_value: Optional[Coordinate] = Field(default=None, alias="CoordinateValue")
    is_valid: Optional[StrictBool] = Field(default=None, alias="IsValid")
    __properties: ClassVar[List[str]] = ["X", "Y", "Z", "M", "CoordinateValue", "IsValid"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Coordinate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "is_valid",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coordinate_value
        if self.coordinate_value:
            _dict['CoordinateValue'] = self.coordinate_value.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Coordinate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "X": obj.get("X"),
            "Y": obj.get("Y"),
            "Z": obj.get("Z"),
            "M": obj.get("M"),
            "CoordinateValue": Coordinate.from_dict(obj.get("CoordinateValue")) if obj.get("CoordinateValue") is not None else None,
            "IsValid": obj.get("IsValid")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
Coordinate.model_rebuild(raise_errors=False)

