# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.details_themed import DetailsThemed
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DetailThemed(BaseModel):
    """
    DetailThemed
    """ # noqa: E501
    details_themed: Optional[Dict[str, DetailsThemed]] = Field(default=None, alias="DetailsThemed")
    language: Optional[StrictStr] = Field(default=None, alias="Language")
    __properties: ClassVar[List[str]] = ["DetailsThemed", "Language"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DetailThemed from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in details_themed (dict)
        _field_dict = {}
        if self.details_themed:
            for _key in self.details_themed:
                if self.details_themed[_key]:
                    _field_dict[_key] = self.details_themed[_key].to_dict()
            _dict['DetailsThemed'] = _field_dict
        # set to None if details_themed (nullable) is None
        # and model_fields_set contains the field
        if self.details_themed is None and "details_themed" in self.model_fields_set:
            _dict['DetailsThemed'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['Language'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DetailThemed from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "DetailsThemed": dict(
                (_k, DetailsThemed.from_dict(_v))
                for _k, _v in obj.get("DetailsThemed").items()
            )
            if obj.get("DetailsThemed") is not None
            else None,
            "Language": obj.get("Language")
        })
        return _obj


