# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Detail(BaseModel):
    """
    Detail
    """ # noqa: E501
    header: Optional[StrictStr] = Field(default=None, alias="Header")
    sub_header: Optional[StrictStr] = Field(default=None, alias="SubHeader")
    intro_text: Optional[StrictStr] = Field(default=None, alias="IntroText")
    base_text: Optional[StrictStr] = Field(default=None, alias="BaseText")
    title: Optional[StrictStr] = Field(default=None, alias="Title")
    additional_text: Optional[StrictStr] = Field(default=None, alias="AdditionalText")
    meta_title: Optional[StrictStr] = Field(default=None, alias="MetaTitle")
    meta_desc: Optional[StrictStr] = Field(default=None, alias="MetaDesc")
    get_there_text: Optional[StrictStr] = Field(default=None, alias="GetThereText")
    language: Optional[StrictStr] = Field(default=None, alias="Language")
    keywords: Optional[List[StrictStr]] = Field(default=None, alias="Keywords")
    parking_info: Optional[StrictStr] = Field(default=None, alias="ParkingInfo")
    public_transportation_info: Optional[StrictStr] = Field(default=None, alias="PublicTransportationInfo")
    author_tip: Optional[StrictStr] = Field(default=None, alias="AuthorTip")
    safety_info: Optional[StrictStr] = Field(default=None, alias="SafetyInfo")
    equipment_info: Optional[StrictStr] = Field(default=None, alias="EquipmentInfo")
    __properties: ClassVar[List[str]] = ["Header", "SubHeader", "IntroText", "BaseText", "Title", "AdditionalText", "MetaTitle", "MetaDesc", "GetThereText", "Language", "Keywords", "ParkingInfo", "PublicTransportationInfo", "AuthorTip", "SafetyInfo", "EquipmentInfo"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Detail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if header (nullable) is None
        # and model_fields_set contains the field
        if self.header is None and "header" in self.model_fields_set:
            _dict['Header'] = None

        # set to None if sub_header (nullable) is None
        # and model_fields_set contains the field
        if self.sub_header is None and "sub_header" in self.model_fields_set:
            _dict['SubHeader'] = None

        # set to None if intro_text (nullable) is None
        # and model_fields_set contains the field
        if self.intro_text is None and "intro_text" in self.model_fields_set:
            _dict['IntroText'] = None

        # set to None if base_text (nullable) is None
        # and model_fields_set contains the field
        if self.base_text is None and "base_text" in self.model_fields_set:
            _dict['BaseText'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['Title'] = None

        # set to None if additional_text (nullable) is None
        # and model_fields_set contains the field
        if self.additional_text is None and "additional_text" in self.model_fields_set:
            _dict['AdditionalText'] = None

        # set to None if meta_title (nullable) is None
        # and model_fields_set contains the field
        if self.meta_title is None and "meta_title" in self.model_fields_set:
            _dict['MetaTitle'] = None

        # set to None if meta_desc (nullable) is None
        # and model_fields_set contains the field
        if self.meta_desc is None and "meta_desc" in self.model_fields_set:
            _dict['MetaDesc'] = None

        # set to None if get_there_text (nullable) is None
        # and model_fields_set contains the field
        if self.get_there_text is None and "get_there_text" in self.model_fields_set:
            _dict['GetThereText'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['Language'] = None

        # set to None if keywords (nullable) is None
        # and model_fields_set contains the field
        if self.keywords is None and "keywords" in self.model_fields_set:
            _dict['Keywords'] = None

        # set to None if parking_info (nullable) is None
        # and model_fields_set contains the field
        if self.parking_info is None and "parking_info" in self.model_fields_set:
            _dict['ParkingInfo'] = None

        # set to None if public_transportation_info (nullable) is None
        # and model_fields_set contains the field
        if self.public_transportation_info is None and "public_transportation_info" in self.model_fields_set:
            _dict['PublicTransportationInfo'] = None

        # set to None if author_tip (nullable) is None
        # and model_fields_set contains the field
        if self.author_tip is None and "author_tip" in self.model_fields_set:
            _dict['AuthorTip'] = None

        # set to None if safety_info (nullable) is None
        # and model_fields_set contains the field
        if self.safety_info is None and "safety_info" in self.model_fields_set:
            _dict['SafetyInfo'] = None

        # set to None if equipment_info (nullable) is None
        # and model_fields_set contains the field
        if self.equipment_info is None and "equipment_info" in self.model_fields_set:
            _dict['EquipmentInfo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Detail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Header": obj.get("Header"),
            "SubHeader": obj.get("SubHeader"),
            "IntroText": obj.get("IntroText"),
            "BaseText": obj.get("BaseText"),
            "Title": obj.get("Title"),
            "AdditionalText": obj.get("AdditionalText"),
            "MetaTitle": obj.get("MetaTitle"),
            "MetaDesc": obj.get("MetaDesc"),
            "GetThereText": obj.get("GetThereText"),
            "Language": obj.get("Language"),
            "Keywords": obj.get("Keywords"),
            "ParkingInfo": obj.get("ParkingInfo"),
            "PublicTransportationInfo": obj.get("PublicTransportationInfo"),
            "AuthorTip": obj.get("AuthorTip"),
            "SafetyInfo": obj.get("SafetyInfo"),
            "EquipmentInfo": obj.get("EquipmentInfo")
        })
        return _obj


