# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.event_date_calculated_day_variant import EventDateCalculatedDayVariant
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EventDateCalculatedDay(BaseModel):
    """
    EventDateCalculatedDay
    """ # noqa: E501
    calculated_day_id: Optional[StrictStr] = Field(default=None, alias="CalculatedDayId")
    c_day_rid: Optional[StrictStr] = Field(default=None, description="Deprecated use CalculatedDayId", alias="CDayRID")
    day: Optional[datetime] = Field(default=None, alias="Day")
    begin: Optional[StrictStr] = Field(default=None, alias="Begin")
    availability_low: Optional[StrictBool] = Field(default=None, alias="AvailabilityLow")
    availability_calculated_value: Optional[StrictInt] = Field(default=None, alias="AvailabilityCalculatedValue")
    sold_out: Optional[StrictBool] = Field(default=None, alias="SoldOut")
    event_date_calculated_day_variant: Optional[List[EventDateCalculatedDayVariant]] = Field(default=None, alias="EventDateCalculatedDayVariant")
    __properties: ClassVar[List[str]] = ["CalculatedDayId", "CDayRID", "Day", "Begin", "AvailabilityLow", "AvailabilityCalculatedValue", "SoldOut", "EventDateCalculatedDayVariant"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventDateCalculatedDay from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in event_date_calculated_day_variant (list)
        _items = []
        if self.event_date_calculated_day_variant:
            for _item in self.event_date_calculated_day_variant:
                if _item:
                    _items.append(_item.to_dict())
            _dict['EventDateCalculatedDayVariant'] = _items
        # set to None if calculated_day_id (nullable) is None
        # and model_fields_set contains the field
        if self.calculated_day_id is None and "calculated_day_id" in self.model_fields_set:
            _dict['CalculatedDayId'] = None

        # set to None if c_day_rid (nullable) is None
        # and model_fields_set contains the field
        if self.c_day_rid is None and "c_day_rid" in self.model_fields_set:
            _dict['CDayRID'] = None

        # set to None if day (nullable) is None
        # and model_fields_set contains the field
        if self.day is None and "day" in self.model_fields_set:
            _dict['Day'] = None

        # set to None if begin (nullable) is None
        # and model_fields_set contains the field
        if self.begin is None and "begin" in self.model_fields_set:
            _dict['Begin'] = None

        # set to None if availability_low (nullable) is None
        # and model_fields_set contains the field
        if self.availability_low is None and "availability_low" in self.model_fields_set:
            _dict['AvailabilityLow'] = None

        # set to None if availability_calculated_value (nullable) is None
        # and model_fields_set contains the field
        if self.availability_calculated_value is None and "availability_calculated_value" in self.model_fields_set:
            _dict['AvailabilityCalculatedValue'] = None

        # set to None if sold_out (nullable) is None
        # and model_fields_set contains the field
        if self.sold_out is None and "sold_out" in self.model_fields_set:
            _dict['SoldOut'] = None

        # set to None if event_date_calculated_day_variant (nullable) is None
        # and model_fields_set contains the field
        if self.event_date_calculated_day_variant is None and "event_date_calculated_day_variant" in self.model_fields_set:
            _dict['EventDateCalculatedDayVariant'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EventDateCalculatedDay from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CalculatedDayId": obj.get("CalculatedDayId"),
            "CDayRID": obj.get("CDayRID"),
            "Day": obj.get("Day"),
            "Begin": obj.get("Begin"),
            "AvailabilityLow": obj.get("AvailabilityLow"),
            "AvailabilityCalculatedValue": obj.get("AvailabilityCalculatedValue"),
            "SoldOut": obj.get("SoldOut"),
            "EventDateCalculatedDayVariant": [EventDateCalculatedDayVariant.from_dict(_item) for _item in obj.get("EventDateCalculatedDayVariant")] if obj.get("EventDateCalculatedDayVariant") is not None else None
        })
        return _obj


