# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EventVariant(BaseModel):
    """
    EventVariant
    """ # noqa: E501
    order: Optional[StrictInt] = Field(default=None, alias="Order")
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Price")
    variant_id: Optional[StrictStr] = Field(default=None, alias="VariantId")
    variant_category_id: Optional[StrictStr] = Field(default=None, alias="VariantCategoryId")
    name: Optional[Dict[str, StrictStr]] = Field(default=None, alias="Name")
    is_ignored_in_availability: Optional[StrictBool] = Field(default=None, alias="IsIgnoredInAvailability")
    is_standard: Optional[StrictBool] = Field(default=None, alias="IsStandard")
    combined_sales_ids: Optional[List[StrictStr]] = Field(default=None, alias="CombinedSalesIds")
    tax_rate_id: Optional[StrictStr] = Field(default=None, alias="TaxRateId")
    __properties: ClassVar[List[str]] = ["Order", "Price", "VariantId", "VariantCategoryId", "Name", "IsIgnoredInAvailability", "IsStandard", "CombinedSalesIds", "TaxRateId"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventVariant from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if order (nullable) is None
        # and model_fields_set contains the field
        if self.order is None and "order" in self.model_fields_set:
            _dict['Order'] = None

        # set to None if price (nullable) is None
        # and model_fields_set contains the field
        if self.price is None and "price" in self.model_fields_set:
            _dict['Price'] = None

        # set to None if variant_id (nullable) is None
        # and model_fields_set contains the field
        if self.variant_id is None and "variant_id" in self.model_fields_set:
            _dict['VariantId'] = None

        # set to None if variant_category_id (nullable) is None
        # and model_fields_set contains the field
        if self.variant_category_id is None and "variant_category_id" in self.model_fields_set:
            _dict['VariantCategoryId'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['Name'] = None

        # set to None if is_ignored_in_availability (nullable) is None
        # and model_fields_set contains the field
        if self.is_ignored_in_availability is None and "is_ignored_in_availability" in self.model_fields_set:
            _dict['IsIgnoredInAvailability'] = None

        # set to None if is_standard (nullable) is None
        # and model_fields_set contains the field
        if self.is_standard is None and "is_standard" in self.model_fields_set:
            _dict['IsStandard'] = None

        # set to None if combined_sales_ids (nullable) is None
        # and model_fields_set contains the field
        if self.combined_sales_ids is None and "combined_sales_ids" in self.model_fields_set:
            _dict['CombinedSalesIds'] = None

        # set to None if tax_rate_id (nullable) is None
        # and model_fields_set contains the field
        if self.tax_rate_id is None and "tax_rate_id" in self.model_fields_set:
            _dict['TaxRateId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EventVariant from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Order": obj.get("Order"),
            "Price": obj.get("Price"),
            "VariantId": obj.get("VariantId"),
            "VariantCategoryId": obj.get("VariantCategoryId"),
            "Name": obj.get("Name"),
            "IsIgnoredInAvailability": obj.get("IsIgnoredInAvailability"),
            "IsStandard": obj.get("IsStandard"),
            "CombinedSalesIds": obj.get("CombinedSalesIds"),
            "TaxRateId": obj.get("TaxRateId")
        })
        return _obj


