# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.event_booking_detail import EventBookingDetail
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EventBooking(BaseModel):
    """
    EventBooking
    """ # noqa: E501
    bookable_from: Optional[datetime] = Field(default=None, alias="BookableFrom")
    bookable_to: Optional[datetime] = Field(default=None, alias="BookableTo")
    booking_url: Optional[Dict[str, EventBookingDetail]] = Field(default=None, alias="BookingUrl")
    booking_active: Optional[StrictBool] = Field(default=None, alias="BookingActive")
    __properties: ClassVar[List[str]] = ["BookableFrom", "BookableTo", "BookingUrl", "BookingActive"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventBooking from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in booking_url (dict)
        _field_dict = {}
        if self.booking_url:
            for _key in self.booking_url:
                if self.booking_url[_key]:
                    _field_dict[_key] = self.booking_url[_key].to_dict()
            _dict['BookingUrl'] = _field_dict
        # set to None if bookable_from (nullable) is None
        # and model_fields_set contains the field
        if self.bookable_from is None and "bookable_from" in self.model_fields_set:
            _dict['BookableFrom'] = None

        # set to None if bookable_to (nullable) is None
        # and model_fields_set contains the field
        if self.bookable_to is None and "bookable_to" in self.model_fields_set:
            _dict['BookableTo'] = None

        # set to None if booking_url (nullable) is None
        # and model_fields_set contains the field
        if self.booking_url is None and "booking_url" in self.model_fields_set:
            _dict['BookingUrl'] = None

        # set to None if booking_active (nullable) is None
        # and model_fields_set contains the field
        if self.booking_active is None and "booking_active" in self.model_fields_set:
            _dict['BookingActive'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EventBooking from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "BookableFrom": obj.get("BookableFrom"),
            "BookableTo": obj.get("BookableTo"),
            "BookingUrl": dict(
                (_k, EventBookingDetail.from_dict(_v))
                for _k, _v in obj.get("BookingUrl").items()
            )
            if obj.get("BookingUrl") is not None
            else None,
            "BookingActive": obj.get("BookingActive")
        })
        return _obj


