# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EventPrice(BaseModel):
    """
    EventPrice
    """ # noqa: E501
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Price")
    type: Optional[StrictStr] = Field(default=None, alias="Type")
    pstd: Optional[StrictStr] = Field(default=None, alias="Pstd")
    short_desc: Optional[StrictStr] = Field(default=None, alias="ShortDesc")
    long_desc: Optional[StrictStr] = Field(default=None, alias="LongDesc")
    description: Optional[StrictStr] = Field(default=None, alias="Description")
    language: Optional[StrictStr] = Field(default=None, alias="Language")
    price_rid: Optional[StrictStr] = Field(default=None, alias="PriceRID")
    var_rid: Optional[StrictStr] = Field(default=None, alias="VarRID")
    __properties: ClassVar[List[str]] = ["Price", "Type", "Pstd", "ShortDesc", "LongDesc", "Description", "Language", "PriceRID", "VarRID"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventPrice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        # set to None if pstd (nullable) is None
        # and model_fields_set contains the field
        if self.pstd is None and "pstd" in self.model_fields_set:
            _dict['Pstd'] = None

        # set to None if short_desc (nullable) is None
        # and model_fields_set contains the field
        if self.short_desc is None and "short_desc" in self.model_fields_set:
            _dict['ShortDesc'] = None

        # set to None if long_desc (nullable) is None
        # and model_fields_set contains the field
        if self.long_desc is None and "long_desc" in self.model_fields_set:
            _dict['LongDesc'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['Description'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['Language'] = None

        # set to None if price_rid (nullable) is None
        # and model_fields_set contains the field
        if self.price_rid is None and "price_rid" in self.model_fields_set:
            _dict['PriceRID'] = None

        # set to None if var_rid (nullable) is None
        # and model_fields_set contains the field
        if self.var_rid is None and "var_rid" in self.model_fields_set:
            _dict['VarRID'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EventPrice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Price": obj.get("Price"),
            "Type": obj.get("Type"),
            "Pstd": obj.get("Pstd"),
            "ShortDesc": obj.get("ShortDesc"),
            "LongDesc": obj.get("LongDesc"),
            "Description": obj.get("Description"),
            "Language": obj.get("Language"),
            "PriceRID": obj.get("PriceRID"),
            "VarRID": obj.get("VarRID")
        })
        return _obj


