# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EventDateAdditionalInfo(BaseModel):
    """
    EventDateAdditionalInfo
    """ # noqa: E501
    description: Optional[StrictStr] = Field(default=None, alias="Description")
    guide: Optional[StrictStr] = Field(default=None, alias="Guide")
    registration_within: Optional[StrictStr] = Field(default=None, alias="RegistrationWithin")
    language: Optional[StrictStr] = Field(default=None, alias="Language")
    cancellation_description: Optional[StrictStr] = Field(default=None, alias="CancellationDescription")
    __properties: ClassVar[List[str]] = ["Description", "Guide", "RegistrationWithin", "Language", "CancellationDescription"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventDateAdditionalInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['Description'] = None

        # set to None if guide (nullable) is None
        # and model_fields_set contains the field
        if self.guide is None and "guide" in self.model_fields_set:
            _dict['Guide'] = None

        # set to None if registration_within (nullable) is None
        # and model_fields_set contains the field
        if self.registration_within is None and "registration_within" in self.model_fields_set:
            _dict['RegistrationWithin'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['Language'] = None

        # set to None if cancellation_description (nullable) is None
        # and model_fields_set contains the field
        if self.cancellation_description is None and "cancellation_description" in self.model_fields_set:
            _dict['CancellationDescription'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EventDateAdditionalInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Description": obj.get("Description"),
            "Guide": obj.get("Guide"),
            "RegistrationWithin": obj.get("RegistrationWithin"),
            "Language": obj.get("Language"),
            "CancellationDescription": obj.get("CancellationDescription")
        })
        return _obj


