# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Forecast24Hours(BaseModel):
    """
    Forecast24Hours
    """ # noqa: E501
    var_date: Optional[datetime] = Field(default=None, alias="Date")
    min_temp: Optional[StrictInt] = Field(default=None, description="Minimum Temperature in °C", alias="MinTemp")
    max_temp: Optional[StrictInt] = Field(default=None, description="Maximum Temperature in °C", alias="MaxTemp")
    sunshine_duration: Optional[StrictInt] = Field(default=None, description="Sunshine Duration in Hours h", alias="SunshineDuration")
    precipitation_probability: Optional[StrictInt] = Field(default=None, description="Maximimum Precipitation Probability in Percent %", alias="PrecipitationProbability")
    precipitation: Optional[StrictInt] = Field(default=None, description="24 hour Precipitation sum in mm", alias="Precipitation")
    weather_code: Optional[StrictStr] = Field(default=None, description="Weather Code", alias="WeatherCode")
    weather_desc: Optional[StrictStr] = Field(default=None, description="Weather Desciption", alias="WeatherDesc")
    weather_description: Optional[Dict[str, StrictStr]] = Field(default=None, description="Weather Desciption multi language", alias="WeatherDescription")
    weather_img_url: Optional[StrictStr] = Field(default=None, description="Weather ImageUrl", alias="WeatherImgUrl")
    __properties: ClassVar[List[str]] = ["Date", "MinTemp", "MaxTemp", "SunshineDuration", "PrecipitationProbability", "Precipitation", "WeatherCode", "WeatherDesc", "WeatherDescription", "WeatherImgUrl"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Forecast24Hours from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if min_temp (nullable) is None
        # and model_fields_set contains the field
        if self.min_temp is None and "min_temp" in self.model_fields_set:
            _dict['MinTemp'] = None

        # set to None if max_temp (nullable) is None
        # and model_fields_set contains the field
        if self.max_temp is None and "max_temp" in self.model_fields_set:
            _dict['MaxTemp'] = None

        # set to None if sunshine_duration (nullable) is None
        # and model_fields_set contains the field
        if self.sunshine_duration is None and "sunshine_duration" in self.model_fields_set:
            _dict['SunshineDuration'] = None

        # set to None if precipitation_probability (nullable) is None
        # and model_fields_set contains the field
        if self.precipitation_probability is None and "precipitation_probability" in self.model_fields_set:
            _dict['PrecipitationProbability'] = None

        # set to None if precipitation (nullable) is None
        # and model_fields_set contains the field
        if self.precipitation is None and "precipitation" in self.model_fields_set:
            _dict['Precipitation'] = None

        # set to None if weather_code (nullable) is None
        # and model_fields_set contains the field
        if self.weather_code is None and "weather_code" in self.model_fields_set:
            _dict['WeatherCode'] = None

        # set to None if weather_desc (nullable) is None
        # and model_fields_set contains the field
        if self.weather_desc is None and "weather_desc" in self.model_fields_set:
            _dict['WeatherDesc'] = None

        # set to None if weather_description (nullable) is None
        # and model_fields_set contains the field
        if self.weather_description is None and "weather_description" in self.model_fields_set:
            _dict['WeatherDescription'] = None

        # set to None if weather_img_url (nullable) is None
        # and model_fields_set contains the field
        if self.weather_img_url is None and "weather_img_url" in self.model_fields_set:
            _dict['WeatherImgUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Forecast24Hours from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Date": obj.get("Date"),
            "MinTemp": obj.get("MinTemp"),
            "MaxTemp": obj.get("MaxTemp"),
            "SunshineDuration": obj.get("SunshineDuration"),
            "PrecipitationProbability": obj.get("PrecipitationProbability"),
            "Precipitation": obj.get("Precipitation"),
            "WeatherCode": obj.get("WeatherCode"),
            "WeatherDesc": obj.get("WeatherDesc"),
            "WeatherDescription": obj.get("WeatherDescription"),
            "WeatherImgUrl": obj.get("WeatherImgUrl")
        })
        return _obj


