# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Forecast(BaseModel):
    """
    Forecast
    """ # noqa: E501
    var_date: Optional[datetime] = Field(default=None, description="Obsolete, use Date", alias="date")
    weatherdesc: Optional[StrictStr] = Field(default=None, description="Obsolete, use WeatherDesc", alias="Weatherdesc")
    weathercode: Optional[StrictStr] = Field(default=None, description="Obsolete, use WeatherCode", alias="Weathercode")
    weather_imgurl: Optional[StrictStr] = Field(default=None, description="Obsolete, use WeatherImgUrl", alias="WeatherImgurl")
    var_date: Optional[datetime] = Field(default=None, alias="Date")
    temp_maxmax: Optional[StrictInt] = Field(default=None, alias="TempMaxmax")
    temp_maxmin: Optional[StrictInt] = Field(default=None, alias="TempMaxmin")
    temp_minmax: Optional[StrictInt] = Field(default=None, alias="TempMinmax")
    temp_minmin: Optional[StrictInt] = Field(default=None, alias="TempMinmin")
    weather_code: Optional[StrictStr] = Field(default=None, alias="WeatherCode")
    weather_desc: Optional[StrictStr] = Field(default=None, alias="WeatherDesc")
    weather_img_url: Optional[StrictStr] = Field(default=None, alias="WeatherImgUrl")
    reliability: Optional[StrictStr] = Field(default=None, alias="Reliability")
    __properties: ClassVar[List[str]] = ["date", "Weatherdesc", "Weathercode", "WeatherImgurl", "Date", "TempMaxmax", "TempMaxmin", "TempMinmax", "TempMinmin", "WeatherCode", "WeatherDesc", "WeatherImgUrl", "Reliability"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Forecast from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_date",
                "weatherdesc",
                "weathercode",
                "weather_imgurl",
            },
            exclude_none=True,
        )
        # set to None if weatherdesc (nullable) is None
        # and model_fields_set contains the field
        if self.weatherdesc is None and "weatherdesc" in self.model_fields_set:
            _dict['Weatherdesc'] = None

        # set to None if weathercode (nullable) is None
        # and model_fields_set contains the field
        if self.weathercode is None and "weathercode" in self.model_fields_set:
            _dict['Weathercode'] = None

        # set to None if weather_imgurl (nullable) is None
        # and model_fields_set contains the field
        if self.weather_imgurl is None and "weather_imgurl" in self.model_fields_set:
            _dict['WeatherImgurl'] = None

        # set to None if weather_code (nullable) is None
        # and model_fields_set contains the field
        if self.weather_code is None and "weather_code" in self.model_fields_set:
            _dict['WeatherCode'] = None

        # set to None if weather_desc (nullable) is None
        # and model_fields_set contains the field
        if self.weather_desc is None and "weather_desc" in self.model_fields_set:
            _dict['WeatherDesc'] = None

        # set to None if weather_img_url (nullable) is None
        # and model_fields_set contains the field
        if self.weather_img_url is None and "weather_img_url" in self.model_fields_set:
            _dict['WeatherImgUrl'] = None

        # set to None if reliability (nullable) is None
        # and model_fields_set contains the field
        if self.reliability is None and "reliability" in self.model_fields_set:
            _dict['Reliability'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Forecast from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "Weatherdesc": obj.get("Weatherdesc"),
            "Weathercode": obj.get("Weathercode"),
            "WeatherImgurl": obj.get("WeatherImgurl"),
            "Date": obj.get("Date"),
            "TempMaxmax": obj.get("TempMaxmax"),
            "TempMaxmin": obj.get("TempMaxmin"),
            "TempMinmax": obj.get("TempMinmax"),
            "TempMinmin": obj.get("TempMinmin"),
            "WeatherCode": obj.get("WeatherCode"),
            "WeatherDesc": obj.get("WeatherDesc"),
            "WeatherImgUrl": obj.get("WeatherImgUrl"),
            "Reliability": obj.get("Reliability")
        })
        return _obj


