# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.coordinate import Coordinate
from openapi_server.models.dimension import Dimension
from openapi_server.models.envelope import Envelope
from openapi_server.models.geometry_factory import GeometryFactory
from openapi_server.models.ogc_geometry_type import OgcGeometryType
from openapi_server.models.precision_model import PrecisionModel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Geometry(BaseModel):
    """
    Geometry
    """ # noqa: E501
    factory: Optional[GeometryFactory] = Field(default=None, alias="Factory")
    user_data: Optional[Any] = Field(default=None, alias="UserData")
    srid: Optional[StrictInt] = Field(default=None, alias="SRID")
    geometry_type: Optional[StrictStr] = Field(default=None, alias="GeometryType")
    ogc_geometry_type: Optional[OgcGeometryType] = Field(default=None, alias="OgcGeometryType")
    precision_model: Optional[PrecisionModel] = Field(default=None, alias="PrecisionModel")
    coordinate: Optional[Coordinate] = Field(default=None, alias="Coordinate")
    coordinates: Optional[List[Coordinate]] = Field(default=None, alias="Coordinates")
    num_points: Optional[StrictInt] = Field(default=None, alias="NumPoints")
    num_geometries: Optional[StrictInt] = Field(default=None, alias="NumGeometries")
    is_simple: Optional[StrictBool] = Field(default=None, alias="IsSimple")
    is_valid: Optional[StrictBool] = Field(default=None, alias="IsValid")
    is_empty: Optional[StrictBool] = Field(default=None, alias="IsEmpty")
    area: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Area")
    length: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Length")
    centroid: Optional[Point] = Field(default=None, alias="Centroid")
    interior_point: Optional[Point] = Field(default=None, alias="InteriorPoint")
    point_on_surface: Optional[Point] = Field(default=None, alias="PointOnSurface")
    dimension: Optional[Dimension] = Field(default=None, alias="Dimension")
    boundary: Optional[Geometry] = Field(default=None, alias="Boundary")
    boundary_dimension: Optional[Dimension] = Field(default=None, alias="BoundaryDimension")
    envelope: Optional[Geometry] = Field(default=None, alias="Envelope")
    envelope_internal: Optional[Envelope] = Field(default=None, alias="EnvelopeInternal")
    is_rectangle: Optional[StrictBool] = Field(default=None, alias="IsRectangle")
    __properties: ClassVar[List[str]] = ["Factory", "UserData", "SRID", "GeometryType", "OgcGeometryType", "PrecisionModel", "Coordinate", "Coordinates", "NumPoints", "NumGeometries", "IsSimple", "IsValid", "IsEmpty", "Area", "Length", "Centroid", "InteriorPoint", "PointOnSurface", "Dimension", "Boundary", "BoundaryDimension", "Envelope", "EnvelopeInternal", "IsRectangle"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Geometry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "geometry_type",
                "coordinates",
                "num_points",
                "num_geometries",
                "is_simple",
                "is_valid",
                "is_empty",
                "area",
                "length",
                "is_rectangle",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of factory
        if self.factory:
            _dict['Factory'] = self.factory.to_dict()
        # override the default output from pydantic by calling `to_dict()` of precision_model
        if self.precision_model:
            _dict['PrecisionModel'] = self.precision_model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of coordinate
        if self.coordinate:
            _dict['Coordinate'] = self.coordinate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in coordinates (list)
        _items = []
        if self.coordinates:
            for _item in self.coordinates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Coordinates'] = _items
        # override the default output from pydantic by calling `to_dict()` of centroid
        if self.centroid:
            _dict['Centroid'] = self.centroid.to_dict()
        # override the default output from pydantic by calling `to_dict()` of interior_point
        if self.interior_point:
            _dict['InteriorPoint'] = self.interior_point.to_dict()
        # override the default output from pydantic by calling `to_dict()` of point_on_surface
        if self.point_on_surface:
            _dict['PointOnSurface'] = self.point_on_surface.to_dict()
        # override the default output from pydantic by calling `to_dict()` of boundary
        if self.boundary:
            _dict['Boundary'] = self.boundary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of envelope
        if self.envelope:
            _dict['Envelope'] = self.envelope.to_dict()
        # override the default output from pydantic by calling `to_dict()` of envelope_internal
        if self.envelope_internal:
            _dict['EnvelopeInternal'] = self.envelope_internal.to_dict()
        # set to None if user_data (nullable) is None
        # and model_fields_set contains the field
        if self.user_data is None and "user_data" in self.model_fields_set:
            _dict['UserData'] = None

        # set to None if geometry_type (nullable) is None
        # and model_fields_set contains the field
        if self.geometry_type is None and "geometry_type" in self.model_fields_set:
            _dict['GeometryType'] = None

        # set to None if coordinates (nullable) is None
        # and model_fields_set contains the field
        if self.coordinates is None and "coordinates" in self.model_fields_set:
            _dict['Coordinates'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Geometry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Factory": GeometryFactory.from_dict(obj.get("Factory")) if obj.get("Factory") is not None else None,
            "UserData": obj.get("UserData"),
            "SRID": obj.get("SRID"),
            "GeometryType": obj.get("GeometryType"),
            "OgcGeometryType": obj.get("OgcGeometryType"),
            "PrecisionModel": PrecisionModel.from_dict(obj.get("PrecisionModel")) if obj.get("PrecisionModel") is not None else None,
            "Coordinate": Coordinate.from_dict(obj.get("Coordinate")) if obj.get("Coordinate") is not None else None,
            "Coordinates": [Coordinate.from_dict(_item) for _item in obj.get("Coordinates")] if obj.get("Coordinates") is not None else None,
            "NumPoints": obj.get("NumPoints"),
            "NumGeometries": obj.get("NumGeometries"),
            "IsSimple": obj.get("IsSimple"),
            "IsValid": obj.get("IsValid"),
            "IsEmpty": obj.get("IsEmpty"),
            "Area": obj.get("Area"),
            "Length": obj.get("Length"),
            "Centroid": Point.from_dict(obj.get("Centroid")) if obj.get("Centroid") is not None else None,
            "InteriorPoint": Point.from_dict(obj.get("InteriorPoint")) if obj.get("InteriorPoint") is not None else None,
            "PointOnSurface": Point.from_dict(obj.get("PointOnSurface")) if obj.get("PointOnSurface") is not None else None,
            "Dimension": obj.get("Dimension"),
            "Boundary": Geometry.from_dict(obj.get("Boundary")) if obj.get("Boundary") is not None else None,
            "BoundaryDimension": obj.get("BoundaryDimension"),
            "Envelope": Geometry.from_dict(obj.get("Envelope")) if obj.get("Envelope") is not None else None,
            "EnvelopeInternal": Envelope.from_dict(obj.get("EnvelopeInternal")) if obj.get("EnvelopeInternal") is not None else None,
            "IsRectangle": obj.get("IsRectangle")
        })
        return _obj

from openapi_server.models.point import Point
# TODO: Rewrite to not use raise_errors
Geometry.model_rebuild(raise_errors=False)

