# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.cheapest_room_combination import CheapestRoomCombination
from openapi_server.models.room_details import RoomDetails
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MssResponseShort(BaseModel):
    """
    MssResponseShort
    """ # noqa: E501
    hotel_id: Optional[StrictInt] = Field(default=None, alias="HotelId")
    a0_rid: Optional[StrictStr] = Field(default=None, alias="A0RID")
    bookable: Optional[StrictBool] = Field(default=None, alias="Bookable")
    channel_id: Optional[StrictStr] = Field(default=None, alias="ChannelID")
    channellink: Optional[StrictStr] = Field(default=None, alias="Channellink")
    offer_id: Optional[StrictStr] = Field(default=None, alias="OfferId")
    offer_gid: Optional[StrictStr] = Field(default=None, alias="OfferGid")
    offer_typ: Optional[StrictInt] = Field(default=None, alias="OfferTyp")
    offer_show: Optional[StrictInt] = Field(default=None, alias="OfferShow")
    cheapest_offer: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="CheapestOffer")
    cheapest_offer_string: Optional[StrictStr] = Field(default=None, alias="CheapestOfferString")
    onlinepayment_methods: Optional[StrictStr] = Field(default=None, alias="OnlinepaymentMethods")
    onlinepayment_prepayment: Optional[StrictStr] = Field(default=None, alias="OnlinepaymentPrepayment")
    onlinepayment_c_cards: Optional[StrictStr] = Field(default=None, alias="OnlinepaymentCCards")
    cheapest_offer_ws: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="CheapestOffer_ws")
    cheapest_offer_bb: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="CheapestOffer_bb")
    cheapest_offer_hb: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="CheapestOffer_hb")
    cheapest_offer_fb: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="CheapestOffer_fb")
    cheapest_offer_ai: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="CheapestOffer_ai")
    room_details: Optional[List[RoomDetails]] = Field(default=None, alias="RoomDetails")
    cheapest_offer_detail: Optional[List[CheapestRoomCombination]] = Field(default=None, alias="CheapestOfferDetail")
    __properties: ClassVar[List[str]] = ["HotelId", "A0RID", "Bookable", "ChannelID", "Channellink", "OfferId", "OfferGid", "OfferTyp", "OfferShow", "CheapestOffer", "CheapestOfferString", "OnlinepaymentMethods", "OnlinepaymentPrepayment", "OnlinepaymentCCards", "CheapestOffer_ws", "CheapestOffer_bb", "CheapestOffer_hb", "CheapestOffer_fb", "CheapestOffer_ai", "RoomDetails", "CheapestOfferDetail"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MssResponseShort from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in room_details (list)
        _items = []
        if self.room_details:
            for _item in self.room_details:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RoomDetails'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cheapest_offer_detail (list)
        _items = []
        if self.cheapest_offer_detail:
            for _item in self.cheapest_offer_detail:
                if _item:
                    _items.append(_item.to_dict())
            _dict['CheapestOfferDetail'] = _items
        # set to None if a0_rid (nullable) is None
        # and model_fields_set contains the field
        if self.a0_rid is None and "a0_rid" in self.model_fields_set:
            _dict['A0RID'] = None

        # set to None if channel_id (nullable) is None
        # and model_fields_set contains the field
        if self.channel_id is None and "channel_id" in self.model_fields_set:
            _dict['ChannelID'] = None

        # set to None if channellink (nullable) is None
        # and model_fields_set contains the field
        if self.channellink is None and "channellink" in self.model_fields_set:
            _dict['Channellink'] = None

        # set to None if offer_id (nullable) is None
        # and model_fields_set contains the field
        if self.offer_id is None and "offer_id" in self.model_fields_set:
            _dict['OfferId'] = None

        # set to None if offer_gid (nullable) is None
        # and model_fields_set contains the field
        if self.offer_gid is None and "offer_gid" in self.model_fields_set:
            _dict['OfferGid'] = None

        # set to None if offer_typ (nullable) is None
        # and model_fields_set contains the field
        if self.offer_typ is None and "offer_typ" in self.model_fields_set:
            _dict['OfferTyp'] = None

        # set to None if offer_show (nullable) is None
        # and model_fields_set contains the field
        if self.offer_show is None and "offer_show" in self.model_fields_set:
            _dict['OfferShow'] = None

        # set to None if cheapest_offer_string (nullable) is None
        # and model_fields_set contains the field
        if self.cheapest_offer_string is None and "cheapest_offer_string" in self.model_fields_set:
            _dict['CheapestOfferString'] = None

        # set to None if onlinepayment_methods (nullable) is None
        # and model_fields_set contains the field
        if self.onlinepayment_methods is None and "onlinepayment_methods" in self.model_fields_set:
            _dict['OnlinepaymentMethods'] = None

        # set to None if onlinepayment_prepayment (nullable) is None
        # and model_fields_set contains the field
        if self.onlinepayment_prepayment is None and "onlinepayment_prepayment" in self.model_fields_set:
            _dict['OnlinepaymentPrepayment'] = None

        # set to None if onlinepayment_c_cards (nullable) is None
        # and model_fields_set contains the field
        if self.onlinepayment_c_cards is None and "onlinepayment_c_cards" in self.model_fields_set:
            _dict['OnlinepaymentCCards'] = None

        # set to None if cheapest_offer_ws (nullable) is None
        # and model_fields_set contains the field
        if self.cheapest_offer_ws is None and "cheapest_offer_ws" in self.model_fields_set:
            _dict['CheapestOffer_ws'] = None

        # set to None if cheapest_offer_bb (nullable) is None
        # and model_fields_set contains the field
        if self.cheapest_offer_bb is None and "cheapest_offer_bb" in self.model_fields_set:
            _dict['CheapestOffer_bb'] = None

        # set to None if cheapest_offer_hb (nullable) is None
        # and model_fields_set contains the field
        if self.cheapest_offer_hb is None and "cheapest_offer_hb" in self.model_fields_set:
            _dict['CheapestOffer_hb'] = None

        # set to None if cheapest_offer_fb (nullable) is None
        # and model_fields_set contains the field
        if self.cheapest_offer_fb is None and "cheapest_offer_fb" in self.model_fields_set:
            _dict['CheapestOffer_fb'] = None

        # set to None if cheapest_offer_ai (nullable) is None
        # and model_fields_set contains the field
        if self.cheapest_offer_ai is None and "cheapest_offer_ai" in self.model_fields_set:
            _dict['CheapestOffer_ai'] = None

        # set to None if room_details (nullable) is None
        # and model_fields_set contains the field
        if self.room_details is None and "room_details" in self.model_fields_set:
            _dict['RoomDetails'] = None

        # set to None if cheapest_offer_detail (nullable) is None
        # and model_fields_set contains the field
        if self.cheapest_offer_detail is None and "cheapest_offer_detail" in self.model_fields_set:
            _dict['CheapestOfferDetail'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MssResponseShort from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "HotelId": obj.get("HotelId"),
            "A0RID": obj.get("A0RID"),
            "Bookable": obj.get("Bookable"),
            "ChannelID": obj.get("ChannelID"),
            "Channellink": obj.get("Channellink"),
            "OfferId": obj.get("OfferId"),
            "OfferGid": obj.get("OfferGid"),
            "OfferTyp": obj.get("OfferTyp"),
            "OfferShow": obj.get("OfferShow"),
            "CheapestOffer": obj.get("CheapestOffer"),
            "CheapestOfferString": obj.get("CheapestOfferString"),
            "OnlinepaymentMethods": obj.get("OnlinepaymentMethods"),
            "OnlinepaymentPrepayment": obj.get("OnlinepaymentPrepayment"),
            "OnlinepaymentCCards": obj.get("OnlinepaymentCCards"),
            "CheapestOffer_ws": obj.get("CheapestOffer_ws"),
            "CheapestOffer_bb": obj.get("CheapestOffer_bb"),
            "CheapestOffer_hb": obj.get("CheapestOffer_hb"),
            "CheapestOffer_fb": obj.get("CheapestOffer_fb"),
            "CheapestOffer_ai": obj.get("CheapestOffer_ai"),
            "RoomDetails": [RoomDetails.from_dict(_item) for _item in obj.get("RoomDetails")] if obj.get("RoomDetails") is not None else None,
            "CheapestOfferDetail": [CheapestRoomCombination.from_dict(_item) for _item in obj.get("CheapestOfferDetail")] if obj.get("CheapestOfferDetail") is not None else None
        })
        return _obj


