# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.contact_infos import ContactInfos
from openapi_server.models.detail import Detail
from openapi_server.models.distance_info import DistanceInfo
from openapi_server.models.gps_info import GpsInfo
from openapi_server.models.gps_polygon import GpsPolygon
from openapi_server.models.image_gallery import ImageGallery
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.metadata import Metadata
from openapi_server.models.odh_tags import ODHTags
from openapi_server.models.region_link import RegionLink
from openapi_server.models.related_content import RelatedContent
from openapi_server.models.tags import Tags
from openapi_server.models.tourism_association_link import TourismAssociationLink
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MunicipalityLinked(BaseModel):
    """
    MunicipalityLinked
    """ # noqa: E501
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    var_self: Optional[StrictStr] = Field(default=None, description="generated field", alias="Self")
    odh_tags: Optional[List[ODHTags]] = Field(default=None, description="generated field", alias="ODHTags")
    odh_active: Optional[StrictBool] = Field(default=None, description="generated field", alias="OdhActive")
    region: Optional[RegionLink] = Field(default=None, alias="Region")
    tourismassociation: Optional[TourismAssociationLink] = Field(default=None, alias="Tourismassociation")
    gps_info: Optional[List[GpsInfo]] = Field(default=None, alias="GpsInfo")
    gpstype: Optional[StrictStr] = Field(default=None, description="generated field", alias="Gpstype")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="generated field", alias="Latitude")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="generated field", alias="Longitude")
    altitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="generated field", alias="Altitude")
    altitude_unitof_measure: Optional[StrictStr] = Field(default=None, description="generated field", alias="AltitudeUnitofMeasure")
    gps_points: Optional[Dict[str, GpsInfo]] = Field(default=None, description="generated field", alias="GpsPoints")
    additional_properties: Optional[Dict[str, Any]] = Field(default=None, alias="AdditionalProperties")
    plz: Optional[StrictStr] = Field(default=None, alias="Plz")
    region_id: Optional[StrictStr] = Field(default=None, alias="RegionId")
    tourismverein_id: Optional[StrictStr] = Field(default=None, alias="TourismvereinId")
    siag_id: Optional[StrictStr] = Field(default=None, alias="SiagId")
    gps_polygon: Optional[List[GpsPolygon]] = Field(default=None, alias="GpsPolygon")
    visible_in_search: Optional[StrictBool] = Field(default=None, alias="VisibleInSearch")
    inhabitants: Optional[StrictInt] = Field(default=None, alias="Inhabitants")
    istat_number: Optional[StrictStr] = Field(default=None, alias="IstatNumber")
    related_content: Optional[List[RelatedContent]] = Field(default=None, alias="RelatedContent")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    active: Optional[StrictBool] = Field(default=None, alias="Active")
    custom_id: Optional[StrictStr] = Field(default=None, alias="CustomId")
    shortname: Optional[StrictStr] = Field(default=None, alias="Shortname")
    detail: Optional[Dict[str, Detail]] = Field(default=None, alias="Detail")
    contact_infos: Optional[Dict[str, ContactInfos]] = Field(default=None, alias="ContactInfos")
    image_gallery: Optional[List[ImageGallery]] = Field(default=None, alias="ImageGallery")
    smg_tags: Optional[List[StrictStr]] = Field(default=None, alias="SmgTags")
    smg_active: Optional[StrictBool] = Field(default=None, description="Obsolete, use PublishedOn", alias="SmgActive")
    has_language: Optional[List[StrictStr]] = Field(default=None, alias="HasLanguage")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    published_on: Optional[List[StrictStr]] = Field(default=None, alias="PublishedOn")
    source: Optional[StrictStr] = Field(default=None, alias="Source")
    mapping: Optional[Dict[str, Dict[str, StrictStr]]] = Field(default=None, alias="Mapping")
    distance_info: Optional[DistanceInfo] = Field(default=None, alias="DistanceInfo")
    tags: Optional[List[Tags]] = Field(default=None, alias="Tags")
    tag_ids: Optional[List[StrictStr]] = Field(default=None, alias="TagIds")
    __properties: ClassVar[List[str]] = ["_Meta", "Self", "ODHTags", "OdhActive", "Region", "Tourismassociation", "GpsInfo", "Gpstype", "Latitude", "Longitude", "Altitude", "AltitudeUnitofMeasure", "GpsPoints", "AdditionalProperties", "Plz", "RegionId", "TourismvereinId", "SiagId", "GpsPolygon", "VisibleInSearch", "Inhabitants", "IstatNumber", "RelatedContent", "LicenseInfo", "Id", "Active", "CustomId", "Shortname", "Detail", "ContactInfos", "ImageGallery", "SmgTags", "SmgActive", "HasLanguage", "LastChange", "FirstImport", "PublishedOn", "Source", "Mapping", "DistanceInfo", "Tags", "TagIds"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MunicipalityLinked from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_self",
                "odh_tags",
                "odh_active",
                "gpstype",
                "latitude",
                "longitude",
                "altitude",
                "altitude_unitof_measure",
                "gps_points",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in odh_tags (list)
        _items = []
        if self.odh_tags:
            for _item in self.odh_tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ODHTags'] = _items
        # override the default output from pydantic by calling `to_dict()` of region
        if self.region:
            _dict['Region'] = self.region.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tourismassociation
        if self.tourismassociation:
            _dict['Tourismassociation'] = self.tourismassociation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in gps_info (list)
        _items = []
        if self.gps_info:
            for _item in self.gps_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['GpsInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in gps_points (dict)
        _field_dict = {}
        if self.gps_points:
            for _key in self.gps_points:
                if self.gps_points[_key]:
                    _field_dict[_key] = self.gps_points[_key].to_dict()
            _dict['GpsPoints'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in gps_polygon (list)
        _items = []
        if self.gps_polygon:
            for _item in self.gps_polygon:
                if _item:
                    _items.append(_item.to_dict())
            _dict['GpsPolygon'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_content (list)
        _items = []
        if self.related_content:
            for _item in self.related_content:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RelatedContent'] = _items
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in detail (dict)
        _field_dict = {}
        if self.detail:
            for _key in self.detail:
                if self.detail[_key]:
                    _field_dict[_key] = self.detail[_key].to_dict()
            _dict['Detail'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in contact_infos (dict)
        _field_dict = {}
        if self.contact_infos:
            for _key in self.contact_infos:
                if self.contact_infos[_key]:
                    _field_dict[_key] = self.contact_infos[_key].to_dict()
            _dict['ContactInfos'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in image_gallery (list)
        _items = []
        if self.image_gallery:
            for _item in self.image_gallery:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ImageGallery'] = _items
        # override the default output from pydantic by calling `to_dict()` of distance_info
        if self.distance_info:
            _dict['DistanceInfo'] = self.distance_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Tags'] = _items
        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if odh_tags (nullable) is None
        # and model_fields_set contains the field
        if self.odh_tags is None and "odh_tags" in self.model_fields_set:
            _dict['ODHTags'] = None

        # set to None if gps_info (nullable) is None
        # and model_fields_set contains the field
        if self.gps_info is None and "gps_info" in self.model_fields_set:
            _dict['GpsInfo'] = None

        # set to None if gpstype (nullable) is None
        # and model_fields_set contains the field
        if self.gpstype is None and "gpstype" in self.model_fields_set:
            _dict['Gpstype'] = None

        # set to None if altitude (nullable) is None
        # and model_fields_set contains the field
        if self.altitude is None and "altitude" in self.model_fields_set:
            _dict['Altitude'] = None

        # set to None if altitude_unitof_measure (nullable) is None
        # and model_fields_set contains the field
        if self.altitude_unitof_measure is None and "altitude_unitof_measure" in self.model_fields_set:
            _dict['AltitudeUnitofMeasure'] = None

        # set to None if gps_points (nullable) is None
        # and model_fields_set contains the field
        if self.gps_points is None and "gps_points" in self.model_fields_set:
            _dict['GpsPoints'] = None

        # set to None if additional_properties (nullable) is None
        # and model_fields_set contains the field
        if self.additional_properties is None and "additional_properties" in self.model_fields_set:
            _dict['AdditionalProperties'] = None

        # set to None if plz (nullable) is None
        # and model_fields_set contains the field
        if self.plz is None and "plz" in self.model_fields_set:
            _dict['Plz'] = None

        # set to None if region_id (nullable) is None
        # and model_fields_set contains the field
        if self.region_id is None and "region_id" in self.model_fields_set:
            _dict['RegionId'] = None

        # set to None if tourismverein_id (nullable) is None
        # and model_fields_set contains the field
        if self.tourismverein_id is None and "tourismverein_id" in self.model_fields_set:
            _dict['TourismvereinId'] = None

        # set to None if siag_id (nullable) is None
        # and model_fields_set contains the field
        if self.siag_id is None and "siag_id" in self.model_fields_set:
            _dict['SiagId'] = None

        # set to None if gps_polygon (nullable) is None
        # and model_fields_set contains the field
        if self.gps_polygon is None and "gps_polygon" in self.model_fields_set:
            _dict['GpsPolygon'] = None

        # set to None if istat_number (nullable) is None
        # and model_fields_set contains the field
        if self.istat_number is None and "istat_number" in self.model_fields_set:
            _dict['IstatNumber'] = None

        # set to None if related_content (nullable) is None
        # and model_fields_set contains the field
        if self.related_content is None and "related_content" in self.model_fields_set:
            _dict['RelatedContent'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if custom_id (nullable) is None
        # and model_fields_set contains the field
        if self.custom_id is None and "custom_id" in self.model_fields_set:
            _dict['CustomId'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['Shortname'] = None

        # set to None if detail (nullable) is None
        # and model_fields_set contains the field
        if self.detail is None and "detail" in self.model_fields_set:
            _dict['Detail'] = None

        # set to None if contact_infos (nullable) is None
        # and model_fields_set contains the field
        if self.contact_infos is None and "contact_infos" in self.model_fields_set:
            _dict['ContactInfos'] = None

        # set to None if image_gallery (nullable) is None
        # and model_fields_set contains the field
        if self.image_gallery is None and "image_gallery" in self.model_fields_set:
            _dict['ImageGallery'] = None

        # set to None if smg_tags (nullable) is None
        # and model_fields_set contains the field
        if self.smg_tags is None and "smg_tags" in self.model_fields_set:
            _dict['SmgTags'] = None

        # set to None if has_language (nullable) is None
        # and model_fields_set contains the field
        if self.has_language is None and "has_language" in self.model_fields_set:
            _dict['HasLanguage'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if published_on (nullable) is None
        # and model_fields_set contains the field
        if self.published_on is None and "published_on" in self.model_fields_set:
            _dict['PublishedOn'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['Source'] = None

        # set to None if mapping (nullable) is None
        # and model_fields_set contains the field
        if self.mapping is None and "mapping" in self.model_fields_set:
            _dict['Mapping'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['Tags'] = None

        # set to None if tag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.tag_ids is None and "tag_ids" in self.model_fields_set:
            _dict['TagIds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MunicipalityLinked from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "Self": obj.get("Self"),
            "ODHTags": [ODHTags.from_dict(_item) for _item in obj.get("ODHTags")] if obj.get("ODHTags") is not None else None,
            "OdhActive": obj.get("OdhActive"),
            "Region": RegionLink.from_dict(obj.get("Region")) if obj.get("Region") is not None else None,
            "Tourismassociation": TourismAssociationLink.from_dict(obj.get("Tourismassociation")) if obj.get("Tourismassociation") is not None else None,
            "GpsInfo": [GpsInfo.from_dict(_item) for _item in obj.get("GpsInfo")] if obj.get("GpsInfo") is not None else None,
            "Gpstype": obj.get("Gpstype"),
            "Latitude": obj.get("Latitude"),
            "Longitude": obj.get("Longitude"),
            "Altitude": obj.get("Altitude"),
            "AltitudeUnitofMeasure": obj.get("AltitudeUnitofMeasure"),
            "GpsPoints": dict(
                (_k, GpsInfo.from_dict(_v))
                for _k, _v in obj.get("GpsPoints").items()
            )
            if obj.get("GpsPoints") is not None
            else None,
            "AdditionalProperties": obj.get("AdditionalProperties"),
            "Plz": obj.get("Plz"),
            "RegionId": obj.get("RegionId"),
            "TourismvereinId": obj.get("TourismvereinId"),
            "SiagId": obj.get("SiagId"),
            "GpsPolygon": [GpsPolygon.from_dict(_item) for _item in obj.get("GpsPolygon")] if obj.get("GpsPolygon") is not None else None,
            "VisibleInSearch": obj.get("VisibleInSearch"),
            "Inhabitants": obj.get("Inhabitants"),
            "IstatNumber": obj.get("IstatNumber"),
            "RelatedContent": [RelatedContent.from_dict(_item) for _item in obj.get("RelatedContent")] if obj.get("RelatedContent") is not None else None,
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "Id": obj.get("Id"),
            "Active": obj.get("Active"),
            "CustomId": obj.get("CustomId"),
            "Shortname": obj.get("Shortname"),
            "Detail": dict(
                (_k, Detail.from_dict(_v))
                for _k, _v in obj.get("Detail").items()
            )
            if obj.get("Detail") is not None
            else None,
            "ContactInfos": dict(
                (_k, ContactInfos.from_dict(_v))
                for _k, _v in obj.get("ContactInfos").items()
            )
            if obj.get("ContactInfos") is not None
            else None,
            "ImageGallery": [ImageGallery.from_dict(_item) for _item in obj.get("ImageGallery")] if obj.get("ImageGallery") is not None else None,
            "SmgTags": obj.get("SmgTags"),
            "SmgActive": obj.get("SmgActive"),
            "HasLanguage": obj.get("HasLanguage"),
            "LastChange": obj.get("LastChange"),
            "FirstImport": obj.get("FirstImport"),
            "PublishedOn": obj.get("PublishedOn"),
            "Source": obj.get("Source"),
            "Mapping": obj.get("Mapping"),
            "DistanceInfo": DistanceInfo.from_dict(obj.get("DistanceInfo")) if obj.get("DistanceInfo") is not None else None,
            "Tags": [Tags.from_dict(_item) for _item in obj.get("Tags")] if obj.get("Tags") is not None else None,
            "TagIds": obj.get("TagIds")
        })
        return _obj


