# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.coordinate_sequence_factory import CoordinateSequenceFactory
from openapi_server.models.precision_model import PrecisionModel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NtsGeometryServices(BaseModel):
    """
    NtsGeometryServices
    """ # noqa: E501
    geometry_overlay: Optional[Dict[str, Any]] = Field(default=None, alias="GeometryOverlay")
    coordinate_equality_comparer: Optional[Dict[str, Any]] = Field(default=None, alias="CoordinateEqualityComparer")
    default_srid: Optional[StrictInt] = Field(default=None, alias="DefaultSRID")
    default_coordinate_sequence_factory: Optional[CoordinateSequenceFactory] = Field(default=None, alias="DefaultCoordinateSequenceFactory")
    default_precision_model: Optional[PrecisionModel] = Field(default=None, alias="DefaultPrecisionModel")
    __properties: ClassVar[List[str]] = ["GeometryOverlay", "CoordinateEqualityComparer", "DefaultSRID", "DefaultCoordinateSequenceFactory", "DefaultPrecisionModel"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NtsGeometryServices from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "default_srid",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of default_coordinate_sequence_factory
        if self.default_coordinate_sequence_factory:
            _dict['DefaultCoordinateSequenceFactory'] = self.default_coordinate_sequence_factory.to_dict()
        # override the default output from pydantic by calling `to_dict()` of default_precision_model
        if self.default_precision_model:
            _dict['DefaultPrecisionModel'] = self.default_precision_model.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NtsGeometryServices from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "GeometryOverlay": obj.get("GeometryOverlay"),
            "CoordinateEqualityComparer": obj.get("CoordinateEqualityComparer"),
            "DefaultSRID": obj.get("DefaultSRID"),
            "DefaultCoordinateSequenceFactory": CoordinateSequenceFactory.from_dict(obj.get("DefaultCoordinateSequenceFactory")) if obj.get("DefaultCoordinateSequenceFactory") is not None else None,
            "DefaultPrecisionModel": PrecisionModel.from_dict(obj.get("DefaultPrecisionModel")) if obj.get("DefaultPrecisionModel") is not None else None
        })
        return _obj


