# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.activity_lts_data_properties import ActivityLtsDataProperties
from openapi_server.models.echarging_data_properties import EchargingDataProperties
from openapi_server.models.gastronomy_lts_data_properties import GastronomyLtsDataProperties
from openapi_server.models.poi_age_data_properties import PoiAgeDataProperties
from openapi_server.models.poi_lts_data_properties import PoiLtsDataProperties
from openapi_server.models.suedtirol_wein_company_data_properties import SuedtirolWeinCompanyDataProperties
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ODHActivityPoiLinkedAdditionalProperties(BaseModel):
    """
    ODHActivityPoiLinkedAdditionalProperties
    """ # noqa: E501
    echarging_data_properties: Optional[EchargingDataProperties] = Field(default=None, alias="EchargingDataProperties")
    activity_lts_data_properties: Optional[ActivityLtsDataProperties] = Field(default=None, alias="ActivityLtsDataProperties")
    poi_lts_data_properties: Optional[PoiLtsDataProperties] = Field(default=None, alias="PoiLtsDataProperties")
    gastronomy_lts_data_properties: Optional[GastronomyLtsDataProperties] = Field(default=None, alias="GastronomyLtsDataProperties")
    poi_age_data_properties: Optional[PoiAgeDataProperties] = Field(default=None, alias="PoiAgeDataProperties")
    suedtirol_wein_company_data_properties: Optional[SuedtirolWeinCompanyDataProperties] = Field(default=None, alias="SuedtirolWeinCompanyDataProperties")
    __properties: ClassVar[List[str]] = ["EchargingDataProperties", "ActivityLtsDataProperties", "PoiLtsDataProperties", "GastronomyLtsDataProperties", "PoiAgeDataProperties", "SuedtirolWeinCompanyDataProperties"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ODHActivityPoiLinkedAdditionalProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of echarging_data_properties
        if self.echarging_data_properties:
            _dict['EchargingDataProperties'] = self.echarging_data_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of activity_lts_data_properties
        if self.activity_lts_data_properties:
            _dict['ActivityLtsDataProperties'] = self.activity_lts_data_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of poi_lts_data_properties
        if self.poi_lts_data_properties:
            _dict['PoiLtsDataProperties'] = self.poi_lts_data_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gastronomy_lts_data_properties
        if self.gastronomy_lts_data_properties:
            _dict['GastronomyLtsDataProperties'] = self.gastronomy_lts_data_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of poi_age_data_properties
        if self.poi_age_data_properties:
            _dict['PoiAgeDataProperties'] = self.poi_age_data_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of suedtirol_wein_company_data_properties
        if self.suedtirol_wein_company_data_properties:
            _dict['SuedtirolWeinCompanyDataProperties'] = self.suedtirol_wein_company_data_properties.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ODHActivityPoiLinkedAdditionalProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "EchargingDataProperties": EchargingDataProperties.from_dict(obj.get("EchargingDataProperties")) if obj.get("EchargingDataProperties") is not None else None,
            "ActivityLtsDataProperties": ActivityLtsDataProperties.from_dict(obj.get("ActivityLtsDataProperties")) if obj.get("ActivityLtsDataProperties") is not None else None,
            "PoiLtsDataProperties": PoiLtsDataProperties.from_dict(obj.get("PoiLtsDataProperties")) if obj.get("PoiLtsDataProperties") is not None else None,
            "GastronomyLtsDataProperties": GastronomyLtsDataProperties.from_dict(obj.get("GastronomyLtsDataProperties")) if obj.get("GastronomyLtsDataProperties") is not None else None,
            "PoiAgeDataProperties": PoiAgeDataProperties.from_dict(obj.get("PoiAgeDataProperties")) if obj.get("PoiAgeDataProperties") is not None else None,
            "SuedtirolWeinCompanyDataProperties": SuedtirolWeinCompanyDataProperties.from_dict(obj.get("SuedtirolWeinCompanyDataProperties")) if obj.get("SuedtirolWeinCompanyDataProperties") is not None else None
        })
        return _obj


