# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.operation_schedule_time import OperationScheduleTime
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OperationSchedule(BaseModel):
    """
    Wiki Article on <a href='https://github.com/noi-techpark/odh-docs/wiki/Operationschedule-Format' target='_blank'>Wiki Article</a>
    """ # noqa: E501
    operationschedule_name: Optional[Dict[str, StrictStr]] = Field(default=None, alias="OperationscheduleName")
    start: Optional[datetime] = Field(default=None, alias="Start")
    stop: Optional[datetime] = Field(default=None, alias="Stop")
    type: Optional[StrictStr] = Field(default=None, description="1 - Standard, 2 - Only day + month recurring (year not to consider) 3 - only month recurring (season: year and day not to consider), Wiki Article on <a href='https://github.com/noi-techpark/odh-docs/wiki/Operationschedule-Format' target='_blank'>Wiki Article</a>", alias="Type")
    operation_schedule_time: Optional[List[OperationScheduleTime]] = Field(default=None, alias="OperationScheduleTime")
    __properties: ClassVar[List[str]] = ["OperationscheduleName", "Start", "Stop", "Type", "OperationScheduleTime"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OperationSchedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in operation_schedule_time (list)
        _items = []
        if self.operation_schedule_time:
            for _item in self.operation_schedule_time:
                if _item:
                    _items.append(_item.to_dict())
            _dict['OperationScheduleTime'] = _items
        # set to None if operationschedule_name (nullable) is None
        # and model_fields_set contains the field
        if self.operationschedule_name is None and "operationschedule_name" in self.model_fields_set:
            _dict['OperationscheduleName'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        # set to None if operation_schedule_time (nullable) is None
        # and model_fields_set contains the field
        if self.operation_schedule_time is None and "operation_schedule_time" in self.model_fields_set:
            _dict['OperationScheduleTime'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OperationSchedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "OperationscheduleName": obj.get("OperationscheduleName"),
            "Start": obj.get("Start"),
            "Stop": obj.get("Stop"),
            "Type": obj.get("Type"),
            "OperationScheduleTime": [OperationScheduleTime.from_dict(_item) for _item in obj.get("OperationScheduleTime")] if obj.get("OperationScheduleTime") is not None else None
        })
        return _obj


