# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OperationScheduleTime(BaseModel):
    """
    OperationScheduleTime
    """ # noqa: E501
    start: Optional[StrictStr] = Field(default=None, alias="Start")
    end: Optional[StrictStr] = Field(default=None, alias="End")
    monday: Optional[StrictBool] = Field(default=None, alias="Monday")
    tuesday: Optional[StrictBool] = Field(default=None, alias="Tuesday")
    wednesday: Optional[StrictBool] = Field(default=None, alias="Wednesday")
    thuresday: Optional[StrictBool] = Field(default=None, description="Will be removed within 2023-12-31", alias="Thuresday")
    thursday: Optional[StrictBool] = Field(default=None, alias="Thursday")
    friday: Optional[StrictBool] = Field(default=None, alias="Friday")
    saturday: Optional[StrictBool] = Field(default=None, alias="Saturday")
    sunday: Optional[StrictBool] = Field(default=None, alias="Sunday")
    state: Optional[StrictInt] = Field(default=None, description="1 = closed, 2 = open, 0 = undefined, Wiki Article on <a href='https://github.com/noi-techpark/odh-docs/wiki/Operationschedule-Format' target='_blank'>Wiki Article</a>", alias="State")
    timecode: Optional[StrictInt] = Field(default=None, description="1 = General Opening Time, 2 = time range for warm meals, 3 = time range for pizza, 4 = time range for snack’s, Wiki Article on <a href='https://github.com/noi-techpark/odh-docs/wiki/Operationschedule-Format' target='_blank'>Wiki Article</a>", alias="Timecode")
    __properties: ClassVar[List[str]] = ["Start", "End", "Monday", "Tuesday", "Wednesday", "Thuresday", "Thursday", "Friday", "Saturday", "Sunday", "State", "Timecode"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OperationScheduleTime from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "thuresday",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OperationScheduleTime from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Start": obj.get("Start"),
            "End": obj.get("End"),
            "Monday": obj.get("Monday"),
            "Tuesday": obj.get("Tuesday"),
            "Wednesday": obj.get("Wednesday"),
            "Thuresday": obj.get("Thuresday"),
            "Thursday": obj.get("Thursday"),
            "Friday": obj.get("Friday"),
            "Saturday": obj.get("Saturday"),
            "Sunday": obj.get("Sunday"),
            "State": obj.get("State"),
            "Timecode": obj.get("Timecode")
        })
        return _obj


