# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PushConfig(BaseModel):
    """
    PushConfig
    """ # noqa: E501
    path_param: Optional[List[StrictStr]] = Field(default=None, alias="PathParam")
    base_url: Optional[StrictStr] = Field(default=None, alias="BaseUrl")
    push_api_url: Optional[StrictStr] = Field(default=None, alias="PushApiUrl")
    __properties: ClassVar[List[str]] = ["PathParam", "BaseUrl", "PushApiUrl"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PushConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "push_api_url",
            },
            exclude_none=True,
        )
        # set to None if path_param (nullable) is None
        # and model_fields_set contains the field
        if self.path_param is None and "path_param" in self.model_fields_set:
            _dict['PathParam'] = None

        # set to None if base_url (nullable) is None
        # and model_fields_set contains the field
        if self.base_url is None and "base_url" in self.model_fields_set:
            _dict['BaseUrl'] = None

        # set to None if push_api_url (nullable) is None
        # and model_fields_set contains the field
        if self.push_api_url is None and "push_api_url" in self.model_fields_set:
            _dict['PushApiUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PushConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "PathParam": obj.get("PathParam"),
            "BaseUrl": obj.get("BaseUrl"),
            "PushApiUrl": obj.get("PushApiUrl")
        })
        return _obj


