# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RatePlan(BaseModel):
    """
    RatePlan
    """ # noqa: E501
    charge_type: Optional[StrictStr] = Field(default=None, alias="ChargeType")
    rate_plan_id: Optional[StrictStr] = Field(default=None, alias="RatePlanId")
    code: Optional[StrictStr] = Field(default=None, alias="Code")
    name: Optional[Dict[str, StrictStr]] = Field(default=None, alias="Name")
    short_description: Optional[Dict[str, StrictStr]] = Field(default=None, alias="ShortDescription")
    long_description: Optional[Dict[str, StrictStr]] = Field(default=None, alias="LongDescription")
    last_update: Optional[datetime] = Field(default=None, alias="LastUpdate")
    visibility: Optional[StrictStr] = Field(default=None, alias="Visibility")
    __properties: ClassVar[List[str]] = ["ChargeType", "RatePlanId", "Code", "Name", "ShortDescription", "LongDescription", "LastUpdate", "Visibility"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RatePlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if charge_type (nullable) is None
        # and model_fields_set contains the field
        if self.charge_type is None and "charge_type" in self.model_fields_set:
            _dict['ChargeType'] = None

        # set to None if rate_plan_id (nullable) is None
        # and model_fields_set contains the field
        if self.rate_plan_id is None and "rate_plan_id" in self.model_fields_set:
            _dict['RatePlanId'] = None

        # set to None if code (nullable) is None
        # and model_fields_set contains the field
        if self.code is None and "code" in self.model_fields_set:
            _dict['Code'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['Name'] = None

        # set to None if short_description (nullable) is None
        # and model_fields_set contains the field
        if self.short_description is None and "short_description" in self.model_fields_set:
            _dict['ShortDescription'] = None

        # set to None if long_description (nullable) is None
        # and model_fields_set contains the field
        if self.long_description is None and "long_description" in self.model_fields_set:
            _dict['LongDescription'] = None

        # set to None if visibility (nullable) is None
        # and model_fields_set contains the field
        if self.visibility is None and "visibility" in self.model_fields_set:
            _dict['Visibility'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RatePlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ChargeType": obj.get("ChargeType"),
            "RatePlanId": obj.get("RatePlanId"),
            "Code": obj.get("Code"),
            "Name": obj.get("Name"),
            "ShortDescription": obj.get("ShortDescription"),
            "LongDescription": obj.get("LongDescription"),
            "LastUpdate": obj.get("LastUpdate"),
            "Visibility": obj.get("Visibility")
        })
        return _obj


