# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.cancel_policy import CancelPolicy
from openapi_server.models.payment_term import PaymentTerm
from openapi_server.models.room_pictures import RoomPictures
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RoomDetails(BaseModel):
    """
    RoomDetails
    """ # noqa: E501
    room_id: Optional[StrictStr] = Field(default=None, alias="RoomId")
    room_seq: Optional[StrictInt] = Field(default=None, alias="RoomSeq")
    total_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="TotalPrice")
    offer_id: Optional[StrictStr] = Field(default=None, alias="OfferId")
    price_ws: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Price_ws")
    price_bb: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Price_bb")
    price_hb: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Price_hb")
    price_fb: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Price_fb")
    price_ai: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Price_ai")
    roomtype: Optional[StrictInt] = Field(default=None, alias="Roomtype")
    roomfree: Optional[StrictInt] = Field(default=None, alias="Roomfree")
    roommax: Optional[StrictInt] = Field(default=None, alias="Roommax")
    roommin: Optional[StrictInt] = Field(default=None, alias="Roommin")
    roomstd: Optional[StrictInt] = Field(default=None, alias="Roomstd")
    roomtitle: Optional[StrictStr] = Field(default=None, alias="Roomtitle")
    roomdesc: Optional[StrictStr] = Field(default=None, alias="Roomdesc")
    room_channel_link: Optional[StrictStr] = Field(default=None, alias="RoomChannelLink")
    total_price_string: Optional[StrictStr] = Field(default=None, alias="TotalPriceString")
    room_pictures: Optional[List[RoomPictures]] = Field(default=None, alias="RoomPictures")
    payment_term: Optional[PaymentTerm] = Field(default=None, alias="PaymentTerm")
    cancel_policy: Optional[CancelPolicy] = Field(default=None, alias="CancelPolicy")
    __properties: ClassVar[List[str]] = ["RoomId", "RoomSeq", "TotalPrice", "OfferId", "Price_ws", "Price_bb", "Price_hb", "Price_fb", "Price_ai", "Roomtype", "Roomfree", "Roommax", "Roommin", "Roomstd", "Roomtitle", "Roomdesc", "RoomChannelLink", "TotalPriceString", "RoomPictures", "PaymentTerm", "CancelPolicy"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RoomDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in room_pictures (list)
        _items = []
        if self.room_pictures:
            for _item in self.room_pictures:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RoomPictures'] = _items
        # override the default output from pydantic by calling `to_dict()` of payment_term
        if self.payment_term:
            _dict['PaymentTerm'] = self.payment_term.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cancel_policy
        if self.cancel_policy:
            _dict['CancelPolicy'] = self.cancel_policy.to_dict()
        # set to None if room_id (nullable) is None
        # and model_fields_set contains the field
        if self.room_id is None and "room_id" in self.model_fields_set:
            _dict['RoomId'] = None

        # set to None if room_seq (nullable) is None
        # and model_fields_set contains the field
        if self.room_seq is None and "room_seq" in self.model_fields_set:
            _dict['RoomSeq'] = None

        # set to None if offer_id (nullable) is None
        # and model_fields_set contains the field
        if self.offer_id is None and "offer_id" in self.model_fields_set:
            _dict['OfferId'] = None

        # set to None if price_ws (nullable) is None
        # and model_fields_set contains the field
        if self.price_ws is None and "price_ws" in self.model_fields_set:
            _dict['Price_ws'] = None

        # set to None if price_bb (nullable) is None
        # and model_fields_set contains the field
        if self.price_bb is None and "price_bb" in self.model_fields_set:
            _dict['Price_bb'] = None

        # set to None if price_hb (nullable) is None
        # and model_fields_set contains the field
        if self.price_hb is None and "price_hb" in self.model_fields_set:
            _dict['Price_hb'] = None

        # set to None if price_fb (nullable) is None
        # and model_fields_set contains the field
        if self.price_fb is None and "price_fb" in self.model_fields_set:
            _dict['Price_fb'] = None

        # set to None if price_ai (nullable) is None
        # and model_fields_set contains the field
        if self.price_ai is None and "price_ai" in self.model_fields_set:
            _dict['Price_ai'] = None

        # set to None if roomtype (nullable) is None
        # and model_fields_set contains the field
        if self.roomtype is None and "roomtype" in self.model_fields_set:
            _dict['Roomtype'] = None

        # set to None if roomfree (nullable) is None
        # and model_fields_set contains the field
        if self.roomfree is None and "roomfree" in self.model_fields_set:
            _dict['Roomfree'] = None

        # set to None if roommax (nullable) is None
        # and model_fields_set contains the field
        if self.roommax is None and "roommax" in self.model_fields_set:
            _dict['Roommax'] = None

        # set to None if roommin (nullable) is None
        # and model_fields_set contains the field
        if self.roommin is None and "roommin" in self.model_fields_set:
            _dict['Roommin'] = None

        # set to None if roomstd (nullable) is None
        # and model_fields_set contains the field
        if self.roomstd is None and "roomstd" in self.model_fields_set:
            _dict['Roomstd'] = None

        # set to None if roomtitle (nullable) is None
        # and model_fields_set contains the field
        if self.roomtitle is None and "roomtitle" in self.model_fields_set:
            _dict['Roomtitle'] = None

        # set to None if roomdesc (nullable) is None
        # and model_fields_set contains the field
        if self.roomdesc is None and "roomdesc" in self.model_fields_set:
            _dict['Roomdesc'] = None

        # set to None if room_channel_link (nullable) is None
        # and model_fields_set contains the field
        if self.room_channel_link is None and "room_channel_link" in self.model_fields_set:
            _dict['RoomChannelLink'] = None

        # set to None if total_price_string (nullable) is None
        # and model_fields_set contains the field
        if self.total_price_string is None and "total_price_string" in self.model_fields_set:
            _dict['TotalPriceString'] = None

        # set to None if room_pictures (nullable) is None
        # and model_fields_set contains the field
        if self.room_pictures is None and "room_pictures" in self.model_fields_set:
            _dict['RoomPictures'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RoomDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "RoomId": obj.get("RoomId"),
            "RoomSeq": obj.get("RoomSeq"),
            "TotalPrice": obj.get("TotalPrice"),
            "OfferId": obj.get("OfferId"),
            "Price_ws": obj.get("Price_ws"),
            "Price_bb": obj.get("Price_bb"),
            "Price_hb": obj.get("Price_hb"),
            "Price_fb": obj.get("Price_fb"),
            "Price_ai": obj.get("Price_ai"),
            "Roomtype": obj.get("Roomtype"),
            "Roomfree": obj.get("Roomfree"),
            "Roommax": obj.get("Roommax"),
            "Roommin": obj.get("Roommin"),
            "Roomstd": obj.get("Roomstd"),
            "Roomtitle": obj.get("Roomtitle"),
            "Roomdesc": obj.get("Roomdesc"),
            "RoomChannelLink": obj.get("RoomChannelLink"),
            "TotalPriceString": obj.get("TotalPriceString"),
            "RoomPictures": [RoomPictures.from_dict(_item) for _item in obj.get("RoomPictures")] if obj.get("RoomPictures") is not None else None,
            "PaymentTerm": PaymentTerm.from_dict(obj.get("PaymentTerm")) if obj.get("PaymentTerm") is not None else None,
            "CancelPolicy": CancelPolicy.from_dict(obj.get("CancelPolicy")) if obj.get("CancelPolicy") is not None else None
        })
        return _obj


