# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.measuringpoint_reduced import MeasuringpointReduced
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SnowReportBaseData(BaseModel):
    """
    SnowReportBaseData
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    rid: Optional[StrictStr] = Field(default=None, alias="RID")
    skiregion: Optional[StrictStr] = Field(default=None, alias="Skiregion")
    areaname: Optional[StrictStr] = Field(default=None, alias="Areaname")
    last_update: Optional[datetime] = Field(default=None, alias="LastUpdate")
    lang: Optional[StrictStr] = None
    ski_area_slope_km: Optional[StrictStr] = Field(default=None, alias="SkiAreaSlopeKm")
    ski_map_url: Optional[StrictStr] = Field(default=None, alias="SkiMapUrl")
    measuringpoints: Optional[List[MeasuringpointReduced]] = Field(default=None, alias="Measuringpoints")
    webcam_url: Optional[List[StrictStr]] = Field(default=None, alias="WebcamUrl")
    totalskilift: Optional[StrictStr] = None
    openskilift: Optional[StrictStr] = None
    totalskiliftkm: Optional[StrictStr] = None
    openskiliftkm: Optional[StrictStr] = None
    totalskislopes: Optional[StrictStr] = None
    openskislopes: Optional[StrictStr] = None
    totalskislopeskm: Optional[StrictStr] = None
    openskislopeskm: Optional[StrictStr] = None
    totaltracks: Optional[StrictStr] = None
    opentracks: Optional[StrictStr] = None
    totaltrackskm: Optional[StrictStr] = None
    opentrackskm: Optional[StrictStr] = None
    totalslides: Optional[StrictStr] = None
    opentslides: Optional[StrictStr] = None
    totalslideskm: Optional[StrictStr] = None
    opentslideskm: Optional[StrictStr] = None
    totaliceskating: Optional[StrictStr] = None
    openiceskating: Optional[StrictStr] = None
    contactadress: Optional[StrictStr] = None
    contacttel: Optional[StrictStr] = None
    contactcap: Optional[StrictStr] = None
    contactcity: Optional[StrictStr] = None
    contactfax: Optional[StrictStr] = None
    contactweburl: Optional[StrictStr] = None
    contactmail: Optional[StrictStr] = None
    contactlogo: Optional[StrictStr] = None
    contactgpsnorth: Optional[StrictStr] = None
    contactgpseast: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["Id", "RID", "Skiregion", "Areaname", "LastUpdate", "lang", "SkiAreaSlopeKm", "SkiMapUrl", "Measuringpoints", "WebcamUrl", "totalskilift", "openskilift", "totalskiliftkm", "openskiliftkm", "totalskislopes", "openskislopes", "totalskislopeskm", "openskislopeskm", "totaltracks", "opentracks", "totaltrackskm", "opentrackskm", "totalslides", "opentslides", "totalslideskm", "opentslideskm", "totaliceskating", "openiceskating", "contactadress", "contacttel", "contactcap", "contactcity", "contactfax", "contactweburl", "contactmail", "contactlogo", "contactgpsnorth", "contactgpseast"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SnowReportBaseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in measuringpoints (list)
        _items = []
        if self.measuringpoints:
            for _item in self.measuringpoints:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Measuringpoints'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if rid (nullable) is None
        # and model_fields_set contains the field
        if self.rid is None and "rid" in self.model_fields_set:
            _dict['RID'] = None

        # set to None if skiregion (nullable) is None
        # and model_fields_set contains the field
        if self.skiregion is None and "skiregion" in self.model_fields_set:
            _dict['Skiregion'] = None

        # set to None if areaname (nullable) is None
        # and model_fields_set contains the field
        if self.areaname is None and "areaname" in self.model_fields_set:
            _dict['Areaname'] = None

        # set to None if lang (nullable) is None
        # and model_fields_set contains the field
        if self.lang is None and "lang" in self.model_fields_set:
            _dict['lang'] = None

        # set to None if ski_area_slope_km (nullable) is None
        # and model_fields_set contains the field
        if self.ski_area_slope_km is None and "ski_area_slope_km" in self.model_fields_set:
            _dict['SkiAreaSlopeKm'] = None

        # set to None if ski_map_url (nullable) is None
        # and model_fields_set contains the field
        if self.ski_map_url is None and "ski_map_url" in self.model_fields_set:
            _dict['SkiMapUrl'] = None

        # set to None if measuringpoints (nullable) is None
        # and model_fields_set contains the field
        if self.measuringpoints is None and "measuringpoints" in self.model_fields_set:
            _dict['Measuringpoints'] = None

        # set to None if webcam_url (nullable) is None
        # and model_fields_set contains the field
        if self.webcam_url is None and "webcam_url" in self.model_fields_set:
            _dict['WebcamUrl'] = None

        # set to None if totalskilift (nullable) is None
        # and model_fields_set contains the field
        if self.totalskilift is None and "totalskilift" in self.model_fields_set:
            _dict['totalskilift'] = None

        # set to None if openskilift (nullable) is None
        # and model_fields_set contains the field
        if self.openskilift is None and "openskilift" in self.model_fields_set:
            _dict['openskilift'] = None

        # set to None if totalskiliftkm (nullable) is None
        # and model_fields_set contains the field
        if self.totalskiliftkm is None and "totalskiliftkm" in self.model_fields_set:
            _dict['totalskiliftkm'] = None

        # set to None if openskiliftkm (nullable) is None
        # and model_fields_set contains the field
        if self.openskiliftkm is None and "openskiliftkm" in self.model_fields_set:
            _dict['openskiliftkm'] = None

        # set to None if totalskislopes (nullable) is None
        # and model_fields_set contains the field
        if self.totalskislopes is None and "totalskislopes" in self.model_fields_set:
            _dict['totalskislopes'] = None

        # set to None if openskislopes (nullable) is None
        # and model_fields_set contains the field
        if self.openskislopes is None and "openskislopes" in self.model_fields_set:
            _dict['openskislopes'] = None

        # set to None if totalskislopeskm (nullable) is None
        # and model_fields_set contains the field
        if self.totalskislopeskm is None and "totalskislopeskm" in self.model_fields_set:
            _dict['totalskislopeskm'] = None

        # set to None if openskislopeskm (nullable) is None
        # and model_fields_set contains the field
        if self.openskislopeskm is None and "openskislopeskm" in self.model_fields_set:
            _dict['openskislopeskm'] = None

        # set to None if totaltracks (nullable) is None
        # and model_fields_set contains the field
        if self.totaltracks is None and "totaltracks" in self.model_fields_set:
            _dict['totaltracks'] = None

        # set to None if opentracks (nullable) is None
        # and model_fields_set contains the field
        if self.opentracks is None and "opentracks" in self.model_fields_set:
            _dict['opentracks'] = None

        # set to None if totaltrackskm (nullable) is None
        # and model_fields_set contains the field
        if self.totaltrackskm is None and "totaltrackskm" in self.model_fields_set:
            _dict['totaltrackskm'] = None

        # set to None if opentrackskm (nullable) is None
        # and model_fields_set contains the field
        if self.opentrackskm is None and "opentrackskm" in self.model_fields_set:
            _dict['opentrackskm'] = None

        # set to None if totalslides (nullable) is None
        # and model_fields_set contains the field
        if self.totalslides is None and "totalslides" in self.model_fields_set:
            _dict['totalslides'] = None

        # set to None if opentslides (nullable) is None
        # and model_fields_set contains the field
        if self.opentslides is None and "opentslides" in self.model_fields_set:
            _dict['opentslides'] = None

        # set to None if totalslideskm (nullable) is None
        # and model_fields_set contains the field
        if self.totalslideskm is None and "totalslideskm" in self.model_fields_set:
            _dict['totalslideskm'] = None

        # set to None if opentslideskm (nullable) is None
        # and model_fields_set contains the field
        if self.opentslideskm is None and "opentslideskm" in self.model_fields_set:
            _dict['opentslideskm'] = None

        # set to None if totaliceskating (nullable) is None
        # and model_fields_set contains the field
        if self.totaliceskating is None and "totaliceskating" in self.model_fields_set:
            _dict['totaliceskating'] = None

        # set to None if openiceskating (nullable) is None
        # and model_fields_set contains the field
        if self.openiceskating is None and "openiceskating" in self.model_fields_set:
            _dict['openiceskating'] = None

        # set to None if contactadress (nullable) is None
        # and model_fields_set contains the field
        if self.contactadress is None and "contactadress" in self.model_fields_set:
            _dict['contactadress'] = None

        # set to None if contacttel (nullable) is None
        # and model_fields_set contains the field
        if self.contacttel is None and "contacttel" in self.model_fields_set:
            _dict['contacttel'] = None

        # set to None if contactcap (nullable) is None
        # and model_fields_set contains the field
        if self.contactcap is None and "contactcap" in self.model_fields_set:
            _dict['contactcap'] = None

        # set to None if contactcity (nullable) is None
        # and model_fields_set contains the field
        if self.contactcity is None and "contactcity" in self.model_fields_set:
            _dict['contactcity'] = None

        # set to None if contactfax (nullable) is None
        # and model_fields_set contains the field
        if self.contactfax is None and "contactfax" in self.model_fields_set:
            _dict['contactfax'] = None

        # set to None if contactweburl (nullable) is None
        # and model_fields_set contains the field
        if self.contactweburl is None and "contactweburl" in self.model_fields_set:
            _dict['contactweburl'] = None

        # set to None if contactmail (nullable) is None
        # and model_fields_set contains the field
        if self.contactmail is None and "contactmail" in self.model_fields_set:
            _dict['contactmail'] = None

        # set to None if contactlogo (nullable) is None
        # and model_fields_set contains the field
        if self.contactlogo is None and "contactlogo" in self.model_fields_set:
            _dict['contactlogo'] = None

        # set to None if contactgpsnorth (nullable) is None
        # and model_fields_set contains the field
        if self.contactgpsnorth is None and "contactgpsnorth" in self.model_fields_set:
            _dict['contactgpsnorth'] = None

        # set to None if contactgpseast (nullable) is None
        # and model_fields_set contains the field
        if self.contactgpseast is None and "contactgpseast" in self.model_fields_set:
            _dict['contactgpseast'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SnowReportBaseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id"),
            "RID": obj.get("RID"),
            "Skiregion": obj.get("Skiregion"),
            "Areaname": obj.get("Areaname"),
            "LastUpdate": obj.get("LastUpdate"),
            "lang": obj.get("lang"),
            "SkiAreaSlopeKm": obj.get("SkiAreaSlopeKm"),
            "SkiMapUrl": obj.get("SkiMapUrl"),
            "Measuringpoints": [MeasuringpointReduced.from_dict(_item) for _item in obj.get("Measuringpoints")] if obj.get("Measuringpoints") is not None else None,
            "WebcamUrl": obj.get("WebcamUrl"),
            "totalskilift": obj.get("totalskilift"),
            "openskilift": obj.get("openskilift"),
            "totalskiliftkm": obj.get("totalskiliftkm"),
            "openskiliftkm": obj.get("openskiliftkm"),
            "totalskislopes": obj.get("totalskislopes"),
            "openskislopes": obj.get("openskislopes"),
            "totalskislopeskm": obj.get("totalskislopeskm"),
            "openskislopeskm": obj.get("openskislopeskm"),
            "totaltracks": obj.get("totaltracks"),
            "opentracks": obj.get("opentracks"),
            "totaltrackskm": obj.get("totaltrackskm"),
            "opentrackskm": obj.get("opentrackskm"),
            "totalslides": obj.get("totalslides"),
            "opentslides": obj.get("opentslides"),
            "totalslideskm": obj.get("totalslideskm"),
            "opentslideskm": obj.get("opentslideskm"),
            "totaliceskating": obj.get("totaliceskating"),
            "openiceskating": obj.get("openiceskating"),
            "contactadress": obj.get("contactadress"),
            "contacttel": obj.get("contacttel"),
            "contactcap": obj.get("contactcap"),
            "contactcity": obj.get("contactcity"),
            "contactfax": obj.get("contactfax"),
            "contactweburl": obj.get("contactweburl"),
            "contactmail": obj.get("contactmail"),
            "contactlogo": obj.get("contactlogo"),
            "contactgpsnorth": obj.get("contactgpsnorth"),
            "contactgpseast": obj.get("contactgpseast")
        })
        return _obj


