# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.metadata import Metadata
from openapi_server.models.sync_data_config import SyncDataConfig
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SourceLinked(BaseModel):
    """
    SourceLinked
    """ # noqa: E501
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    var_self: Optional[StrictStr] = Field(default=None, description="generated field", alias="Self")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    key: Optional[StrictStr] = Field(default=None, alias="Key")
    name: Optional[Dict[str, StrictStr]] = Field(default=None, alias="Name")
    description: Optional[Dict[str, StrictStr]] = Field(default=None, alias="Description")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    url: Optional[StrictStr] = Field(default=None, alias="Url")
    interfaces: Optional[List[StrictStr]] = Field(default=None, description="Interfaces that are offered by the source", alias="Interfaces")
    types: Optional[List[StrictStr]] = Field(default=None, alias="Types")
    sync_data_config: Optional[List[SyncDataConfig]] = Field(default=None, alias="SyncDataConfig")
    __properties: ClassVar[List[str]] = ["_Meta", "Self", "LicenseInfo", "Id", "Key", "Name", "Description", "FirstImport", "LastChange", "Url", "Interfaces", "Types", "SyncDataConfig"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SourceLinked from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_self",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sync_data_config (list)
        _items = []
        if self.sync_data_config:
            for _item in self.sync_data_config:
                if _item:
                    _items.append(_item.to_dict())
            _dict['SyncDataConfig'] = _items
        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if key (nullable) is None
        # and model_fields_set contains the field
        if self.key is None and "key" in self.model_fields_set:
            _dict['Key'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['Name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['Description'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['Url'] = None

        # set to None if interfaces (nullable) is None
        # and model_fields_set contains the field
        if self.interfaces is None and "interfaces" in self.model_fields_set:
            _dict['Interfaces'] = None

        # set to None if types (nullable) is None
        # and model_fields_set contains the field
        if self.types is None and "types" in self.model_fields_set:
            _dict['Types'] = None

        # set to None if sync_data_config (nullable) is None
        # and model_fields_set contains the field
        if self.sync_data_config is None and "sync_data_config" in self.model_fields_set:
            _dict['SyncDataConfig'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SourceLinked from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "Self": obj.get("Self"),
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "Id": obj.get("Id"),
            "Key": obj.get("Key"),
            "Name": obj.get("Name"),
            "Description": obj.get("Description"),
            "FirstImport": obj.get("FirstImport"),
            "LastChange": obj.get("LastChange"),
            "Url": obj.get("Url"),
            "Interfaces": obj.get("Interfaces"),
            "Types": obj.get("Types"),
            "SyncDataConfig": [SyncDataConfig.from_dict(_item) for _item in obj.get("SyncDataConfig")] if obj.get("SyncDataConfig") is not None else None
        })
        return _obj


