# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SuedtirolWeinCompanyDataProperties(BaseModel):
    """
    SuedtirolWeinCompanyDataProperties
    """ # noqa: E501
    openingtimes_wineshop: Optional[Dict[str, StrictStr]] = Field(default=None, alias="OpeningtimesWineshop")
    openingtimes_guides: Optional[Dict[str, StrictStr]] = Field(default=None, alias="OpeningtimesGuides")
    openingtimes_gastronomie: Optional[Dict[str, StrictStr]] = Field(default=None, alias="OpeningtimesGastronomie")
    company_holiday: Optional[Dict[str, StrictStr]] = Field(default=None, alias="CompanyHoliday")
    has_visits: Optional[StrictBool] = Field(default=None, alias="HasVisits")
    has_overnights: Optional[StrictBool] = Field(default=None, alias="HasOvernights")
    has_biowine: Optional[StrictBool] = Field(default=None, alias="HasBiowine")
    has_accommodation: Optional[StrictBool] = Field(default=None, alias="HasAccommodation")
    is_vinum_hotel: Optional[StrictBool] = Field(default=None, alias="IsVinumHotel")
    is_anteprima: Optional[StrictBool] = Field(default=None, alias="IsAnteprima")
    is_wine_stories: Optional[StrictBool] = Field(default=None, alias="IsWineStories")
    is_wine_summit: Optional[StrictBool] = Field(default=None, alias="IsWineSummit")
    is_sparkling_wineassociation: Optional[StrictBool] = Field(default=None, alias="IsSparklingWineassociation")
    is_winery: Optional[StrictBool] = Field(default=None, alias="IsWinery")
    has_onlineshop: Optional[StrictBool] = Field(default=None, alias="HasOnlineshop")
    has_deliveryservice: Optional[StrictBool] = Field(default=None, alias="HasDeliveryservice")
    has_direct_sales: Optional[StrictBool] = Field(default=None, alias="HasDirectSales")
    is_skyalps_partner: Optional[StrictBool] = Field(default=None, alias="IsSkyalpsPartner")
    wines: Optional[List[StrictStr]] = Field(default=None, alias="Wines")
    online_shopurl: Optional[Dict[str, StrictStr]] = Field(default=None, alias="OnlineShopurl")
    delivery_service_url: Optional[Dict[str, StrictStr]] = Field(default=None, alias="DeliveryServiceUrl")
    h1: Optional[Dict[str, StrictStr]] = Field(default=None, alias="H1")
    h2: Optional[Dict[str, StrictStr]] = Field(default=None, alias="H2")
    quote: Optional[Dict[str, StrictStr]] = Field(default=None, alias="Quote")
    quote_author: Optional[Dict[str, StrictStr]] = Field(default=None, alias="QuoteAuthor")
    description_sparkling_wineproducer: Optional[Dict[str, StrictStr]] = Field(default=None, alias="DescriptionSparklingWineproducer")
    h1_sparkling_wineproducer: Optional[Dict[str, StrictStr]] = Field(default=None, alias="H1SparklingWineproducer")
    h2_sparkling_wineproducer: Optional[Dict[str, StrictStr]] = Field(default=None, alias="H2SparklingWineproducer")
    image_sparkling_wineproducer: Optional[StrictStr] = Field(default=None, alias="ImageSparklingWineproducer")
    socials_facebook: Optional[StrictStr] = Field(default=None, alias="SocialsFacebook")
    socials_instagram: Optional[StrictStr] = Field(default=None, alias="SocialsInstagram")
    socials_linked_in: Optional[StrictStr] = Field(default=None, alias="SocialsLinkedIn")
    socials_pinterest: Optional[StrictStr] = Field(default=None, alias="SocialsPinterest")
    socials_tiktok: Optional[StrictStr] = Field(default=None, alias="SocialsTiktok")
    socials_youtube: Optional[StrictStr] = Field(default=None, alias="SocialsYoutube")
    socials_twitter: Optional[StrictStr] = Field(default=None, alias="SocialsTwitter")
    __properties: ClassVar[List[str]] = ["OpeningtimesWineshop", "OpeningtimesGuides", "OpeningtimesGastronomie", "CompanyHoliday", "HasVisits", "HasOvernights", "HasBiowine", "HasAccommodation", "IsVinumHotel", "IsAnteprima", "IsWineStories", "IsWineSummit", "IsSparklingWineassociation", "IsWinery", "HasOnlineshop", "HasDeliveryservice", "HasDirectSales", "IsSkyalpsPartner", "Wines", "OnlineShopurl", "DeliveryServiceUrl", "H1", "H2", "Quote", "QuoteAuthor", "DescriptionSparklingWineproducer", "H1SparklingWineproducer", "H2SparklingWineproducer", "ImageSparklingWineproducer", "SocialsFacebook", "SocialsInstagram", "SocialsLinkedIn", "SocialsPinterest", "SocialsTiktok", "SocialsYoutube", "SocialsTwitter"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SuedtirolWeinCompanyDataProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if openingtimes_wineshop (nullable) is None
        # and model_fields_set contains the field
        if self.openingtimes_wineshop is None and "openingtimes_wineshop" in self.model_fields_set:
            _dict['OpeningtimesWineshop'] = None

        # set to None if openingtimes_guides (nullable) is None
        # and model_fields_set contains the field
        if self.openingtimes_guides is None and "openingtimes_guides" in self.model_fields_set:
            _dict['OpeningtimesGuides'] = None

        # set to None if openingtimes_gastronomie (nullable) is None
        # and model_fields_set contains the field
        if self.openingtimes_gastronomie is None and "openingtimes_gastronomie" in self.model_fields_set:
            _dict['OpeningtimesGastronomie'] = None

        # set to None if company_holiday (nullable) is None
        # and model_fields_set contains the field
        if self.company_holiday is None and "company_holiday" in self.model_fields_set:
            _dict['CompanyHoliday'] = None

        # set to None if has_visits (nullable) is None
        # and model_fields_set contains the field
        if self.has_visits is None and "has_visits" in self.model_fields_set:
            _dict['HasVisits'] = None

        # set to None if has_overnights (nullable) is None
        # and model_fields_set contains the field
        if self.has_overnights is None and "has_overnights" in self.model_fields_set:
            _dict['HasOvernights'] = None

        # set to None if has_biowine (nullable) is None
        # and model_fields_set contains the field
        if self.has_biowine is None and "has_biowine" in self.model_fields_set:
            _dict['HasBiowine'] = None

        # set to None if has_accommodation (nullable) is None
        # and model_fields_set contains the field
        if self.has_accommodation is None and "has_accommodation" in self.model_fields_set:
            _dict['HasAccommodation'] = None

        # set to None if is_vinum_hotel (nullable) is None
        # and model_fields_set contains the field
        if self.is_vinum_hotel is None and "is_vinum_hotel" in self.model_fields_set:
            _dict['IsVinumHotel'] = None

        # set to None if is_anteprima (nullable) is None
        # and model_fields_set contains the field
        if self.is_anteprima is None and "is_anteprima" in self.model_fields_set:
            _dict['IsAnteprima'] = None

        # set to None if is_wine_stories (nullable) is None
        # and model_fields_set contains the field
        if self.is_wine_stories is None and "is_wine_stories" in self.model_fields_set:
            _dict['IsWineStories'] = None

        # set to None if is_wine_summit (nullable) is None
        # and model_fields_set contains the field
        if self.is_wine_summit is None and "is_wine_summit" in self.model_fields_set:
            _dict['IsWineSummit'] = None

        # set to None if is_sparkling_wineassociation (nullable) is None
        # and model_fields_set contains the field
        if self.is_sparkling_wineassociation is None and "is_sparkling_wineassociation" in self.model_fields_set:
            _dict['IsSparklingWineassociation'] = None

        # set to None if is_winery (nullable) is None
        # and model_fields_set contains the field
        if self.is_winery is None and "is_winery" in self.model_fields_set:
            _dict['IsWinery'] = None

        # set to None if has_onlineshop (nullable) is None
        # and model_fields_set contains the field
        if self.has_onlineshop is None and "has_onlineshop" in self.model_fields_set:
            _dict['HasOnlineshop'] = None

        # set to None if has_deliveryservice (nullable) is None
        # and model_fields_set contains the field
        if self.has_deliveryservice is None and "has_deliveryservice" in self.model_fields_set:
            _dict['HasDeliveryservice'] = None

        # set to None if has_direct_sales (nullable) is None
        # and model_fields_set contains the field
        if self.has_direct_sales is None and "has_direct_sales" in self.model_fields_set:
            _dict['HasDirectSales'] = None

        # set to None if is_skyalps_partner (nullable) is None
        # and model_fields_set contains the field
        if self.is_skyalps_partner is None and "is_skyalps_partner" in self.model_fields_set:
            _dict['IsSkyalpsPartner'] = None

        # set to None if wines (nullable) is None
        # and model_fields_set contains the field
        if self.wines is None and "wines" in self.model_fields_set:
            _dict['Wines'] = None

        # set to None if online_shopurl (nullable) is None
        # and model_fields_set contains the field
        if self.online_shopurl is None and "online_shopurl" in self.model_fields_set:
            _dict['OnlineShopurl'] = None

        # set to None if delivery_service_url (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_service_url is None and "delivery_service_url" in self.model_fields_set:
            _dict['DeliveryServiceUrl'] = None

        # set to None if h1 (nullable) is None
        # and model_fields_set contains the field
        if self.h1 is None and "h1" in self.model_fields_set:
            _dict['H1'] = None

        # set to None if h2 (nullable) is None
        # and model_fields_set contains the field
        if self.h2 is None and "h2" in self.model_fields_set:
            _dict['H2'] = None

        # set to None if quote (nullable) is None
        # and model_fields_set contains the field
        if self.quote is None and "quote" in self.model_fields_set:
            _dict['Quote'] = None

        # set to None if quote_author (nullable) is None
        # and model_fields_set contains the field
        if self.quote_author is None and "quote_author" in self.model_fields_set:
            _dict['QuoteAuthor'] = None

        # set to None if description_sparkling_wineproducer (nullable) is None
        # and model_fields_set contains the field
        if self.description_sparkling_wineproducer is None and "description_sparkling_wineproducer" in self.model_fields_set:
            _dict['DescriptionSparklingWineproducer'] = None

        # set to None if h1_sparkling_wineproducer (nullable) is None
        # and model_fields_set contains the field
        if self.h1_sparkling_wineproducer is None and "h1_sparkling_wineproducer" in self.model_fields_set:
            _dict['H1SparklingWineproducer'] = None

        # set to None if h2_sparkling_wineproducer (nullable) is None
        # and model_fields_set contains the field
        if self.h2_sparkling_wineproducer is None and "h2_sparkling_wineproducer" in self.model_fields_set:
            _dict['H2SparklingWineproducer'] = None

        # set to None if image_sparkling_wineproducer (nullable) is None
        # and model_fields_set contains the field
        if self.image_sparkling_wineproducer is None and "image_sparkling_wineproducer" in self.model_fields_set:
            _dict['ImageSparklingWineproducer'] = None

        # set to None if socials_facebook (nullable) is None
        # and model_fields_set contains the field
        if self.socials_facebook is None and "socials_facebook" in self.model_fields_set:
            _dict['SocialsFacebook'] = None

        # set to None if socials_instagram (nullable) is None
        # and model_fields_set contains the field
        if self.socials_instagram is None and "socials_instagram" in self.model_fields_set:
            _dict['SocialsInstagram'] = None

        # set to None if socials_linked_in (nullable) is None
        # and model_fields_set contains the field
        if self.socials_linked_in is None and "socials_linked_in" in self.model_fields_set:
            _dict['SocialsLinkedIn'] = None

        # set to None if socials_pinterest (nullable) is None
        # and model_fields_set contains the field
        if self.socials_pinterest is None and "socials_pinterest" in self.model_fields_set:
            _dict['SocialsPinterest'] = None

        # set to None if socials_tiktok (nullable) is None
        # and model_fields_set contains the field
        if self.socials_tiktok is None and "socials_tiktok" in self.model_fields_set:
            _dict['SocialsTiktok'] = None

        # set to None if socials_youtube (nullable) is None
        # and model_fields_set contains the field
        if self.socials_youtube is None and "socials_youtube" in self.model_fields_set:
            _dict['SocialsYoutube'] = None

        # set to None if socials_twitter (nullable) is None
        # and model_fields_set contains the field
        if self.socials_twitter is None and "socials_twitter" in self.model_fields_set:
            _dict['SocialsTwitter'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SuedtirolWeinCompanyDataProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "OpeningtimesWineshop": obj.get("OpeningtimesWineshop"),
            "OpeningtimesGuides": obj.get("OpeningtimesGuides"),
            "OpeningtimesGastronomie": obj.get("OpeningtimesGastronomie"),
            "CompanyHoliday": obj.get("CompanyHoliday"),
            "HasVisits": obj.get("HasVisits"),
            "HasOvernights": obj.get("HasOvernights"),
            "HasBiowine": obj.get("HasBiowine"),
            "HasAccommodation": obj.get("HasAccommodation"),
            "IsVinumHotel": obj.get("IsVinumHotel"),
            "IsAnteprima": obj.get("IsAnteprima"),
            "IsWineStories": obj.get("IsWineStories"),
            "IsWineSummit": obj.get("IsWineSummit"),
            "IsSparklingWineassociation": obj.get("IsSparklingWineassociation"),
            "IsWinery": obj.get("IsWinery"),
            "HasOnlineshop": obj.get("HasOnlineshop"),
            "HasDeliveryservice": obj.get("HasDeliveryservice"),
            "HasDirectSales": obj.get("HasDirectSales"),
            "IsSkyalpsPartner": obj.get("IsSkyalpsPartner"),
            "Wines": obj.get("Wines"),
            "OnlineShopurl": obj.get("OnlineShopurl"),
            "DeliveryServiceUrl": obj.get("DeliveryServiceUrl"),
            "H1": obj.get("H1"),
            "H2": obj.get("H2"),
            "Quote": obj.get("Quote"),
            "QuoteAuthor": obj.get("QuoteAuthor"),
            "DescriptionSparklingWineproducer": obj.get("DescriptionSparklingWineproducer"),
            "H1SparklingWineproducer": obj.get("H1SparklingWineproducer"),
            "H2SparklingWineproducer": obj.get("H2SparklingWineproducer"),
            "ImageSparklingWineproducer": obj.get("ImageSparklingWineproducer"),
            "SocialsFacebook": obj.get("SocialsFacebook"),
            "SocialsInstagram": obj.get("SocialsInstagram"),
            "SocialsLinkedIn": obj.get("SocialsLinkedIn"),
            "SocialsPinterest": obj.get("SocialsPinterest"),
            "SocialsTiktok": obj.get("SocialsTiktok"),
            "SocialsYoutube": obj.get("SocialsYoutube"),
            "SocialsTwitter": obj.get("SocialsTwitter")
        })
        return _obj


