# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.image_gallery import ImageGallery
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.metadata import Metadata
from openapi_server.models.tags import Tags
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TourismMetaData(BaseModel):
    """
    TourismMetaData
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    var_self: Optional[StrictStr] = Field(default=None, alias="Self")
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    base_url: Optional[StrictStr] = Field(default=None, description="Base Url of the Api", alias="BaseUrl")
    api_filter: Optional[List[StrictStr]] = Field(default=None, description="optional Filter for the dataset", alias="ApiFilter")
    path_param: List[StrictStr] = Field(alias="PathParam")
    api_url: Optional[StrictStr] = Field(default=None, description="Full Api Url generated from BaseUrl, PathParam and ApiFilter", alias="ApiUrl")
    odh_type: Optional[StrictStr] = Field(default=None, description="Obsolete use Type", alias="OdhType")
    type: Optional[StrictStr] = Field(default=None, description="Optional _Meta.Type of the dataset (valid for the content domain)", alias="Type")
    swagger_url: Optional[StrictStr] = Field(default=None, description="Swagger Url where the api call is described", alias="SwaggerUrl")
    deprecated: Optional[StrictBool] = Field(default=None, alias="Deprecated")
    shortname: StrictStr = Field(alias="Shortname")
    sources: Optional[List[StrictStr]] = Field(default=None, description="Sources (_Meta.Source) of the data (valid for the content domain)", alias="Sources")
    record_count: Optional[Dict[str, StrictInt]] = Field(default=None, alias="RecordCount")
    output: Optional[Dict[str, StrictStr]] = Field(default=None, description="Content Types the Api returns", alias="Output")
    api_description: Optional[Dict[str, StrictStr]] = Field(default=None, description="Description of the dataset and api", alias="ApiDescription")
    published_on: Optional[List[StrictStr]] = Field(default=None, alias="PublishedOn")
    api_access: Optional[Dict[str, StrictStr]] = Field(default=None, alias="ApiAccess")
    image_gallery: Optional[List[ImageGallery]] = Field(default=None, alias="ImageGallery")
    dataspace: Optional[StrictStr] = Field(default=None, description="Dataspace, semantic description of the domain the dataset belongs to", alias="Dataspace")
    category: Optional[List[StrictStr]] = Field(default=None, alias="Category")
    data_provider: Optional[List[StrictStr]] = Field(default=None, description="Data Provider of the dataset", alias="DataProvider")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    api_type: Optional[StrictStr] = Field(default=None, description="Technical Domain of the api, content/timeseries", alias="ApiType")
    dataset_licenses: Optional[List[StrictStr]] = Field(default=None, description="Array containing all Licenses used in the dataset", alias="DatasetLicenses")
    meta_title: Optional[Dict[str, StrictStr]] = Field(default=None, description="Meta Title for SEO", alias="MetaTitle")
    meta_description: Optional[Dict[str, StrictStr]] = Field(default=None, description="Meta Description for SEO", alias="MetaDescription")
    tags: Optional[List[Tags]] = Field(default=None, alias="Tags")
    tag_ids: Optional[List[StrictStr]] = Field(default=None, description="Tag Ids", alias="TagIds")
    __properties: ClassVar[List[str]] = ["Id", "Self", "_Meta", "FirstImport", "LastChange", "BaseUrl", "ApiFilter", "PathParam", "ApiUrl", "OdhType", "Type", "SwaggerUrl", "Deprecated", "Shortname", "Sources", "RecordCount", "Output", "ApiDescription", "PublishedOn", "ApiAccess", "ImageGallery", "Dataspace", "Category", "DataProvider", "LicenseInfo", "ApiType", "DatasetLicenses", "MetaTitle", "MetaDescription", "Tags", "TagIds"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TourismMetaData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_self",
                "api_url",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in image_gallery (list)
        _items = []
        if self.image_gallery:
            for _item in self.image_gallery:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ImageGallery'] = _items
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Tags'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if base_url (nullable) is None
        # and model_fields_set contains the field
        if self.base_url is None and "base_url" in self.model_fields_set:
            _dict['BaseUrl'] = None

        # set to None if api_filter (nullable) is None
        # and model_fields_set contains the field
        if self.api_filter is None and "api_filter" in self.model_fields_set:
            _dict['ApiFilter'] = None

        # set to None if api_url (nullable) is None
        # and model_fields_set contains the field
        if self.api_url is None and "api_url" in self.model_fields_set:
            _dict['ApiUrl'] = None

        # set to None if odh_type (nullable) is None
        # and model_fields_set contains the field
        if self.odh_type is None and "odh_type" in self.model_fields_set:
            _dict['OdhType'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['Type'] = None

        # set to None if swagger_url (nullable) is None
        # and model_fields_set contains the field
        if self.swagger_url is None and "swagger_url" in self.model_fields_set:
            _dict['SwaggerUrl'] = None

        # set to None if sources (nullable) is None
        # and model_fields_set contains the field
        if self.sources is None and "sources" in self.model_fields_set:
            _dict['Sources'] = None

        # set to None if record_count (nullable) is None
        # and model_fields_set contains the field
        if self.record_count is None and "record_count" in self.model_fields_set:
            _dict['RecordCount'] = None

        # set to None if output (nullable) is None
        # and model_fields_set contains the field
        if self.output is None and "output" in self.model_fields_set:
            _dict['Output'] = None

        # set to None if api_description (nullable) is None
        # and model_fields_set contains the field
        if self.api_description is None and "api_description" in self.model_fields_set:
            _dict['ApiDescription'] = None

        # set to None if published_on (nullable) is None
        # and model_fields_set contains the field
        if self.published_on is None and "published_on" in self.model_fields_set:
            _dict['PublishedOn'] = None

        # set to None if api_access (nullable) is None
        # and model_fields_set contains the field
        if self.api_access is None and "api_access" in self.model_fields_set:
            _dict['ApiAccess'] = None

        # set to None if image_gallery (nullable) is None
        # and model_fields_set contains the field
        if self.image_gallery is None and "image_gallery" in self.model_fields_set:
            _dict['ImageGallery'] = None

        # set to None if dataspace (nullable) is None
        # and model_fields_set contains the field
        if self.dataspace is None and "dataspace" in self.model_fields_set:
            _dict['Dataspace'] = None

        # set to None if category (nullable) is None
        # and model_fields_set contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict['Category'] = None

        # set to None if data_provider (nullable) is None
        # and model_fields_set contains the field
        if self.data_provider is None and "data_provider" in self.model_fields_set:
            _dict['DataProvider'] = None

        # set to None if api_type (nullable) is None
        # and model_fields_set contains the field
        if self.api_type is None and "api_type" in self.model_fields_set:
            _dict['ApiType'] = None

        # set to None if dataset_licenses (nullable) is None
        # and model_fields_set contains the field
        if self.dataset_licenses is None and "dataset_licenses" in self.model_fields_set:
            _dict['DatasetLicenses'] = None

        # set to None if meta_title (nullable) is None
        # and model_fields_set contains the field
        if self.meta_title is None and "meta_title" in self.model_fields_set:
            _dict['MetaTitle'] = None

        # set to None if meta_description (nullable) is None
        # and model_fields_set contains the field
        if self.meta_description is None and "meta_description" in self.model_fields_set:
            _dict['MetaDescription'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['Tags'] = None

        # set to None if tag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.tag_ids is None and "tag_ids" in self.model_fields_set:
            _dict['TagIds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TourismMetaData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id"),
            "Self": obj.get("Self"),
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "FirstImport": obj.get("FirstImport"),
            "LastChange": obj.get("LastChange"),
            "BaseUrl": obj.get("BaseUrl"),
            "ApiFilter": obj.get("ApiFilter"),
            "PathParam": obj.get("PathParam"),
            "ApiUrl": obj.get("ApiUrl"),
            "OdhType": obj.get("OdhType"),
            "Type": obj.get("Type"),
            "SwaggerUrl": obj.get("SwaggerUrl"),
            "Deprecated": obj.get("Deprecated"),
            "Shortname": obj.get("Shortname"),
            "Sources": obj.get("Sources"),
            "RecordCount": obj.get("RecordCount"),
            "Output": obj.get("Output"),
            "ApiDescription": obj.get("ApiDescription"),
            "PublishedOn": obj.get("PublishedOn"),
            "ApiAccess": obj.get("ApiAccess"),
            "ImageGallery": [ImageGallery.from_dict(_item) for _item in obj.get("ImageGallery")] if obj.get("ImageGallery") is not None else None,
            "Dataspace": obj.get("Dataspace"),
            "Category": obj.get("Category"),
            "DataProvider": obj.get("DataProvider"),
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "ApiType": obj.get("ApiType"),
            "DatasetLicenses": obj.get("DatasetLicenses"),
            "MetaTitle": obj.get("MetaTitle"),
            "MetaDescription": obj.get("MetaDescription"),
            "Tags": [Tags.from_dict(_item) for _item in obj.get("Tags")] if obj.get("Tags") is not None else None,
            "TagIds": obj.get("TagIds")
        })
        return _obj


