# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.update_history import UpdateHistory
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UpdateInfo(BaseModel):
    """
    UpdateInfo
    """ # noqa: E501
    updated_by: Optional[StrictStr] = Field(default=None, alias="UpdatedBy")
    update_source: Optional[StrictStr] = Field(default=None, alias="UpdateSource")
    update_history: Optional[List[UpdateHistory]] = Field(default=None, alias="UpdateHistory")
    __properties: ClassVar[List[str]] = ["UpdatedBy", "UpdateSource", "UpdateHistory"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpdateInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in update_history (list)
        _items = []
        if self.update_history:
            for _item in self.update_history:
                if _item:
                    _items.append(_item.to_dict())
            _dict['UpdateHistory'] = _items
        # set to None if updated_by (nullable) is None
        # and model_fields_set contains the field
        if self.updated_by is None and "updated_by" in self.model_fields_set:
            _dict['UpdatedBy'] = None

        # set to None if update_source (nullable) is None
        # and model_fields_set contains the field
        if self.update_source is None and "update_source" in self.model_fields_set:
            _dict['UpdateSource'] = None

        # set to None if update_history (nullable) is None
        # and model_fields_set contains the field
        if self.update_history is None and "update_history" in self.model_fields_set:
            _dict['UpdateHistory'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UpdateInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "UpdatedBy": obj.get("UpdatedBy"),
            "UpdateSource": obj.get("UpdateSource"),
            "UpdateHistory": [UpdateHistory.from_dict(_item) for _item in obj.get("UpdateHistory")] if obj.get("UpdateHistory") is not None else None
        })
        return _obj


