# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.detail import Detail
from openapi_server.models.image_gallery import ImageGallery
from openapi_server.models.tags import Tags
from openapi_server.models.venue_room_properties import VenueRoomProperties
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class VenueRoomDetailsV2(BaseModel):
    """
    VenueRoomDetailsV2
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    shortname: Optional[StrictStr] = Field(default=None, alias="Shortname")
    tag_ids: Optional[List[StrictStr]] = Field(default=None, alias="TagIds")
    tags: Optional[List[Tags]] = Field(default=None, alias="Tags")
    detail: Optional[Dict[str, Detail]] = Field(default=None, alias="Detail")
    image_gallery: Optional[List[ImageGallery]] = Field(default=None, alias="ImageGallery")
    venue_room_properties: Optional[VenueRoomProperties] = Field(default=None, alias="VenueRoomProperties")
    placement: Optional[StrictStr] = Field(default=None, alias="Placement")
    __properties: ClassVar[List[str]] = ["Id", "Shortname", "TagIds", "Tags", "Detail", "ImageGallery", "VenueRoomProperties", "Placement"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VenueRoomDetailsV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in detail (dict)
        _field_dict = {}
        if self.detail:
            for _key in self.detail:
                if self.detail[_key]:
                    _field_dict[_key] = self.detail[_key].to_dict()
            _dict['Detail'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in image_gallery (list)
        _items = []
        if self.image_gallery:
            for _item in self.image_gallery:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ImageGallery'] = _items
        # override the default output from pydantic by calling `to_dict()` of venue_room_properties
        if self.venue_room_properties:
            _dict['VenueRoomProperties'] = self.venue_room_properties.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['Shortname'] = None

        # set to None if tag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.tag_ids is None and "tag_ids" in self.model_fields_set:
            _dict['TagIds'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['Tags'] = None

        # set to None if detail (nullable) is None
        # and model_fields_set contains the field
        if self.detail is None and "detail" in self.model_fields_set:
            _dict['Detail'] = None

        # set to None if image_gallery (nullable) is None
        # and model_fields_set contains the field
        if self.image_gallery is None and "image_gallery" in self.model_fields_set:
            _dict['ImageGallery'] = None

        # set to None if placement (nullable) is None
        # and model_fields_set contains the field
        if self.placement is None and "placement" in self.model_fields_set:
            _dict['Placement'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of VenueRoomDetailsV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id"),
            "Shortname": obj.get("Shortname"),
            "TagIds": obj.get("TagIds"),
            "Tags": [Tags.from_dict(_item) for _item in obj.get("Tags")] if obj.get("Tags") is not None else None,
            "Detail": dict(
                (_k, Detail.from_dict(_v))
                for _k, _v in obj.get("Detail").items()
            )
            if obj.get("Detail") is not None
            else None,
            "ImageGallery": [ImageGallery.from_dict(_item) for _item in obj.get("ImageGallery")] if obj.get("ImageGallery") is not None else None,
            "VenueRoomProperties": VenueRoomProperties.from_dict(obj.get("VenueRoomProperties")) if obj.get("VenueRoomProperties") is not None else None,
            "Placement": obj.get("Placement")
        })
        return _obj


