# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class VenueRoomProperties(BaseModel):
    """
    VenueRoomProperties
    """ # noqa: E501
    square_meters: Optional[StrictInt] = Field(default=None, alias="SquareMeters")
    room_width_in_meters: Optional[StrictInt] = Field(default=None, alias="RoomWidthInMeters")
    room_height_in_centimeters: Optional[StrictInt] = Field(default=None, alias="RoomHeightInCentimeters")
    room_depth_in_meters: Optional[StrictInt] = Field(default=None, alias="RoomDepthInMeters")
    door_width_in_centimeters: Optional[StrictInt] = Field(default=None, alias="DoorWidthInCentimeters")
    door_height_in_centimeters: Optional[StrictInt] = Field(default=None, alias="DoorHeightInCentimeters")
    __properties: ClassVar[List[str]] = ["SquareMeters", "RoomWidthInMeters", "RoomHeightInCentimeters", "RoomDepthInMeters", "DoorWidthInCentimeters", "DoorHeightInCentimeters"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VenueRoomProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if square_meters (nullable) is None
        # and model_fields_set contains the field
        if self.square_meters is None and "square_meters" in self.model_fields_set:
            _dict['SquareMeters'] = None

        # set to None if room_width_in_meters (nullable) is None
        # and model_fields_set contains the field
        if self.room_width_in_meters is None and "room_width_in_meters" in self.model_fields_set:
            _dict['RoomWidthInMeters'] = None

        # set to None if room_height_in_centimeters (nullable) is None
        # and model_fields_set contains the field
        if self.room_height_in_centimeters is None and "room_height_in_centimeters" in self.model_fields_set:
            _dict['RoomHeightInCentimeters'] = None

        # set to None if room_depth_in_meters (nullable) is None
        # and model_fields_set contains the field
        if self.room_depth_in_meters is None and "room_depth_in_meters" in self.model_fields_set:
            _dict['RoomDepthInMeters'] = None

        # set to None if door_width_in_centimeters (nullable) is None
        # and model_fields_set contains the field
        if self.door_width_in_centimeters is None and "door_width_in_centimeters" in self.model_fields_set:
            _dict['DoorWidthInCentimeters'] = None

        # set to None if door_height_in_centimeters (nullable) is None
        # and model_fields_set contains the field
        if self.door_height_in_centimeters is None and "door_height_in_centimeters" in self.model_fields_set:
            _dict['DoorHeightInCentimeters'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of VenueRoomProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "SquareMeters": obj.get("SquareMeters"),
            "RoomWidthInMeters": obj.get("RoomWidthInMeters"),
            "RoomHeightInCentimeters": obj.get("RoomHeightInCentimeters"),
            "RoomDepthInMeters": obj.get("RoomDepthInMeters"),
            "DoorWidthInCentimeters": obj.get("DoorWidthInCentimeters"),
            "DoorHeightInCentimeters": obj.get("DoorHeightInCentimeters")
        })
        return _obj


