# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.announcement_additional_properties import AnnouncementAdditionalProperties
from openapi_server.models.contact_infos import ContactInfos
from openapi_server.models.detail import Detail
from openapi_server.models.distance_info import DistanceInfo
from openapi_server.models.gps_info import GpsInfo
from openapi_server.models.image_gallery import ImageGallery
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.location_info_linked import LocationInfoLinked
from openapi_server.models.metadata import Metadata
from openapi_server.models.operation_schedule import OperationSchedule
from openapi_server.models.related_content import RelatedContent
from openapi_server.models.tags import Tags
from openapi_server.models.venue_room_details_v2 import VenueRoomDetailsV2
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class VenueV2(BaseModel):
    """
    VenueV2
    """ # noqa: E501
    active: Optional[StrictBool] = Field(default=None, alias="Active")
    gps_info: Optional[List[GpsInfo]] = Field(default=None, alias="GpsInfo")
    gps_points: Optional[Dict[str, GpsInfo]] = Field(default=None, description="generated field", alias="GpsPoints")
    detail: Optional[Dict[str, Detail]] = Field(default=None, alias="Detail")
    contact_infos: Optional[Dict[str, ContactInfos]] = Field(default=None, alias="ContactInfos")
    image_gallery: Optional[List[ImageGallery]] = Field(default=None, alias="ImageGallery")
    published_on: Optional[List[StrictStr]] = Field(default=None, alias="PublishedOn")
    distance_info: Optional[DistanceInfo] = Field(default=None, alias="DistanceInfo")
    operation_schedule: Optional[List[OperationSchedule]] = Field(default=None, alias="OperationSchedule")
    var_self: Optional[StrictStr] = Field(default=None, description="generated field", alias="Self")
    location_info: Optional[LocationInfoLinked] = Field(default=None, alias="LocationInfo")
    tags: Optional[List[Tags]] = Field(default=None, alias="Tags")
    room_details: Optional[List[VenueRoomDetailsV2]] = Field(default=None, alias="RoomDetails")
    district_id: Optional[StrictStr] = Field(default=None, alias="DistrictId")
    related_content: Optional[List[RelatedContent]] = Field(default=None, alias="RelatedContent")
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    shortname: Optional[StrictStr] = Field(default=None, alias="Shortname")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    has_language: Optional[List[StrictStr]] = Field(default=None, alias="HasLanguage")
    mapping: Optional[Dict[str, Dict[str, StrictStr]]] = Field(default=None, alias="Mapping")
    additional_properties: Optional[AnnouncementAdditionalProperties] = Field(default=None, alias="AdditionalProperties")
    source: Optional[StrictStr] = Field(default=None, alias="Source")
    tag_ids: Optional[List[StrictStr]] = Field(default=None, alias="TagIds")
    __properties: ClassVar[List[str]] = ["Active", "GpsInfo", "GpsPoints", "Detail", "ContactInfos", "ImageGallery", "PublishedOn", "DistanceInfo", "OperationSchedule", "Self", "LocationInfo", "Tags", "RoomDetails", "DistrictId", "RelatedContent", "Id", "_Meta", "LicenseInfo", "Shortname", "FirstImport", "LastChange", "HasLanguage", "Mapping", "AdditionalProperties", "Source", "TagIds"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VenueV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "gps_points",
                "var_self",
                "district_id",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in gps_info (list)
        _items = []
        if self.gps_info:
            for _item in self.gps_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['GpsInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in gps_points (dict)
        _field_dict = {}
        if self.gps_points:
            for _key in self.gps_points:
                if self.gps_points[_key]:
                    _field_dict[_key] = self.gps_points[_key].to_dict()
            _dict['GpsPoints'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in detail (dict)
        _field_dict = {}
        if self.detail:
            for _key in self.detail:
                if self.detail[_key]:
                    _field_dict[_key] = self.detail[_key].to_dict()
            _dict['Detail'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in contact_infos (dict)
        _field_dict = {}
        if self.contact_infos:
            for _key in self.contact_infos:
                if self.contact_infos[_key]:
                    _field_dict[_key] = self.contact_infos[_key].to_dict()
            _dict['ContactInfos'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in image_gallery (list)
        _items = []
        if self.image_gallery:
            for _item in self.image_gallery:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ImageGallery'] = _items
        # override the default output from pydantic by calling `to_dict()` of distance_info
        if self.distance_info:
            _dict['DistanceInfo'] = self.distance_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in operation_schedule (list)
        _items = []
        if self.operation_schedule:
            for _item in self.operation_schedule:
                if _item:
                    _items.append(_item.to_dict())
            _dict['OperationSchedule'] = _items
        # override the default output from pydantic by calling `to_dict()` of location_info
        if self.location_info:
            _dict['LocationInfo'] = self.location_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in room_details (list)
        _items = []
        if self.room_details:
            for _item in self.room_details:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RoomDetails'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_content (list)
        _items = []
        if self.related_content:
            for _item in self.related_content:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RelatedContent'] = _items
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of additional_properties
        if self.additional_properties:
            _dict['AdditionalProperties'] = self.additional_properties.to_dict()
        # set to None if gps_info (nullable) is None
        # and model_fields_set contains the field
        if self.gps_info is None and "gps_info" in self.model_fields_set:
            _dict['GpsInfo'] = None

        # set to None if gps_points (nullable) is None
        # and model_fields_set contains the field
        if self.gps_points is None and "gps_points" in self.model_fields_set:
            _dict['GpsPoints'] = None

        # set to None if detail (nullable) is None
        # and model_fields_set contains the field
        if self.detail is None and "detail" in self.model_fields_set:
            _dict['Detail'] = None

        # set to None if contact_infos (nullable) is None
        # and model_fields_set contains the field
        if self.contact_infos is None and "contact_infos" in self.model_fields_set:
            _dict['ContactInfos'] = None

        # set to None if image_gallery (nullable) is None
        # and model_fields_set contains the field
        if self.image_gallery is None and "image_gallery" in self.model_fields_set:
            _dict['ImageGallery'] = None

        # set to None if published_on (nullable) is None
        # and model_fields_set contains the field
        if self.published_on is None and "published_on" in self.model_fields_set:
            _dict['PublishedOn'] = None

        # set to None if operation_schedule (nullable) is None
        # and model_fields_set contains the field
        if self.operation_schedule is None and "operation_schedule" in self.model_fields_set:
            _dict['OperationSchedule'] = None

        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['Tags'] = None

        # set to None if room_details (nullable) is None
        # and model_fields_set contains the field
        if self.room_details is None and "room_details" in self.model_fields_set:
            _dict['RoomDetails'] = None

        # set to None if district_id (nullable) is None
        # and model_fields_set contains the field
        if self.district_id is None and "district_id" in self.model_fields_set:
            _dict['DistrictId'] = None

        # set to None if related_content (nullable) is None
        # and model_fields_set contains the field
        if self.related_content is None and "related_content" in self.model_fields_set:
            _dict['RelatedContent'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['Shortname'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if has_language (nullable) is None
        # and model_fields_set contains the field
        if self.has_language is None and "has_language" in self.model_fields_set:
            _dict['HasLanguage'] = None

        # set to None if mapping (nullable) is None
        # and model_fields_set contains the field
        if self.mapping is None and "mapping" in self.model_fields_set:
            _dict['Mapping'] = None

        # set to None if additional_properties (nullable) is None
        # and model_fields_set contains the field
        if self.additional_properties is None and "additional_properties" in self.model_fields_set:
            _dict['AdditionalProperties'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['Source'] = None

        # set to None if tag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.tag_ids is None and "tag_ids" in self.model_fields_set:
            _dict['TagIds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of VenueV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Active": obj.get("Active"),
            "GpsInfo": [GpsInfo.from_dict(_item) for _item in obj.get("GpsInfo")] if obj.get("GpsInfo") is not None else None,
            "GpsPoints": dict(
                (_k, GpsInfo.from_dict(_v))
                for _k, _v in obj.get("GpsPoints").items()
            )
            if obj.get("GpsPoints") is not None
            else None,
            "Detail": dict(
                (_k, Detail.from_dict(_v))
                for _k, _v in obj.get("Detail").items()
            )
            if obj.get("Detail") is not None
            else None,
            "ContactInfos": dict(
                (_k, ContactInfos.from_dict(_v))
                for _k, _v in obj.get("ContactInfos").items()
            )
            if obj.get("ContactInfos") is not None
            else None,
            "ImageGallery": [ImageGallery.from_dict(_item) for _item in obj.get("ImageGallery")] if obj.get("ImageGallery") is not None else None,
            "PublishedOn": obj.get("PublishedOn"),
            "DistanceInfo": DistanceInfo.from_dict(obj.get("DistanceInfo")) if obj.get("DistanceInfo") is not None else None,
            "OperationSchedule": [OperationSchedule.from_dict(_item) for _item in obj.get("OperationSchedule")] if obj.get("OperationSchedule") is not None else None,
            "Self": obj.get("Self"),
            "LocationInfo": LocationInfoLinked.from_dict(obj.get("LocationInfo")) if obj.get("LocationInfo") is not None else None,
            "Tags": [Tags.from_dict(_item) for _item in obj.get("Tags")] if obj.get("Tags") is not None else None,
            "RoomDetails": [VenueRoomDetailsV2.from_dict(_item) for _item in obj.get("RoomDetails")] if obj.get("RoomDetails") is not None else None,
            "DistrictId": obj.get("DistrictId"),
            "RelatedContent": [RelatedContent.from_dict(_item) for _item in obj.get("RelatedContent")] if obj.get("RelatedContent") is not None else None,
            "Id": obj.get("Id"),
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "Shortname": obj.get("Shortname"),
            "FirstImport": obj.get("FirstImport"),
            "LastChange": obj.get("LastChange"),
            "HasLanguage": obj.get("HasLanguage"),
            "Mapping": obj.get("Mapping"),
            "AdditionalProperties": AnnouncementAdditionalProperties.from_dict(obj.get("AdditionalProperties")) if obj.get("AdditionalProperties") is not None else None,
            "Source": obj.get("Source"),
            "TagIds": obj.get("TagIds")
        })
        return _obj


