# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.forecast24_hours import Forecast24Hours
from openapi_server.models.forecast3_hours import Forecast3Hours
from openapi_server.models.gps_info import GpsInfo
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.location_info_linked import LocationInfoLinked
from openapi_server.models.metadata import Metadata
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WeatherForecastLinked(BaseModel):
    """
    WeatherForecastLinked
    """ # noqa: E501
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    var_self: Optional[StrictStr] = Field(default=None, description="generated field", alias="Self")
    location_info: Optional[LocationInfoLinked] = Field(default=None, alias="LocationInfo")
    var_date: Optional[datetime] = Field(default=None, alias="Date")
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    language: Optional[StrictStr] = Field(default=None, alias="Language")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    gps_info: Optional[List[GpsInfo]] = Field(default=None, alias="GpsInfo")
    municipality_istat_code: Optional[StrictStr] = Field(default=None, alias="MunicipalityIstatCode")
    shortname: Optional[StrictStr] = Field(default=None, alias="Shortname")
    municipality_name: Optional[Dict[str, StrictStr]] = Field(default=None, alias="MunicipalityName")
    fore_cast_daily: Optional[List[Forecast24Hours]] = Field(default=None, alias="ForeCastDaily")
    forecast3_hours_interval: Optional[List[Forecast3Hours]] = Field(default=None, alias="Forecast3HoursInterval")
    __properties: ClassVar[List[str]] = ["_Meta", "Self", "LocationInfo", "Date", "Id", "Language", "LicenseInfo", "FirstImport", "LastChange", "GpsInfo", "MunicipalityIstatCode", "Shortname", "MunicipalityName", "ForeCastDaily", "Forecast3HoursInterval"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WeatherForecastLinked from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_self",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location_info
        if self.location_info:
            _dict['LocationInfo'] = self.location_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in gps_info (list)
        _items = []
        if self.gps_info:
            for _item in self.gps_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['GpsInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in fore_cast_daily (list)
        _items = []
        if self.fore_cast_daily:
            for _item in self.fore_cast_daily:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ForeCastDaily'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in forecast3_hours_interval (list)
        _items = []
        if self.forecast3_hours_interval:
            for _item in self.forecast3_hours_interval:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Forecast3HoursInterval'] = _items
        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['Language'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if gps_info (nullable) is None
        # and model_fields_set contains the field
        if self.gps_info is None and "gps_info" in self.model_fields_set:
            _dict['GpsInfo'] = None

        # set to None if municipality_istat_code (nullable) is None
        # and model_fields_set contains the field
        if self.municipality_istat_code is None and "municipality_istat_code" in self.model_fields_set:
            _dict['MunicipalityIstatCode'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['Shortname'] = None

        # set to None if municipality_name (nullable) is None
        # and model_fields_set contains the field
        if self.municipality_name is None and "municipality_name" in self.model_fields_set:
            _dict['MunicipalityName'] = None

        # set to None if fore_cast_daily (nullable) is None
        # and model_fields_set contains the field
        if self.fore_cast_daily is None and "fore_cast_daily" in self.model_fields_set:
            _dict['ForeCastDaily'] = None

        # set to None if forecast3_hours_interval (nullable) is None
        # and model_fields_set contains the field
        if self.forecast3_hours_interval is None and "forecast3_hours_interval" in self.model_fields_set:
            _dict['Forecast3HoursInterval'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WeatherForecastLinked from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "Self": obj.get("Self"),
            "LocationInfo": LocationInfoLinked.from_dict(obj.get("LocationInfo")) if obj.get("LocationInfo") is not None else None,
            "Date": obj.get("Date"),
            "Id": obj.get("Id"),
            "Language": obj.get("Language"),
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "FirstImport": obj.get("FirstImport"),
            "LastChange": obj.get("LastChange"),
            "GpsInfo": [GpsInfo.from_dict(_item) for _item in obj.get("GpsInfo")] if obj.get("GpsInfo") is not None else None,
            "MunicipalityIstatCode": obj.get("MunicipalityIstatCode"),
            "Shortname": obj.get("Shortname"),
            "MunicipalityName": obj.get("MunicipalityName"),
            "ForeCastDaily": [Forecast24Hours.from_dict(_item) for _item in obj.get("ForeCastDaily")] if obj.get("ForeCastDaily") is not None else None,
            "Forecast3HoursInterval": [Forecast3Hours.from_dict(_item) for _item in obj.get("Forecast3HoursInterval")] if obj.get("Forecast3HoursInterval") is not None else None
        })
        return _obj


