# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.area_link import AreaLink
from openapi_server.models.contact_infos import ContactInfos
from openapi_server.models.detail import Detail
from openapi_server.models.gps_info import GpsInfo
from openapi_server.models.image_gallery import ImageGallery
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.metadata import Metadata
from openapi_server.models.odh_tags import ODHTags
from openapi_server.models.publishedon_object import PublishedonObject
from openapi_server.models.related_content import RelatedContent
from openapi_server.models.tags import Tags
from openapi_server.models.video_items import VideoItems
from openapi_server.models.webcam_properties import WebcamProperties
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WebcamInfoLinked(BaseModel):
    """
    WebcamInfoLinked
    """ # noqa: E501
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    var_self: Optional[StrictStr] = Field(default=None, description="generated field", alias="Self")
    odh_active: Optional[StrictBool] = Field(default=None, description="generated field", alias="OdhActive")
    areas: Optional[List[AreaLink]] = Field(default=None, description="generated field", alias="Areas")
    odh_tags: Optional[List[ODHTags]] = Field(default=None, description="generated field", alias="ODHTags")
    tags: Optional[List[Tags]] = Field(default=None, alias="Tags")
    tag_ids: Optional[List[StrictStr]] = Field(default=None, alias="TagIds")
    additional_properties: Optional[Dict[str, Any]] = Field(default=None, alias="AdditionalProperties")
    related_content: Optional[List[RelatedContent]] = Field(default=None, alias="RelatedContent")
    gps_info: Optional[List[GpsInfo]] = Field(default=None, alias="GpsInfo")
    gps_points: Optional[Dict[str, GpsInfo]] = Field(default=None, description="Deprecated, use GpsInfo", alias="GpsPoints")
    contact_infos: Optional[Dict[str, ContactInfos]] = Field(default=None, alias="ContactInfos")
    image_gallery: Optional[List[ImageGallery]] = Field(default=None, alias="ImageGallery")
    video_items: Optional[Dict[str, List[VideoItems]]] = Field(default=None, alias="VideoItems")
    detail: Optional[Dict[str, Detail]] = Field(default=None, alias="Detail")
    web_cam_properties: Optional[WebcamProperties] = Field(default=None, alias="WebCamProperties")
    webcamname: Optional[Dict[str, StrictStr]] = Field(default=None, description="generated field", alias="Webcamname")
    webcamurl: Optional[StrictStr] = Field(default=None, description="generated field", alias="Webcamurl")
    streamurl: Optional[StrictStr] = Field(default=None, description="generated field", alias="Streamurl")
    previewurl: Optional[StrictStr] = Field(default=None, description="generated field", alias="Previewurl")
    has_language: Optional[List[StrictStr]] = Field(default=None, alias="HasLanguage")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    shortname: Optional[StrictStr] = Field(default=None, alias="Shortname")
    active: Optional[StrictBool] = Field(default=None, alias="Active")
    smg_active: Optional[StrictBool] = Field(default=None, description="Obsolete, use PublishedOn", alias="SmgActive")
    webcam_assigned_on: Optional[List[PublishedonObject]] = Field(default=None, alias="WebcamAssignedOn")
    area_ids: Optional[List[StrictStr]] = Field(default=None, alias="AreaIds")
    smg_tags: Optional[List[StrictStr]] = Field(default=None, alias="SmgTags")
    published_on: Optional[List[StrictStr]] = Field(default=None, alias="PublishedOn")
    mapping: Optional[Dict[str, Dict[str, StrictStr]]] = Field(default=None, alias="Mapping")
    webcam_id: Optional[StrictStr] = Field(default=None, alias="WebcamId")
    list_position: Optional[StrictInt] = Field(default=None, alias="ListPosition")
    source: Optional[StrictStr] = Field(default=None, alias="Source")
    __properties: ClassVar[List[str]] = ["_Meta", "Self", "OdhActive", "Areas", "ODHTags", "Tags", "TagIds", "AdditionalProperties", "RelatedContent", "GpsInfo", "GpsPoints", "ContactInfos", "ImageGallery", "VideoItems", "Detail", "WebCamProperties", "Webcamname", "Webcamurl", "Streamurl", "Previewurl", "HasLanguage", "LicenseInfo", "Id", "LastChange", "FirstImport", "Shortname", "Active", "SmgActive", "WebcamAssignedOn", "AreaIds", "SmgTags", "PublishedOn", "Mapping", "WebcamId", "ListPosition", "Source"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebcamInfoLinked from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_self",
                "odh_active",
                "areas",
                "odh_tags",
                "gps_points",
                "webcamname",
                "webcamurl",
                "streamurl",
                "previewurl",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in areas (list)
        _items = []
        if self.areas:
            for _item in self.areas:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Areas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in odh_tags (list)
        _items = []
        if self.odh_tags:
            for _item in self.odh_tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ODHTags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in related_content (list)
        _items = []
        if self.related_content:
            for _item in self.related_content:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RelatedContent'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in gps_info (list)
        _items = []
        if self.gps_info:
            for _item in self.gps_info:
                if _item:
                    _items.append(_item.to_dict())
            _dict['GpsInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in gps_points (dict)
        _field_dict = {}
        if self.gps_points:
            for _key in self.gps_points:
                if self.gps_points[_key]:
                    _field_dict[_key] = self.gps_points[_key].to_dict()
            _dict['GpsPoints'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in contact_infos (dict)
        _field_dict = {}
        if self.contact_infos:
            for _key in self.contact_infos:
                if self.contact_infos[_key]:
                    _field_dict[_key] = self.contact_infos[_key].to_dict()
            _dict['ContactInfos'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in image_gallery (list)
        _items = []
        if self.image_gallery:
            for _item in self.image_gallery:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ImageGallery'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in video_items (dict of array)
        _field_dict_of_array = {}
        if self.video_items:
            for _key in self.video_items:
                if self.video_items[_key] is not None:
                    _field_dict_of_array[_key] = [
                        _item.to_dict() for _item in self.video_items[_key]
                    ]
            _dict['VideoItems'] = _field_dict_of_array
        # override the default output from pydantic by calling `to_dict()` of each value in detail (dict)
        _field_dict = {}
        if self.detail:
            for _key in self.detail:
                if self.detail[_key]:
                    _field_dict[_key] = self.detail[_key].to_dict()
            _dict['Detail'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of web_cam_properties
        if self.web_cam_properties:
            _dict['WebCamProperties'] = self.web_cam_properties.to_dict()
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in webcam_assigned_on (list)
        _items = []
        if self.webcam_assigned_on:
            for _item in self.webcam_assigned_on:
                if _item:
                    _items.append(_item.to_dict())
            _dict['WebcamAssignedOn'] = _items
        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if areas (nullable) is None
        # and model_fields_set contains the field
        if self.areas is None and "areas" in self.model_fields_set:
            _dict['Areas'] = None

        # set to None if odh_tags (nullable) is None
        # and model_fields_set contains the field
        if self.odh_tags is None and "odh_tags" in self.model_fields_set:
            _dict['ODHTags'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['Tags'] = None

        # set to None if tag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.tag_ids is None and "tag_ids" in self.model_fields_set:
            _dict['TagIds'] = None

        # set to None if additional_properties (nullable) is None
        # and model_fields_set contains the field
        if self.additional_properties is None and "additional_properties" in self.model_fields_set:
            _dict['AdditionalProperties'] = None

        # set to None if related_content (nullable) is None
        # and model_fields_set contains the field
        if self.related_content is None and "related_content" in self.model_fields_set:
            _dict['RelatedContent'] = None

        # set to None if gps_info (nullable) is None
        # and model_fields_set contains the field
        if self.gps_info is None and "gps_info" in self.model_fields_set:
            _dict['GpsInfo'] = None

        # set to None if gps_points (nullable) is None
        # and model_fields_set contains the field
        if self.gps_points is None and "gps_points" in self.model_fields_set:
            _dict['GpsPoints'] = None

        # set to None if contact_infos (nullable) is None
        # and model_fields_set contains the field
        if self.contact_infos is None and "contact_infos" in self.model_fields_set:
            _dict['ContactInfos'] = None

        # set to None if image_gallery (nullable) is None
        # and model_fields_set contains the field
        if self.image_gallery is None and "image_gallery" in self.model_fields_set:
            _dict['ImageGallery'] = None

        # set to None if video_items (nullable) is None
        # and model_fields_set contains the field
        if self.video_items is None and "video_items" in self.model_fields_set:
            _dict['VideoItems'] = None

        # set to None if detail (nullable) is None
        # and model_fields_set contains the field
        if self.detail is None and "detail" in self.model_fields_set:
            _dict['Detail'] = None

        # set to None if webcamname (nullable) is None
        # and model_fields_set contains the field
        if self.webcamname is None and "webcamname" in self.model_fields_set:
            _dict['Webcamname'] = None

        # set to None if webcamurl (nullable) is None
        # and model_fields_set contains the field
        if self.webcamurl is None and "webcamurl" in self.model_fields_set:
            _dict['Webcamurl'] = None

        # set to None if streamurl (nullable) is None
        # and model_fields_set contains the field
        if self.streamurl is None and "streamurl" in self.model_fields_set:
            _dict['Streamurl'] = None

        # set to None if previewurl (nullable) is None
        # and model_fields_set contains the field
        if self.previewurl is None and "previewurl" in self.model_fields_set:
            _dict['Previewurl'] = None

        # set to None if has_language (nullable) is None
        # and model_fields_set contains the field
        if self.has_language is None and "has_language" in self.model_fields_set:
            _dict['HasLanguage'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['Shortname'] = None

        # set to None if webcam_assigned_on (nullable) is None
        # and model_fields_set contains the field
        if self.webcam_assigned_on is None and "webcam_assigned_on" in self.model_fields_set:
            _dict['WebcamAssignedOn'] = None

        # set to None if area_ids (nullable) is None
        # and model_fields_set contains the field
        if self.area_ids is None and "area_ids" in self.model_fields_set:
            _dict['AreaIds'] = None

        # set to None if smg_tags (nullable) is None
        # and model_fields_set contains the field
        if self.smg_tags is None and "smg_tags" in self.model_fields_set:
            _dict['SmgTags'] = None

        # set to None if published_on (nullable) is None
        # and model_fields_set contains the field
        if self.published_on is None and "published_on" in self.model_fields_set:
            _dict['PublishedOn'] = None

        # set to None if mapping (nullable) is None
        # and model_fields_set contains the field
        if self.mapping is None and "mapping" in self.model_fields_set:
            _dict['Mapping'] = None

        # set to None if webcam_id (nullable) is None
        # and model_fields_set contains the field
        if self.webcam_id is None and "webcam_id" in self.model_fields_set:
            _dict['WebcamId'] = None

        # set to None if list_position (nullable) is None
        # and model_fields_set contains the field
        if self.list_position is None and "list_position" in self.model_fields_set:
            _dict['ListPosition'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['Source'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WebcamInfoLinked from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "Self": obj.get("Self"),
            "OdhActive": obj.get("OdhActive"),
            "Areas": [AreaLink.from_dict(_item) for _item in obj.get("Areas")] if obj.get("Areas") is not None else None,
            "ODHTags": [ODHTags.from_dict(_item) for _item in obj.get("ODHTags")] if obj.get("ODHTags") is not None else None,
            "Tags": [Tags.from_dict(_item) for _item in obj.get("Tags")] if obj.get("Tags") is not None else None,
            "TagIds": obj.get("TagIds"),
            "AdditionalProperties": obj.get("AdditionalProperties"),
            "RelatedContent": [RelatedContent.from_dict(_item) for _item in obj.get("RelatedContent")] if obj.get("RelatedContent") is not None else None,
            "GpsInfo": [GpsInfo.from_dict(_item) for _item in obj.get("GpsInfo")] if obj.get("GpsInfo") is not None else None,
            "GpsPoints": dict(
                (_k, GpsInfo.from_dict(_v))
                for _k, _v in obj.get("GpsPoints").items()
            )
            if obj.get("GpsPoints") is not None
            else None,
            "ContactInfos": dict(
                (_k, ContactInfos.from_dict(_v))
                for _k, _v in obj.get("ContactInfos").items()
            )
            if obj.get("ContactInfos") is not None
            else None,
            "ImageGallery": [ImageGallery.from_dict(_item) for _item in obj.get("ImageGallery")] if obj.get("ImageGallery") is not None else None,
            "VideoItems": dict(
                (_k,
                        [VideoItems.from_dict(_item) for _item in _v]
                        if _v is not None
                        else None
                )
                for _k, _v in obj.get("VideoItems").items()
            ),
            "Detail": dict(
                (_k, Detail.from_dict(_v))
                for _k, _v in obj.get("Detail").items()
            )
            if obj.get("Detail") is not None
            else None,
            "WebCamProperties": WebcamProperties.from_dict(obj.get("WebCamProperties")) if obj.get("WebCamProperties") is not None else None,
            "Webcamname": obj.get("Webcamname"),
            "Webcamurl": obj.get("Webcamurl"),
            "Streamurl": obj.get("Streamurl"),
            "Previewurl": obj.get("Previewurl"),
            "HasLanguage": obj.get("HasLanguage"),
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "Id": obj.get("Id"),
            "LastChange": obj.get("LastChange"),
            "FirstImport": obj.get("FirstImport"),
            "Shortname": obj.get("Shortname"),
            "Active": obj.get("Active"),
            "SmgActive": obj.get("SmgActive"),
            "WebcamAssignedOn": [PublishedonObject.from_dict(_item) for _item in obj.get("WebcamAssignedOn")] if obj.get("WebcamAssignedOn") is not None else None,
            "AreaIds": obj.get("AreaIds"),
            "SmgTags": obj.get("SmgTags"),
            "PublishedOn": obj.get("PublishedOn"),
            "Mapping": obj.get("Mapping"),
            "WebcamId": obj.get("WebcamId"),
            "ListPosition": obj.get("ListPosition"),
            "Source": obj.get("Source")
        })
        return _obj


