# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WebcamProperties(BaseModel):
    """
    WebcamProperties
    """ # noqa: E501
    webcam_url: Optional[StrictStr] = Field(default=None, alias="WebcamUrl")
    stream_url: Optional[StrictStr] = Field(default=None, alias="StreamUrl")
    preview_url: Optional[StrictStr] = Field(default=None, alias="PreviewUrl")
    view_angle_degree: Optional[StrictStr] = Field(default=None, alias="ViewAngleDegree")
    zero_direction: Optional[StrictStr] = Field(default=None, alias="ZeroDirection")
    html_embed: Optional[StrictStr] = Field(default=None, alias="HtmlEmbed")
    tour_cam: Optional[StrictBool] = Field(default=None, alias="TourCam")
    has_vr: Optional[StrictBool] = Field(default=None, alias="HasVR")
    viewer_type: Optional[StrictStr] = Field(default=None, alias="ViewerType")
    __properties: ClassVar[List[str]] = ["WebcamUrl", "StreamUrl", "PreviewUrl", "ViewAngleDegree", "ZeroDirection", "HtmlEmbed", "TourCam", "HasVR", "ViewerType"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebcamProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if webcam_url (nullable) is None
        # and model_fields_set contains the field
        if self.webcam_url is None and "webcam_url" in self.model_fields_set:
            _dict['WebcamUrl'] = None

        # set to None if stream_url (nullable) is None
        # and model_fields_set contains the field
        if self.stream_url is None and "stream_url" in self.model_fields_set:
            _dict['StreamUrl'] = None

        # set to None if preview_url (nullable) is None
        # and model_fields_set contains the field
        if self.preview_url is None and "preview_url" in self.model_fields_set:
            _dict['PreviewUrl'] = None

        # set to None if view_angle_degree (nullable) is None
        # and model_fields_set contains the field
        if self.view_angle_degree is None and "view_angle_degree" in self.model_fields_set:
            _dict['ViewAngleDegree'] = None

        # set to None if zero_direction (nullable) is None
        # and model_fields_set contains the field
        if self.zero_direction is None and "zero_direction" in self.model_fields_set:
            _dict['ZeroDirection'] = None

        # set to None if html_embed (nullable) is None
        # and model_fields_set contains the field
        if self.html_embed is None and "html_embed" in self.model_fields_set:
            _dict['HtmlEmbed'] = None

        # set to None if tour_cam (nullable) is None
        # and model_fields_set contains the field
        if self.tour_cam is None and "tour_cam" in self.model_fields_set:
            _dict['TourCam'] = None

        # set to None if has_vr (nullable) is None
        # and model_fields_set contains the field
        if self.has_vr is None and "has_vr" in self.model_fields_set:
            _dict['HasVR'] = None

        # set to None if viewer_type (nullable) is None
        # and model_fields_set contains the field
        if self.viewer_type is None and "viewer_type" in self.model_fields_set:
            _dict['ViewerType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WebcamProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "WebcamUrl": obj.get("WebcamUrl"),
            "StreamUrl": obj.get("StreamUrl"),
            "PreviewUrl": obj.get("PreviewUrl"),
            "ViewAngleDegree": obj.get("ViewAngleDegree"),
            "ZeroDirection": obj.get("ZeroDirection"),
            "HtmlEmbed": obj.get("HtmlEmbed"),
            "TourCam": obj.get("TourCam"),
            "HasVR": obj.get("HasVR"),
            "ViewerType": obj.get("ViewerType")
        })
        return _obj


