# coding: utf-8

"""
    Open Data Hub Tourism Api

    Open Data Hub Tourism Api based on .Net Core with PostgreSQL

    The version of the OpenAPI document: v1
    Contact: help@opendatahub.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.company_link import CompanyLink
from openapi_server.models.detail import Detail
from openapi_server.models.image_gallery import ImageGallery
from openapi_server.models.license_info import LicenseInfo
from openapi_server.models.metadata import Metadata
from openapi_server.models.related_content import RelatedContent
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class WineLinked(BaseModel):
    """
    WineLinked
    """ # noqa: E501
    meta: Optional[Metadata] = Field(default=None, alias="_Meta")
    var_self: Optional[StrictStr] = Field(default=None, description="generated field", alias="Self")
    odh_active: Optional[StrictBool] = Field(default=None, description="generated field", alias="OdhActive")
    company: Optional[CompanyLink] = Field(default=None, alias="Company")
    additional_properties: Optional[Dict[str, Any]] = Field(default=None, alias="AdditionalProperties")
    related_content: Optional[List[RelatedContent]] = Field(default=None, alias="RelatedContent")
    license_info: Optional[LicenseInfo] = Field(default=None, alias="LicenseInfo")
    id: Optional[StrictStr] = Field(default=None, alias="Id")
    shortname: Optional[StrictStr] = Field(default=None, alias="Shortname")
    detail: Optional[Dict[str, Detail]] = Field(default=None, alias="Detail")
    vintage: Optional[StrictInt] = Field(default=None, alias="Vintage")
    awardyear: Optional[StrictInt] = Field(default=None, alias="Awardyear")
    custom_id: Optional[StrictStr] = Field(default=None, description="Id on the primary data Source", alias="CustomId")
    company_id: Optional[StrictStr] = Field(default=None, alias="CompanyId")
    image_gallery: Optional[List[ImageGallery]] = Field(default=None, alias="ImageGallery")
    awards: Optional[List[StrictStr]] = Field(default=None, alias="Awards")
    last_change: Optional[datetime] = Field(default=None, alias="LastChange")
    first_import: Optional[datetime] = Field(default=None, alias="FirstImport")
    active: Optional[StrictBool] = Field(default=None, alias="Active")
    smg_active: Optional[StrictBool] = Field(default=None, description="Obsolete, use PublishedOn", alias="SmgActive")
    has_language: Optional[List[StrictStr]] = Field(default=None, alias="HasLanguage")
    source: Optional[StrictStr] = Field(default=None, alias="Source")
    mapping: Optional[Dict[str, Dict[str, StrictStr]]] = Field(default=None, alias="Mapping")
    published_on: Optional[List[StrictStr]] = Field(default=None, alias="PublishedOn")
    __properties: ClassVar[List[str]] = ["_Meta", "Self", "OdhActive", "Company", "AdditionalProperties", "RelatedContent", "LicenseInfo", "Id", "Shortname", "Detail", "Vintage", "Awardyear", "CustomId", "CompanyId", "ImageGallery", "Awards", "LastChange", "FirstImport", "Active", "SmgActive", "HasLanguage", "Source", "Mapping", "PublishedOn"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WineLinked from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
                "var_self",
                "odh_active",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['_Meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['Company'] = self.company.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in related_content (list)
        _items = []
        if self.related_content:
            for _item in self.related_content:
                if _item:
                    _items.append(_item.to_dict())
            _dict['RelatedContent'] = _items
        # override the default output from pydantic by calling `to_dict()` of license_info
        if self.license_info:
            _dict['LicenseInfo'] = self.license_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in detail (dict)
        _field_dict = {}
        if self.detail:
            for _key in self.detail:
                if self.detail[_key]:
                    _field_dict[_key] = self.detail[_key].to_dict()
            _dict['Detail'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in image_gallery (list)
        _items = []
        if self.image_gallery:
            for _item in self.image_gallery:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ImageGallery'] = _items
        # set to None if var_self (nullable) is None
        # and model_fields_set contains the field
        if self.var_self is None and "var_self" in self.model_fields_set:
            _dict['Self'] = None

        # set to None if additional_properties (nullable) is None
        # and model_fields_set contains the field
        if self.additional_properties is None and "additional_properties" in self.model_fields_set:
            _dict['AdditionalProperties'] = None

        # set to None if related_content (nullable) is None
        # and model_fields_set contains the field
        if self.related_content is None and "related_content" in self.model_fields_set:
            _dict['RelatedContent'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if shortname (nullable) is None
        # and model_fields_set contains the field
        if self.shortname is None and "shortname" in self.model_fields_set:
            _dict['Shortname'] = None

        # set to None if detail (nullable) is None
        # and model_fields_set contains the field
        if self.detail is None and "detail" in self.model_fields_set:
            _dict['Detail'] = None

        # set to None if custom_id (nullable) is None
        # and model_fields_set contains the field
        if self.custom_id is None and "custom_id" in self.model_fields_set:
            _dict['CustomId'] = None

        # set to None if company_id (nullable) is None
        # and model_fields_set contains the field
        if self.company_id is None and "company_id" in self.model_fields_set:
            _dict['CompanyId'] = None

        # set to None if image_gallery (nullable) is None
        # and model_fields_set contains the field
        if self.image_gallery is None and "image_gallery" in self.model_fields_set:
            _dict['ImageGallery'] = None

        # set to None if awards (nullable) is None
        # and model_fields_set contains the field
        if self.awards is None and "awards" in self.model_fields_set:
            _dict['Awards'] = None

        # set to None if last_change (nullable) is None
        # and model_fields_set contains the field
        if self.last_change is None and "last_change" in self.model_fields_set:
            _dict['LastChange'] = None

        # set to None if first_import (nullable) is None
        # and model_fields_set contains the field
        if self.first_import is None and "first_import" in self.model_fields_set:
            _dict['FirstImport'] = None

        # set to None if has_language (nullable) is None
        # and model_fields_set contains the field
        if self.has_language is None and "has_language" in self.model_fields_set:
            _dict['HasLanguage'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['Source'] = None

        # set to None if mapping (nullable) is None
        # and model_fields_set contains the field
        if self.mapping is None and "mapping" in self.model_fields_set:
            _dict['Mapping'] = None

        # set to None if published_on (nullable) is None
        # and model_fields_set contains the field
        if self.published_on is None and "published_on" in self.model_fields_set:
            _dict['PublishedOn'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of WineLinked from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_Meta": Metadata.from_dict(obj.get("_Meta")) if obj.get("_Meta") is not None else None,
            "Self": obj.get("Self"),
            "OdhActive": obj.get("OdhActive"),
            "Company": CompanyLink.from_dict(obj.get("Company")) if obj.get("Company") is not None else None,
            "AdditionalProperties": obj.get("AdditionalProperties"),
            "RelatedContent": [RelatedContent.from_dict(_item) for _item in obj.get("RelatedContent")] if obj.get("RelatedContent") is not None else None,
            "LicenseInfo": LicenseInfo.from_dict(obj.get("LicenseInfo")) if obj.get("LicenseInfo") is not None else None,
            "Id": obj.get("Id"),
            "Shortname": obj.get("Shortname"),
            "Detail": dict(
                (_k, Detail.from_dict(_v))
                for _k, _v in obj.get("Detail").items()
            )
            if obj.get("Detail") is not None
            else None,
            "Vintage": obj.get("Vintage"),
            "Awardyear": obj.get("Awardyear"),
            "CustomId": obj.get("CustomId"),
            "CompanyId": obj.get("CompanyId"),
            "ImageGallery": [ImageGallery.from_dict(_item) for _item in obj.get("ImageGallery")] if obj.get("ImageGallery") is not None else None,
            "Awards": obj.get("Awards"),
            "LastChange": obj.get("LastChange"),
            "FirstImport": obj.get("FirstImport"),
            "Active": obj.get("Active"),
            "SmgActive": obj.get("SmgActive"),
            "HasLanguage": obj.get("HasLanguage"),
            "Source": obj.get("Source"),
            "Mapping": obj.get("Mapping"),
            "PublishedOn": obj.get("PublishedOn")
        })
        return _obj


